---
title: "Released Datasets"
execute:
  echo: false
---
This document provides a list of datasets as part of the novust 2025 released. Each dataset is described briefly, including whether it contains Protected Health Information (PHI) or if the PHI has been scrubbed. 

### OMOP Datasets
| Dataset Name | Description |
|:------------|:------------|
| `som-rit-phi-oncology-prod.oncology_omop_phi_irb76049_nov2025`| Oncology OMOP-CDM v5.4.1 dataset with PHI| 
| `som-rit-phi-oncology-prod.oncology_omop_confidential_irb76049_nov2025`| Oncology OMOP-CDM v5.4.1 dataset with PHI Scrubbed|


### NeuralFrame Datasets
| Dataset Name | Description |
|:------------|:------------|
| `som-rit-phi-oncology-prod.oncology_neuralframe_phi_irb76049_nov2025`| NeuralFrame dataset with PHI | 
| `som-rit-phi-oncology-prod.oncology_neuralframe_confidential_irb76049_nov2025`| NeuralFrame dataset with PHI Scrubbed |

### Philips ISPM Datasets
| Dataset Name | Description |
|:------------|:------------|
| `som-rit-phi-oncology-prod.oncology_philips_phi_irb76049_nov2025`| Philips ISPM dataset with PHI | 
| `som-rit-phi-oncology-prod.oncology_philips_confidential_irb76049_nov2025`| Philips ISPM dataset with PHI Scrubbed |

### STAMP Add-On Data
| Dataset Name | Description |
|:------------|:------------|
|`som-rit-phi-oncology-prod.oncology_stamp_add_on_data_irb76049_nov2025.stamp_add_on_data_phi`| STAMP add on dataset with PHI | 
|`som-rit-phi-oncology-prod.oncology_stamp_add_on_data_irb76049_nov2025.stamp_add_on_data_confidential`| STAMP add on dataset Scrubbed |
:  {.hover .responsive .sm}

### HIPPO Benchmark
| Dataset Name | Description |
|:------------|:------------|
|`som-rit-phi-oncology-prod.oncology_annotations_phi_irb76049_nov2025`| BigQuery Dataset with the PHI annotations| 
:  {.hover .responsive .sm}

### Lung Resection CAP Forms

| Dataset Name | Description |
|:------------|:------------|
|`som-rit-phi-oncology-prod.oncology_cap_forms_phi_irb76049_nov2025`| BigQuery Dataset with CAP Forms tables| 
|`gs://oncology-cap-forms.us-west1.starr-data.us/shc_cap_forms_qa_20250825.tar.gz`| GCS bucket with QA cleaned dataset |
:  {.hover .responsive .sm}

### Epic Media Server Documents
| Dataset Name | Description |
|:------------|:------------|
|`som-rit-phi-oncology-prod.epic_media_server_documents.pdfs_arpah_cancer_patients`| BigQuery dataset with the metadata and GCS location for all the PDFs that we downloaded from the EPIC Media Server for all Cancer patients | 
:  {.hover .responsive .sm}