---
title: "care_site"
---

Standarized Health System Data Tables

### Table Columns

| field                                               | type    | required   | phi   | phi scrubbing operation   |
|:----------------------------------------------------|:--------|:-----------|:------|:--------------------------|
| care_site_id                                        | INTEGER | Yes        | Yes   | Sub with Stable between Data Refreshes                    |
| care_site_name                                      | STRING  | No         |       |                           |
| place_of_service_concept_id                         | INTEGER | Yes        |       |                           |
| location_id                                         | INTEGER | No         | Yes   | Sub Not Stable between Data Refreshes                    |
| care_site_source_value                              | STRING  | No         | Yes   | Del                       |
| place_of_service_source_value                       | STRING  | No         |       |                           |
:  {.hover .responsive .sm}

### Columns Description


##### care_site_id

A unique identifier for each Care Site.

##### care_site_name

The verbatim description or name of the Care Site as in data source

##### place_of_service_concept_id

A foreign key that refers to a Place of Service Concept ID in the Standardized Vocabularies.

##### location_id

A foreign key to the geographic Location in the LOCATION table, where the detailed address information is stored.

##### care_site_source_value

The identifier for the Care Site in the source data, stored here for reference.

##### place_of_service_source_value

The source code for the Place of Service as it appears in the source data, stored here for reference.

