---
title: "concept"
---

Vocabulary Tables

### Table Columns

| field                                               | type    | required   | phi   |   phi scrubbing operation |
|:----------------------------------------------------|:--------|:-----------|:------|--------------------------:|
| concept_id                                          | INTEGER | Yes        |       |                        |
| concept_name                                        | STRING  | Yes        |       |                        |
| domain_id                                           | STRING  | Yes        |       |                        |
| vocabulary_id                                       | STRING  | Yes        |       |                        |
| concept_class_id                                    | STRING  | Yes        |       |                        |
| standard_concept                                    | STRING  | No         |       |                        |
| concept_code                                        | STRING  | Yes        |       |                        |
| valid_start_date                                    | DATE    | Yes        |       |                        |
| valid_end_date                                      | DATE    | Yes        |       |                        |
| invalid_reason                                      | STRING  | No         |       |                        |


:  {.hover .responsive .sm}

### Columns Description


##### concept_id

A unique identifier for each Concept across all domains.

##### concept_name

An unambiguous, meaningful and descriptive name for the Concept.

##### domain_id

A foreign key to the DOMAIN table the Concept belongs to.

##### vocabulary_id

A foreign key to the VOCABULARY table indicating from which source the Concept has been adapted.

##### concept_class_id

The attribute or concept class of the Concept. Examples are 'Clinical Drug', 'Ingredient', 'Clinical Finding' etc.

##### standard_concept

This flag determines where a Concept is a Standard Concept, i.e. is used in the data, a Classification Concept, or a non-standard Source Concept. The allowables values are 'S' (Standard Concept) and 'C' (Classification Concept), otherwise the content is NULL.

##### concept_code

The concept code represents the identifier of the Concept in the source vocabulary, such as SNOMED-CT concept IDs, RxNorm RXCUIs etc. Note that concept codes are not unique across vocabularies.

##### valid_start_date

The date when the Concept was first recorded. The default value is 1-Jan-1970, meaning, the Concept has no (known) date of inception.

##### valid_end_date

The date when the Concept became invalid because it was deleted or superseded (updated) by a new concept. The default value is 31-Dec-2099, meaning, the Concept is valid until it becomes deprecated.

##### invalid_reason

Reason the Concept was invalidated. Possible values are D (deleted), U (replaced with an update) or NULL when valid_end_date has the default value.

