---
title: "device_exposure"
---

Standard Clinical Data Table

### Table Columns

| field                                               | type     | required   | phi   | phi scrubbing operation   |
|:----------------------------------------------------|:---------|:-----------|:------|:--------------------------|
| device_exposure_id                                  | INTEGER  | Yes        | Yes   | Not Stable between Data Refreshes                    |
| person_id                                           | INTEGER  | Yes        | Yes   | Sub                       |
| device_concept_id                                   | INTEGER  | Yes        |       |                        |
| device_exposure_start_date                          | DATE     | No         | Yes   | Jitter                    |
| device_exposure_start_datetime                      | DATETIME | Yes        | Yes   | Jitter                    |
| device_exposure_end_date                            | DATE     | No         | Yes   | Jitter                    |
| device_exposure_end_datetime                        | DATETIME | No         | Yes   | Jitter                    |
| device_type_concept_id                              | INTEGER  | Yes        |       |                        |
| unique_device_id                                    | STRING   | No         |       |                        |
| quantity                                            | INTEGER  | No         |       |                        |
| provider_id                                         | INTEGER  | No         | Yes   | Not Stable between Data Refreshes                    |
| visit_occurrence_id                                 | INTEGER  | No         |       | Not Stable between Data Refreshes                    |
| visit_detail_id                                     | INTEGER  | No         |       | Not Stable between Data Refreshes                    |
| device_source_value                                 | STRING   | No         |       |                        |
| device_source_concept_id                            | INTEGER  | Yes        |       |                        |
| production_id                                       | STRING   | No         |       |                        |
| unit_concept_id                                     | INT64    | No         |       |                        |
| unit_source_concept_id                              | INT64    | No         |       |                        |
| unit_source_value                                   | STRING   | No         |       |                        |


:  {.hover .responsive .sm}

### Columns Description


##### device_exposure_id

A system-generated unique identifier for each Device Exposure.

##### person_id

A foreign key identifier to the Person who is subjected to the Device. The demographic details of that Person are stored in the PERSON table.

##### device_concept_id

A foreign key that refers to a Standard Concept identifier in the Standardized Vocabularies belonging to the 'Device' domain.

##### device_exposure_start_date

The date the Device or supply was applied or used.

##### device_exposure_start_datetime

The date and time the Device or supply was applied or used.

##### device_exposure_end_date

The date use of the Device or supply was ceased.

##### device_exposure_end_datetime

The date and time use of the Device or supply was ceased.

##### device_type_concept_id

This field can be used to determine the provenance of the record, as in whether the condition was from an EHR system, insurance claim, registry, or other sources.

##### unique_device_id

A UDI or equivalent identifying the instance of the Device used in the Person.

##### quantity

The number of individual Devices used in the exposure.

##### provider_id

A foreign key to the provider in the PROVIDER table who initiated or administered the Device.

##### visit_occurrence_id

A foreign key to the visit in the VISIT_OCCURRENCE table during which the Device was used.

##### visit_detail_id

A foreign key to the visit detail record in the VISIT_DETAIL table during which the Device was used.

##### device_source_value

The source code for the Device as it appears in the source data. This code is mapped to a Standard Device Concept in the Standardized Vocabularies and the original code is stored here for reference.

##### device_source_concept_id

A foreign key to a Device Concept that refers to the code used in the source.

##### production_id

The production or lot number of the Device.

##### unit_concept_id

A foreign key that refers to a Standard Concept identifier for the unit of measurement of the quantity.

##### unit_source_concept_id

A foreign key to a Concept that refers to the source unit code in the source data.

##### unit_source_value

The source code for the unit as it appears in the source data.

