---
title: "source_to_concept_map"
---

## Description
The source to concept map table is a legacy data structure within the OMOP Common Data Model, recommended for use in ETL processes to maintain local source codes which are not available as Concepts in the Standardized Vocabularies, and to establish mappings for each source code into a Standard Concept as target_concept_ids that can be used to populate the Common Data Model tables.

Standard Clinical Data Table

### Table Columns

| field | type | required |
|:------|:-----|:---------|
| source_code | varchar(50) | Yes |
| source_concept_id | integer | Yes |
| source_vocabulary_id | varchar(20) | Yes |
| source_code_description | varchar(255) | No |
| target_concept_id | integer | Yes |
| target_vocabulary_id | varchar(20) | Yes |
| valid_start_date | date | Yes |
| valid_end_date | date | Yes |
| invalid_reason | varchar(1) | No |

:  {.hover .responsive .sm}

### Columns Description

##### source_code

The source code being translated into a Standard Concept.

##### source_concept_id

A foreign key to the Source Concept that is being translated into a Standard Concept.

##### source_vocabulary_id

A foreign key to the VOCABULARY table defining the vocabulary of the source code that is being translated to a Standard Concept.

##### source_code_description

An optional description for the source code. This is included as a convenience to compare the description of the source code to the name of the concept.

##### target_concept_id

A foreign key to the target Concept to which the source code is being mapped.

##### target_vocabulary_id

A foreign key to the VOCABULARY table defining the vocabulary of the target Concept.

##### valid_start_date

The date when the mapping instance was first recorded.

##### valid_end_date

The date when the mapping instance became invalid because it was deleted or superseded (updated) by a new instance.

##### invalid_reason

Reason the mapping instance was invalidated. Possible values are D (deleted), U (replaced with an update) or NULL when valid_end_date has the default value.

