---
title: "specimen"
---


## Fields

| Field | Type | Required | Description |
|-------|------|----------|-------------|
| specimen_id | integer | Yes | A unique identifier for each specimen. |
| person_id | integer | Yes | A foreign key identifier to the Person for whom the Specimen is recorded. |
| specimen_concept_id | integer | Yes | A foreign key referring to a Standard Concept identifier in the Standardized Vocabularies for the Specimen. |
| specimen_type_concept_id | integer | Yes | A foreign key referring to the Concept identifier in the Standardized Vocabularies reflecting the system of record from which the Specimen was represented in the source data. |
| specimen_date | date | Yes | The date the specimen was obtained from the Person. |
| specimen_datetime | datetime | No | The date and time on the date when the Specimen was obtained from the person. |
| quantity | float | No | The amount of specimen collection from the person during the sampling procedure. |
| unit_concept_id | integer | No | A foreign key to a Standard Concept identifier of measurement units in the Standardized Vocabularies. |
| anatomic_site_concept_id | integer | No | A foreign key to a Standard Concept identifier for the anatomic location of specimen collection in the Standardized Vocabularies. |
| disease_status_concept_id | integer | No | A foreign key to a Standard Concept identifier for the Disease Status of specimen collection in the Standardized Vocabularies. |
| specimen_source_id | varchar(50) | No | The Specimen identifier as it appears in the source data. |
| specimen_source_value | varchar(50) | No | The Specimen value as it appears in the source data. The value is mapped to a Standard Concept in the Standardized Vocabularies and the original code is stored here for reference. |
| unit_source_value | varchar(50) | No | The information about the Unit as detailed in the source. |
| anatomic_site_source_value | varchar(50) | No | The information about the anatomic site as detailed in the source. |
| disease_status_source_value | varchar(50) | No | The information about the disease status as detailed in the source. |

