---
title: "vocabulary"
---

Vocabulary Tables

### Table Columns

| field                                               | type    | required   | phi   |   phi scrubbing operation |
|:----------------------------------------------------|:--------|:-----------|:------|--------------------------:|
| vocabulary_id                                       | STRING  | Yes        | No    |                        |
| vocabulary_name                                     | STRING  | Yes        | No    |                        |
| vocabulary_reference                                | STRING  | Yes        | No    |                        |
| vocabulary_version                                  | STRING  | No         | No    |                        |
| vocabulary_concept_id                               | INTEGER | Yes        | No    |                        |


:  {.hover .responsive .sm}

### Columns Description


##### vocabulary_id

A unique identifier for each Vocabulary, such as ICD9CM, SNOMED, Visit.

##### vocabulary_name

The name describing the vocabulary, for example "International Classification of Diseases, Ninth Revision, Clinical Modification, Volume 1 and 2 (NCHS)" etc.

##### vocabulary_reference

External reference to documentation or available download of the about the vocabulary.

##### vocabulary_version

Version of the Vocabulary as indicated in the source.

##### vocabulary_concept_id

A foreign key that refers to a standard concept identifier in the CONCEPT table for the Vocabulary the VOCABULARY record belongs to

