---
title: "cohort_definition"
---

## Overview

The COHORT_DEFINITION table contains records defining a Cohort derived from the data through the associated description and syntax and upon instantiation (execution of the algorithm) placed into the COHORT table. Cohorts are a set of subjects that satisfy a given combination of inclusion criteria for a duration of time. The COHORT_DEFINITION table provides a standardized structure for maintaining the rules governing the inclusion of a subject into a cohort, and can store operational programming code to instantiate the cohort within the OMOP Common Data Model.

## ETL Conventions

NA

## Table Columns

| Field | Type | Required |
|-------|------|----------|
| cohort_definition_id | integer | Yes |
| cohort_definition_name | varchar(255) | Yes |
| cohort_definition_description | varchar(MAX) | No |
| definition_type_concept_id | integer | Yes |
| cohort_definition_syntax | varchar(MAX) | No |
| subject_concept_id | integer | Yes |
| cohort_initiation_date | date | No |
{.hover .responsive .sm}

##### cohort_definition_id
This is the identifier given to the cohort, usually by the ATLAS application.

##### cohort_definition_name
A short description of the cohort.

##### cohort_definition_description
A complete description of the cohort.

##### definition_type_concept_id
Type defining what kind of Cohort Definition the record represents and how the syntax may be executed.

##### cohort_definition_syntax
Syntax or code to operationalize the Cohort Definition.

##### subject_concept_id
This field contains a Concept that represents the domain of the subjects that are members of the cohort (e.g., Person, Provider, Visit).

##### cohort_initiation_date
A date to indicate when the Cohort was initiated in the COHORT table.