---
title: "concept_synonym"
---

Vocabulary Tables

### Table Columns

| field                                               | type    | required   | phi   |   phi scrubbing operation |
|:----------------------------------------------------|:--------|:-----------|:------|--------------------------:|
| concept_id                                          | INTEGER | Yes        |       |                        |
| concept_synonym_name                                | STRING  | Yes        |       |                        |
| language_concept_id                                 | INTEGER | Yes        |       |                        |
| load_table_id (Stanford construct for traceability) | STRING  | No         |       |                        |
| load_row_id (Stanford construct for traceability)   | STRING  | No         |       |                        |

:  {.hover .responsive .sm}

### Columns Description


##### concept_id

A foreign key to the Concept in the CONCEPT table.

##### concept_synonym_name

The alternative name for the Concept.

##### language_concept_id

A foreign key to a Concept representing the language.

##### load_table_id (stanford construct for traceability)

A json string with the primary keys of the table in Clarity where most of the information for a given row is sourced

##### load_row_id (stanford construct for traceability)

A reference to the position in the ETL code responsible for bringing in this row level data
