---
title: "condition_era"
---

Standardized Derived Elements

### Table Columns

| field                                               | type     | required   | phi   | phi scrubbing operation   |
|:----------------------------------------------------|:---------|:-----------|:------|:--------------------------|
| condition_era_id                                    | INTEGER  | Yes        |  Yes     | Sub Not Stable between Data Refreshes                    |
| person_id                                           | INTEGER  | Yes        |    Yes   | Sub with Stable between Data Refreshes                       |
| condition_concept_id                                | INTEGER  | Yes        |       |                        |
| condition_era_start_date                            | DATETIME | Yes        | Yes   | Jitter                    |
| condition_era_end_date                              | DATETIME | Yes        | Yes   | Jitter                    |
| condition_occurrence_count                          | INTEGER  | No         |       |                        |
| trace_id (Stanford construct for traceability)      | STRING   | No         | Yes   |                        |
| unit_id (Stanford construct for traceability)       | STRING   | No         |       |                        |
| load_table_id (Stanford construct for traceability) | STRING   | No         |       |                        |

:  {.hover .responsive .sm}

### Columns Description


##### condition_era_id

A unique identifier for each Condition Era.

##### person_id

A foreign key identifier to the Person who is experiencing the Condition during the Condition Era. The demographic details of that Person are stored in the PERSON table.

##### condition_concept_id

A foreign key that refers to a standard Condition Concept identifier in the Standardized Vocabularies.

##### condition_era_start_date

The start date for the Condition Era constructed from the individual instances of Condition Occurrences. It is the start date of the very first chronologically recorded instance of the condition.

##### condition_era_end_date

The end date for the Condition Era constructed from the individual instances of Condition Occurrences. It is the end date of the final continuously recorded instance of the Condition.

##### condition_occurrence_count

The number of individual Condition Occurrences used to construct the condition era.

##### trace_id (stanford construct for traceability) 

A json string with the primary keys of the table in Clarity where most of the information for a given row is sourced

##### unit_id (stanford construct for traceability) 

Is a reference for the position in the ETL code responsible for bringing in this row level data

##### load_table_id (stanford construct for traceability) 

Is the name of the primary Clarity table in Clarity where most of the information for a given row is sourced
