---
title: "drug_era"
---

Standardized Derived Elements

### Table Columns

| field                                               | type     | required   | phi   | phi scrubbing operation   |
|:----------------------------------------------------|:---------|:-----------|:------|:--------------------------|
| drug_era_id                                         | INTEGER  | Yes        |  Yes     | Sub Not Stable between Data Refreshes                    |
| person_id                                           | INTEGER  | Yes        | Yes   | Sub with Stable between Data Refreshes                       |
| drug_concept_id                                     | INTEGER  | Yes        |       |                        |
| drug_era_start_date                                 | DATETIME | Yes        | Yes   | Jitter                    |
| drug_era_end_date                                   | DATETIME | Yes        | Yes   | Jitter                    |
| drug_exposure_count                                 | INTEGER  | No         |       |                        |
| gap_days                                            | INTEGER  | No         |       |                        |
| trace_id (Stanford construct for traceability)      | STRING   | No         | Yes   | Del                       |
| unit_id (Stanford construct for traceability)       | STRING   | No         |       |                        |
| load_table_id (Stanford construct for traceability) | STRING   | No         |       |                        |

:  {.hover .responsive .sm}

### Columns Description


##### drug_era_id

A unique identifier for each Drug Era.

##### person_id

A foreign key identifier to the Person who is subjected to the drug during the Drug Era. The demographic details of that Person are stored in the PERSON table.

##### drug_concept_id

A foreign key that refers to a Standard Concept identifier in the Standardized Vocabularies for the Ingredient Concept.

##### drug_era_start_date

The start date for the Drug Era constructed from the individual instances of Drug Exposures. It is the start date of the very first chronologically recorded instance of conutilization of a Drug.

##### drug_era_end_date

The end date for the drug era constructed from the individual instance of drug exposures. It is the end date of the final continuously recorded instance of utilization of a drug.

##### drug_exposure_count

The number of individual Drug Exposure occurrences used to construct the Drug Era.

##### gap_days

The number of days that are not covered by drug_exposure records that were used to make up the era record.

##### trace_id (stanford construct for traceability) 

A json string with the primary keys of the table in Clarity where most of the information for a given row is sourced

##### unit_id (stanford construct for traceability) 

Is a reference for the position in the ETL code responsible for bringing in this row data

##### load_table_id (stanford construct for traceability) 

Is the name of the primary Clarity table in Clarity where most of the information for a given row is sourced
