---
title: "note"
---

Standard Clinical Data Table

### Table Columns

| field                                               | type     | required   | phi   | phi scrubbing operation   |
|:----------------------------------------------------|:---------|:-----------|:------|:--------------------------|
| note_id                                             | INTEGER  | Yes        |       | Sub with Stable between Data Refreshes                    |
| person_id                                           | INTEGER  | Yes        |       | Sub with Stable between Data Refreshes                       |
| note_date                                           | DATE     | No         | Yes   | Jitter                      
| note_datetime                                       | DATETIME | Yes        | Yes   | Jitter                      |
| note_type_concept_id                                | INTEGER  | Yes        |       |                        |
| note_class_concept_id                               | INTEGER  | Yes        |       |                        |
| note_title                                          | STRING   | No         | Yes   |                        |
| note_text                                           | STRING   | Yes        | Yes   | TiDE                      |
| encoding_concept_id                                 | INTEGER  | Yes        |       |                        |
| language_concept_id                                 | INTEGER  | Yes        |       |                        |
| provider_id                                         | INTEGER  | No         |       | Sub with Stable between Data Refreshes                    |
| visit_occurrence_id                                 | INTEGER  | No         |       | Sub with Stable between Data Refreshes                    |
| visit_detail_id                                     | INTEGER  | No         |       | Sub with Stable between Data Refreshes                    |
| note_source_value                                   | STRING   | No         |       | Not Stable between Data Refreshes                    |
| load_table_id (Stanford construct for traceability) | STRING   | No         |       |                        |
| unit_id (Stanford construct for traceability)       | STRING   | No         |       |                        |

:  {.hover .responsive .sm}

### Columns Description


##### note_id

A unique identifier for each note.

##### person_id

A foreign key identifier to the Person about whom the Note was recorded. The demographic details of that Person are stored in the PERSON table.

##### note_date

The date the note was recorded.

##### note_datetime

The date and time the note was recorded.

##### note_type_concept_id

Concept id that describes the provenance of the note. 

##### note_class_concept_id

A foreign key to the predefined Concept in the Standardized Vocabularies reflecting the HL7 LOINC Document Type Vocabulary classification of the note.

##### note_title

In our OMOP this column ususally refers the note type. (Procedure note type, h&p etc)

##### note_text

The content of the Note.

##### encoding_concept_id

A foreign key to the predefined Concept in the Standardized Vocabularies reflecting the note character encoding type

##### language_concept_id

A foreign key to the predefined Concept in the Standardized Vocabularies reflecting the language of the note

##### provider_id

A foreign key to the Provider in the PROVIDER table who took the Note.

##### visit_occurrence_id

A foreign key to the Visit in the VISIT_OCCURRENCE table when the Note was taken.

##### visit_detail_id

A foreign key to the Visit in the VISIT_DETAIL table when the Note was taken.

##### note_source_value

The source value associated with the origin of the Note - In this case it often the clarity note_id (from hno_note)

##### load_table_id (stanford construct for traceability) 

A json string with the primary keys of the table in Clarity where most of the information for a given row is sourced

##### unit_id (stanford construct for traceability) 

Is a reference for the position in the ETL code responsible for bringing in this row level data
