---
title: "payer_plan_period"
---

Standardized Health Economics data Table, currently empty

### Table Columns

| field                                               | type    | required   | phi   | phi scrubbing operation   |
|:----------------------------------------------------|:--------|:-----------|:------|:--------------------------|
| payer_plan_period_id                                | INTEGER | Yes        |       | Not Stable between Data Refreshes                    |
| person_id                                           | INTEGER | Yes        |       | Sub with Stable between Data Refreshes                       |
| payer_plan_period_start_date                        | DATE    | Yes        | Yes   | Jitt                      |
| payer_plan_period_end_date                          | DATE    | Yes        | Yes   | Jitt                      |
| payer_concept_id                                    | INTEGER | Yes        |       |                        |
| payer_source_value                                  | STRING  | No         | Yes   |                        |
| payer_source_concept_id                             | INTEGER | Yes        |       |                        |
| plan_concept_id                                     | INTEGER | Yes        |       |                        |
| plan_source_value                                   | STRING  | No         | Yes   | Del                       |
| plan_source_concept_id                              | INTEGER | Yes        |       |                        |
| sponsor_concept_id                                  | INTEGER | Yes        |       |                        |
| sponsor_source_value                                | STRING  | No         |       |                        |
| sponsor_source_concept_id                           | INTEGER | Yes        |       |                        |
| family_source_value                                 | STRING  | No         | Yes   |                        |
| stop_reason_concept_id                              | INTEGER | Yes        |       |                        |
| stop_reason_source_value                            | STRING  | No         | Yes   |                        |
| stop_reason_source_concept_id                       | INTEGER | Yes        |       |                        |
| trace_id (Stanford construct for traceability)      | STRING  | No         | Yes   | Del                       |
| load_table_id (Stanford construct for traceability) | STRING  | No         | Yes   | Del                       |

:  {.hover .responsive .sm}

### Columns Description


##### payer_plan_period_id

A unique identifier for each unique combination of a Person, Payer, Plan, and Period of time.

##### person_id

The Person covered by the Plan. The demographic details of that Person are stored in the PERSON table.

##### payer_plan_period_start_date

The start date of the payer plan period.

##### payer_plan_period_end_date

The end date of the payer plan period.

##### payer_concept_id

This field represents the organization who reimburses the provider which administers care to the Person. This field refers to a standard Payer concept identifier in the Standarized Vocabularies.

##### payer_source_value

The source code for the payer as it appears in the source data. Currently it is "payer_ SOPT Desc | SOPT ID | Epic Payer Name| Epic Payor ID | Epic Financial Class Name | Epic Financial Class ID". SOPT is the payer type standard that provides a mechanism for consistent reporting of payer data to public health agencies for health care services and research

##### payer_source_concept_id

A foreign key to a payer concept that refers to the code used in the source. It is the OMOP concept id corresponding to the source code.

##### plan_concept_id

A foreign key that refers to a standard plan concept identifier that represents the health benefit plan in the Standardized Vocabularies.

##### plan_source_value

The source code for the Person's health benefit plan as it appears in the source data. Currently it is "Epic Plan Name| Epic Plan ID ".

##### plan_source_concept_id

A foreign key to a plan concept that refers to the plan code used in the source data.

##### sponsor_concept_id

A foreign key that refers to a concept identifier that represents the sponsor in the Standardized Vocabularies.

##### sponsor_source_value

The source code for the Person's sponsor of the health plan as it appears in the source data.

##### sponsor_source_concept_id

A foreign key to a sponsor concept that refers to the sponsor code used in the source data.

##### family_source_value

The source code for the Person's family as it appears in the source data.

##### stop_reason_concept_id

A foreign key that refers to a standard termination reason that represents the reason for the termination in the Standardized Vocabularies.

##### stop_reason_source_value

The reason for stop-coverage as it appears in the source data.

##### stop_reason_source_concept_id

A foreign key to a stop-coverage concept that refers to the code used in the source

##### trace_id (stanford construct for traceability) 

Is a reference for the position in the ETL code resposible for bringing in this row data

##### load_table_id (stanford construct for traceability) 

Is the name of the primary Clarity table in Clarity where most of the information for a given row is sourced
