---
title: "provider"
---

Standarized Health System Data Tables

### Table Columns

| field                                               | type    | required   | phi   | phi scrubbing operation   |
|:----------------------------------------------------|:--------|:-----------|:------|:--------------------------|
| provider_id                                         | INTEGER | Yes        | Yes    | Sub with Stable between Data Refreshes                    |
| provider_name                                       | STRING  | No         | No    |                        |
| npi                                                 | STRING  | No         | No    |                        |
| dea                                                 | STRING  | No         | No    | Del                       |
| specialty_concept_id                                | STRING  | Yes        | No    |                        |
| care_site_id                                        | INTEGER | No         | Yes  | Sub with Stable between Data Refreshes                    |
| year_of_birth                                       | INTEGER | No         | No    |                        |
| gender_concept_id                                   | INTEGER | Yes        | No    |                        |
| provider_source_value                               | STRING  | No         | Yes   |                        |
| specialty_source_value                              | STRING  | No         | No    |                        |
| specialty_source_concept_id                         | INTEGER | Yes        | No    |                        |
| gender_source_value                                 | STRING  | No         | No    |                        |
| gender_source_concept_id                            | INTEGER | Yes        | No    |                        |
| trace_id (Stanford construct for traceability)      | STRING  | No         | No    | Del                       |
| unit_id (Stanford construct for traceability)       | STRING  | No         | No    |                        |
| load_table_id (Stanford construct for traceability) | STRING  | No         | No    |                        |

:  {.hover .responsive .sm}

### Columns Description


##### provider_id

A unique identifier for each Provider.

##### provider_name

A description of the Healthcare Provider.

##### npi

The National Provider Identifier (NPI) of the providers in the US by the Centers for Medicare and Medicaid Services (CMS).

##### dea

This is the identifier issued by the DEA, a US federal agency, that allows a provider to write prescriptions for controlled substances.

##### specialty_concept_id

This is the CARE_SITE_ID for the location that the provider primarily practices in.

##### care_site_id

This field either represents the most common specialty that occurs in the data or the most specific concept that represents all specialties listed, should the provider have more than one.

##### year_of_birth

The year of birth of the Provider.

##### gender_concept_id

The gender of the Provider.

##### provider_source_value

The identifier used for the Provider in the source data, stored here for reference.

##### specialty_source_value

The source code for the Provider specialty as it appears in the source data, stored here for reference.

##### specialty_source_concept_id

A foreign key to a Concept that refers to the code used in the source.

##### gender_source_value

The gender code for the Provider as it appears in the source data, stored here for reference.

##### gender_source_concept_id

A foreign key to a Concept that refers to the code used in the source for storing the providers gender

##### trace_id (stanford construct for traceability) 

A json string with the primary keys of the table in Clarity where most of the information for a given row is sourced

##### unit_id (stanford construct for traceability) 

Is a reference for the position in the ETL code resposible for bringing in this row data

##### load_table_id (stanford construct for traceability) 

Is the name of the primary Clarity table in Clarity where most of the information for a given row is sourced
