---
title: "concept_relationship"
---

Vocabulary Tables

### Table Columns

| field            | type    | required   | phi   |   phi scrubbing operation |
|:-----------------|:--------|:-----------|:------|--------------------------:|
| concept_id_1     | INTEGER | Yes        |       |                        |
| concept_id_2     | INTEGER | Yes        |       |                        |
| relationship_id  | STRING  | Yes        |       |                        |
| valid_start_date | DATE    | Yes        |       |                        |
| valid_end_date   | DATE    | Yes        |       |                        |
| invalid_reason   | STRING  | No         |       |                        |
| load_table_id    | STRING  | No         |       |                        |
| load_row_id      | STRING  | No         |       |                        |

:  {.hover .responsive .sm}

### Columns Description


##### concept_id_1

A foreign key to a Concept in the CONCEPT table associated with the relationship. Relationships are directional, and this field represents the source concept designation.

##### concept_id_2

A foreign key to a Concept in the CONCEPT table associated with the relationship. Relationships are directional, and this field represents the destination concept designation.

##### relationship_id

A unique identifier to the type or nature of the Relationship as defined in the RELATIONSHIP table.

##### valid_start_date

The date when the instance of the Concept Relationship is first recorded.

##### valid_end_date

The date when the Concept Relationship became invalid because it was deleted or superseded (updated) by a new relationship. Default value is 31-Dec-2099.

##### invalid_reason

Reason the relationship was invalidated. Possible values are 'D' (deleted), 'U' (replaced with an update) or NULL when valid_end_date has the default value.

##### load_table_id

A json string with the primary keys of the table in Clarity where most of the information for a given row is sourced

##### load_row_id

A reference to the position in the ETL code responsible for bringing in this row level data
