---
title: "NeuralFrame Case Diagnoses"
---

This section contains details about the diagnoses made for each patient, including cancer types, staging, and any relevant comorbidities.

| Column Name                                        | Type   | Description                                        | NAACCR Number                                                                                                 |
|:---------------------------------------------------|:-------|:---------------------------------------------------|:--------------------------------------------------------------------------------------------------------------|
| cleaned_nf_mrn                                     | STRING |                                                    |                                                                                                               |
| cleaned_nf_dob                                     | DATE   |                                                    |                                                                                                               |
| medicalrecordnumber                                | STRING | Medical Record Number                              | [2300](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=2300/)   |
| dateofbirth                                        | STRING | Date of Birth                                      | [240](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=240/)     |
| dateofdiagnosis                                    | STRING | Date of Diagnosis                                  | [390](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=390/)     |
| nfpatientsetid                                     | STRING |                                                    |                                                                                                               |
| nfcaseentityid                                     | STRING |                                                    |                                                                                                               |
| nffacilityid                                       | STRING | NF Facility ID                                     | [50078](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=50078/) |
| nffacilityiddescription                            | STRING |                                                    |                                                                                                               |
| nfcasestatus                                       | STRING |                                                    |                                                                                                               |
| dateofmulttumors                                   | STRING | Date of Mult Tumors                                | [445](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=445/)     |
| accessionnumberhosp                                | STRING | Accession Number--Hosp                             | [550](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=550/)     |
| yearfirstseen                                      | STRING | Year First Seen                                    | [620](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=620/)     |
| yearfirstseendescription                           | STRING |                                                    |                                                                                                               |
| diagnosticconfirmation                             | STRING | Diagnostic Confirmation                            | [490](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=490/)     |
| diagnosticconfirmationdescription                  | STRING |                                                    |                                                                                                               |
| primarysite                                        | STRING | Primary Site                                       | [400](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=400/)     |
| primarysitedescription                             | STRING |                                                    |                                                                                                               |
| highriskcytogenetics                               | STRING | High Risk Cytogenetics                             | [3857](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3857/)   |
| highriskcytogeneticsdescription                    | STRING |                                                    |                                                                                                               |
| highriskhistologicfeatures                         | STRING | High Risk Histologic Features                      | [3858](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3858/)   |
| highriskhistologicfeaturesdescription              | STRING |                                                    |                                                                                                               |
| histologicsubtype                                  | STRING | Histologic Subtype                                 | [3960](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3960/)   |
| histologicsubtypedescription                       | STRING |                                                    |                                                                                                               |
| histologictypeicdo3                                | STRING | Histologic Type ICD-O-3                            | [522](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=522/)     |
| histologictypeicdo3description                     | STRING |                                                    |                                                                                                               |
| histologyicdo2                                     | STRING | Histology (92-00) ICD-O-2                          | [420](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=420/)     |
| histologyicdo2description                          | STRING |                                                    |                                                                                                               |
| laterality                                         | STRING | Laterality                                         | [410](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=410/)     |
| lateralitydescription                              | STRING |                                                    |                                                                                                               |
| ambiguousterminologydx                             | STRING | Ambiguous Terminology DX                           | [442](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=442/)     |
| ambiguousterminologydxdescription                  | STRING |                                                    |                                                                                                               |
| behaviorcodeicdo3                                  | STRING | Behavior Code ICD-O-3                              | [523](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=523/)     |
| behaviorcodeicdo3description                       | STRING |                                                    |                                                                                                               |
| behavioricdo2                                      | STRING | Behavior (92-00) ICD-O-2                           | [430](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=430/)     |
| behavioricdo2description                           | STRING |                                                    |                                                                                                               |
| casefindingsource                                  | STRING | Casefinding Source                                 | [501](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=501/)     |
| casefindingsourcedescription                       | STRING |                                                    |                                                                                                               |
| dateconclusivedx                                   | STRING | Date Conclusive DX                                 | [443](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=443/)     |
| dateconclusivedxflag                               | STRING | Date Conclusive DX Flag                            | [448](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=448/)     |
| dateconclusivedxflagdescription                    | STRING |                                                    |                                                                                                               |
| morphcodingsyscurrent                              | STRING | Morph Coding Sys--Current                          | [470](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=470/)     |
| morphcodingsyscurrentdescription                   | STRING |                                                    |                                                                                                               |
| morphcodingsysoriginl                              | STRING | Morph Coding Sys--Originl                          | [480](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=480/)     |
| morphcodingsysoriginldescription                   | STRING |                                                    |                                                                                                               |
| multtumrptasoneprim                                | STRING | Mult Tum Rpt as One Prim                           | [444](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=444/)     |
| multtumrptasoneprimdescription                     | STRING |                                                    |                                                                                                               |
| multiplicitycounter                                | STRING | Multiplicity Counter                               | [446](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=446/)     |
| multiplicitycounterdescription                     | STRING |                                                    |                                                                                                               |
| sitecodingsyscurrent                               | STRING | Site Coding Sys--Current                           | [450](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=450/)     |
| sitecodingsyscurrentdescription                    | STRING |                                                    |                                                                                                               |
| sitecodingsysoriginal                              | STRING | Site Coding Sys--Original                          | [460](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=460/)     |
| sitecodingsysoriginaldescription                   | STRING |                                                    |                                                                                                               |
| typeofreportingsource                              | STRING | Type of Reporting Source                           | [500](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=500/)     |
| typeofreportingsourcedescription                   | STRING |                                                    |                                                                                                               |
| ajccapiversioncurrent                              | STRING | AJCC API Version Current                           | [2156](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=2156/)   |
| ajccapiversionoriginal                             | STRING | AJCC API Version Original                          | [2157](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=2157/)   |
| ajcccancersurvapiversioncurrent                    | STRING | AJCC Cancer Surveillance DLL Version Current       | [2158](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=2158/)   |
| ajcccancersurvapiversionoriginal                   | STRING | AJCC Cancer Surveillance DLL Version Original      | [2159](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=2159/)   |
| ajccid                                             | STRING | AJCC ID                                            | [995](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=995/)     |
| ajcciddescription                                  | STRING |                                                    |                                                                                                               |
| ajcctnmclinm                                       | STRING | AJCC TNM Clin M                                    | [1003](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1003/)   |
| ajcctnmclinmdescription                            | STRING |                                                    |                                                                                                               |
| ajcctnmclinn                                       | STRING | AJCC TNM Clin N                                    | [1002](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1002/)   |
| ajcctnmclinndescription                            | STRING |                                                    |                                                                                                               |
| ajcctnmclinnsuffix                                 | STRING | AJCC TNM Clin N Suffix                             | [1034](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1034/)   |
| ajcctnmclinnsuffixdescription                      | STRING |                                                    |                                                                                                               |
| ajcctnmclinstagegroup                              | STRING | AJCC TNM Clin Stage Group                          | [1004](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1004/)   |
| ajcctnmclinstagegroupdescription                   | STRING |                                                    |                                                                                                               |
| ajcctnmclint                                       | STRING | AJCC TNM Clin T                                    | [1001](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1001/)   |
| ajcctnmclintdescription                            | STRING |                                                    |                                                                                                               |
| ajcctnmclintsuffix                                 | STRING | AJCC TNM Clin T Suffix                             | [1031](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1031/)   |
| ajcctnmclintsuffixdescription                      | STRING |                                                    |                                                                                                               |
| ajcctnmpathm                                       | STRING | AJCC TNM Path M                                    | [1013](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1013/)   |
| ajcctnmpathmdescription                            | STRING |                                                    |                                                                                                               |
| ajcctnmpathn                                       | STRING | AJCC TNM Path N                                    | [1012](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1012/)   |
| ajcctnmpathndescription                            | STRING |                                                    |                                                                                                               |
| ajcctnmpathnsuffix                                 | STRING | AJCC TNM Path N Suffix                             | [1035](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1035/)   |
| ajcctnmpathnsuffixdescription                      | STRING |                                                    |                                                                                                               |
| ajcctnmpathstagegroup                              | STRING | AJCC TNM Path Stage Group                          | [1014](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1014/)   |
| ajcctnmpathstagegroupdescription                   | STRING |                                                    |                                                                                                               |
| ajcctnmpatht                                       | STRING | AJCC TNM Path T                                    | [1011](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1011/)   |
| ajcctnmpathtdescription                            | STRING |                                                    |                                                                                                               |
| ajcctnmpathtsuffix                                 | STRING | AJCC TNM Path T Suffix                             | [1032](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1032/)   |
| ajcctnmpathtsuffixdescription                      | STRING |                                                    |                                                                                                               |
| ajcctnmposttherapyclinm                            | STRING | AJCC TNM Post Therapy Clin (yc) M                  | [1066](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1066/)   |
| ajcctnmposttherapyclinmdescription                 | STRING |                                                    |                                                                                                               |
| ajcctnmposttherapyclinn                            | STRING | AJCC TNM Post Therapy Clin (yc) N                  | [1064](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1064/)   |
| ajcctnmposttherapyclinndescription                 | STRING |                                                    |                                                                                                               |
| ajcctnmposttherapyclinnsuffix                      | STRING | AJCC TNM Post Therapy Clin (yc) N Suffix           | [1065](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1065/)   |
| ajcctnmposttherapyclinnsuffixdescription           | STRING |                                                    |                                                                                                               |
| ajcctnmposttherapyclint                            | STRING | AJCC TNM Post Therapy Clin (yc) T                  | [1062](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1062/)   |
| ajcctnmposttherapyclintdescription                 | STRING |                                                    |                                                                                                               |
| ajcctnmposttherapym                                | STRING | AJCC TNM Post Therapy Path (yp) M                  | [1023](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1023/)   |
| ajcctnmposttherapymdescription                     | STRING |                                                    |                                                                                                               |
| ajcctnmposttherapyn                                | STRING | AJCC TNM Post Therapy Path (yp) N                  | [1022](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1022/)   |
| ajcctnmposttherapyndescription                     | STRING |                                                    |                                                                                                               |
| ajcctnmposttherapynsuffix                          | STRING | AJCC TNM Post Therapy Path (yp) N Suffix           | [1036](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1036/)   |
| ajcctnmposttherapynsuffixdescription               | STRING |                                                    |                                                                                                               |
| ajcctnmposttherapystagegroup                       | STRING | AJCC TNM Post Therapy Path (yp) Stage Group        | [1024](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1024/)   |
| ajcctnmposttherapystagegroupdescription            | STRING |                                                    |                                                                                                               |
| ajcctnmposttherapyt                                | STRING | AJCC TNM Post Therapy Path (yp) T                  | [1021](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1021/)   |
| ajcctnmposttherapytdescription                     | STRING |                                                    |                                                                                                               |
| ajcctnmposttherapytsuffix                          | STRING | AJCC TNM Post Therapy Path (yp) T Suffix           | [1033](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1033/)   |
| ajcctnmposttherapytsuffixdescription               | STRING |                                                    |                                                                                                               |
| csmetsatdx                                         | STRING | CS Mets at DX                                      | [2850](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=2850/)   |
| csmetsatdxbone                                     | STRING | CS Mets at Dx-Bone                                 | [2851](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=2851/)   |
| csmetsatdxbonedescription                          | STRING |                                                    |                                                                                                               |
| csmetsatdxbrain                                    | STRING | CS Mets at Dx-Brain                                | [2852](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=2852/)   |
| csmetsatdxbraindescription                         | STRING |                                                    |                                                                                                               |
| csmetsatdxdescription                              | STRING |                                                    |                                                                                                               |
| csmetsatdxliver                                    | STRING | CS Mets at Dx-Liver                                | [2853](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=2853/)   |
| csmetsatdxliverdescription                         | STRING |                                                    |                                                                                                               |
| csmetsatdxlung                                     | STRING | CS Mets at Dx-Lung                                 | [2854](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=2854/)   |
| csmetsatdxlungdescription                          | STRING |                                                    |                                                                                                               |
| csmetseval                                         | STRING | CS Mets Eval                                       | [2860](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=2860/)   |
| csmetsevaldescription                              | STRING |                                                    |                                                                                                               |
| cssitespecificfactor1                              | STRING | CS Site-Specific Factor 1                          | [2880](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=2880/)   |
| cssitespecificfactor1description                   | STRING |                                                    |                                                                                                               |
| cssitespecificfactor2                              | STRING | CS Site-Specific Factor 2                          | [2890](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=2890/)   |
| cssitespecificfactor2description                   | STRING |                                                    |                                                                                                               |
| cssitespecificfactor3                              | STRING | CS Site-Specific Factor 3                          | [2900](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=2900/)   |
| cssitespecificfactor3description                   | STRING |                                                    |                                                                                                               |
| cssitespecificfactor4                              | STRING | CS Site-Specific Factor 4                          | [2910](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=2910/)   |
| cssitespecificfactor4description                   | STRING |                                                    |                                                                                                               |
| cssitespecificfactor5                              | STRING | CS Site-Specific Factor 5                          | [2920](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=2920/)   |
| cssitespecificfactor5description                   | STRING |                                                    |                                                                                                               |
| cssitespecificfactor6                              | STRING | CS Site-Specific Factor 6                          | [2930](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=2930/)   |
| cssitespecificfactor6description                   | STRING |                                                    |                                                                                                               |
| cssitespecificfactor7                              | STRING | CS Site-Specific Factor 7                          | [2861](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=2861/)   |
| cssitespecificfactor7description                   | STRING |                                                    |                                                                                                               |
| cssitespecificfactor8                              | STRING | CS Site-Specific Factor 8                          | [2862](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=2862/)   |
| cssitespecificfactor8description                   | STRING |                                                    |                                                                                                               |
| cssitespecificfactor9                              | STRING | CS Site-Specific Factor 9                          | [2863](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=2863/)   |
| cssitespecificfactor9description                   | STRING |                                                    |                                                                                                               |
| cssitespecificfactor10                             | STRING | CS Site-Specific Factor10                          | [2864](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=2864/)   |
| cssitespecificfactor10description                  | STRING |                                                    |                                                                                                               |
| cssitespecificfactor11                             | STRING | CS Site-Specific Factor11                          | [2865](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=2865/)   |
| cssitespecificfactor11description                  | STRING |                                                    |                                                                                                               |
| cssitespecificfactor12                             | STRING | CS Site-Specific Factor12                          | [2866](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=2866/)   |
| cssitespecificfactor12description                  | STRING |                                                    |                                                                                                               |
| cssitespecificfactor13                             | STRING | CS Site-Specific Factor13                          | [2867](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=2867/)   |
| cssitespecificfactor13description                  | STRING |                                                    |                                                                                                               |
| cssitespecificfactor14                             | STRING | CS Site-Specific Factor14                          | [2868](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=2868/)   |
| cssitespecificfactor14description                  | STRING |                                                    |                                                                                                               |
| cssitespecificfactor15                             | STRING | CS Site-Specific Factor15                          | [2869](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=2869/)   |
| cssitespecificfactor15description                  | STRING |                                                    |                                                                                                               |
| cssitespecificfactor16                             | STRING | CS Site-Specific Factor16                          | [2870](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=2870/)   |
| cssitespecificfactor16description                  | STRING |                                                    |                                                                                                               |
| cssitespecificfactor17                             | STRING | CS Site-Specific Factor17                          | [2871](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=2871/)   |
| cssitespecificfactor17description                  | STRING |                                                    |                                                                                                               |
| cssitespecificfactor18                             | STRING | CS Site-Specific Factor18                          | [2872](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=2872/)   |
| cssitespecificfactor18description                  | STRING |                                                    |                                                                                                               |
| cssitespecificfactor19                             | STRING | CS Site-Specific Factor19                          | [2873](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=2873/)   |
| cssitespecificfactor19description                  | STRING |                                                    |                                                                                                               |
| cssitespecificfactor20                             | STRING | CS Site-Specific Factor20                          | [2874](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=2874/)   |
| cssitespecificfactor20description                  | STRING |                                                    |                                                                                                               |
| cssitespecificfactor21                             | STRING | CS Site-Specific Factor21                          | [2875](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=2875/)   |
| cssitespecificfactor21description                  | STRING |                                                    |                                                                                                               |
| cssitespecificfactor22                             | STRING | CS Site-Specific Factor22                          | [2876](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=2876/)   |
| cssitespecificfactor22description                  | STRING |                                                    |                                                                                                               |
| cssitespecificfactor23                             | STRING | CS Site-Specific Factor23                          | [2877](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=2877/)   |
| cssitespecificfactor23description                  | STRING |                                                    |                                                                                                               |
| cssitespecificfactor24                             | STRING | CS Site-Specific Factor24                          | [2878](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=2878/)   |
| cssitespecificfactor24description                  | STRING |                                                    |                                                                                                               |
| cssitespecificfactor25                             | STRING | CS Site-Specific Factor25                          | [2879](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=2879/)   |
| cssitespecificfactor25description                  | STRING |                                                    |                                                                                                               |
| csversionderived                                   | STRING | CS Version Derived                                 | [2936](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=2936/)   |
| csversionderiveddescription                        | STRING |                                                    |                                                                                                               |
| derivedajcc6m                                      | STRING | Derived AJCC-6 M                                   | [2980](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=2980/)   |
| derivedajcc6mdescript                              | STRING | Derived AJCC-6 M Descript                          | [2990](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=2990/)   |
| derivedajcc6mdescriptdescription                   | STRING |                                                    |                                                                                                               |
| derivedajcc6mdescription                           | STRING |                                                    |                                                                                                               |
| derivedajcc6n                                      | STRING | Derived AJCC-6 N                                   | [2960](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=2960/)   |
| derivedajcc6ndescript                              | STRING | Derived AJCC-6 N Descript                          | [2970](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=2970/)   |
| derivedajcc6ndescriptdescription                   | STRING |                                                    |                                                                                                               |
| derivedajcc6ndescription                           | STRING |                                                    |                                                                                                               |
| derivedajcc6stagegrp                               | STRING | Derived AJCC-6 Stage Grp                           | [3000](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3000/)   |
| derivedajcc6stagegrpdescription                    | STRING |                                                    |                                                                                                               |
| derivedajcc6t                                      | STRING | Derived AJCC-6 T                                   | [2940](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=2940/)   |
| derivedajcc6tdescript                              | STRING | Derived AJCC-6 T Descript                          | [2950](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=2950/)   |
| derivedajcc6tdescriptdescription                   | STRING |                                                    |                                                                                                               |
| derivedajcc6tdescription                           | STRING |                                                    |                                                                                                               |
| derivedajcc7m                                      | STRING | Derived AJCC-7 M                                   | [3420](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3420/)   |
| derivedajcc7mdescript                              | STRING | Derived AJCC-7 M Descript                          | [3422](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3422/)   |
| derivedajcc7mdescriptdescription                   | STRING |                                                    |                                                                                                               |
| derivedajcc7mdescription                           | STRING |                                                    |                                                                                                               |
| derivedajcc7n                                      | STRING | Derived AJCC-7 N                                   | [3410](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3410/)   |
| derivedajcc7ndescript                              | STRING | Derived AJCC-7 N Descript                          | [3412](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3412/)   |
| derivedajcc7ndescriptdescription                   | STRING |                                                    |                                                                                                               |
| derivedajcc7ndescription                           | STRING |                                                    |                                                                                                               |
| derivedajcc7stagegrp                               | STRING | Derived AJCC-7 Stage Grp                           | [3430](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3430/)   |
| derivedajcc7stagegrpdescription                    | STRING |                                                    |                                                                                                               |
| derivedajcc7t                                      | STRING | Derived AJCC-7 T                                   | [3400](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3400/)   |
| derivedajcc7tdescript                              | STRING | Derived AJCC-7 T Descript                          | [3402](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3402/)   |
| derivedajcc7tdescriptdescription                   | STRING |                                                    |                                                                                                               |
| derivedajcc7tdescription                           | STRING |                                                    |                                                                                                               |
| derivedajccflag                                    | STRING | Derived AJCC--Flag                                 | [3030](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3030/)   |
| derivedajccflagdescription                         | STRING |                                                    |                                                                                                               |
| derivedeod2018m                                    | STRING | Derived EOD 2018 M                                 | [795](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=795/)     |
| derivedeod2018mdescription                         | STRING |                                                    |                                                                                                               |
| derivedeod2018n                                    | STRING | Derived EOD 2018 N                                 | [815](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=815/)     |
| derivedeod2018ndescription                         | STRING |                                                    |                                                                                                               |
| derivedeod2018stagegroup                           | STRING | Derived EOD 2018 Stage Group                       | [818](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=818/)     |
| derivedeod2018t                                    | STRING | Derived EOD 2018 T                                 | [785](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=785/)     |
| derivedeod2018tdescription                         | STRING |                                                    |                                                                                                               |
| derivedeodversion                                  | STRING |                                                    |                                                                                                               |
| derivedraistage                                    | STRING | Derived Rai Stage                                  | [3955](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3955/)   |
| derivedraistagedescription                         | STRING |                                                    |                                                                                                               |
| derivedss1977                                      | STRING | Derived SS1977                                     | [3010](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3010/)   |
| derivedss1977description                           | STRING |                                                    |                                                                                                               |
| derivedss1977flag                                  | STRING | Derived SS1977--Flag                               | [3040](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3040/)   |
| derivedss1977flagdescription                       | STRING |                                                    |                                                                                                               |
| derivedss2000                                      | STRING | Derived SS2000                                     | [3020](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3020/)   |
| derivedss2000description                           | STRING |                                                    |                                                                                                               |
| derivedss2000flag                                  | STRING | Derived SS2000--Flag                               | [3050](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3050/)   |
| derivedss2000flagdescription                       | STRING |                                                    |                                                                                                               |
| derivedsummarygrade2018                            | STRING |                                                    |                                                                                                               |
| derivedsummarystage2018                            | STRING | Derived Summary Stage 2018                         | [762](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=762/)     |
| derivedsummarystage2018description                 | STRING |                                                    |                                                                                                               |
| eodmets                                            | STRING | EOD Mets                                           | [776](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=776/)     |
| eodmetsdescription                                 | STRING |                                                    |                                                                                                               |
| eodregionalnodes                                   | STRING | EOD Regional Nodes                                 | [774](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=774/)     |
| eodregionalnodesdescription                        | STRING |                                                    |                                                                                                               |
| figostage                                          | STRING | FIGO Stage                                         | [3836](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3836/)   |
| figostagedescription                               | STRING |                                                    |                                                                                                               |
| grade                                              | STRING | Grade                                              | [440](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=440/)     |
| gradeclinical                                      | STRING | Grade Clinical                                     | [3843](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3843/)   |
| gradeclinicaldescription                           | STRING |                                                    |                                                                                                               |
| gradedescription                                   | STRING |                                                    |                                                                                                               |
| gradepathsystem                                    | STRING | Grade Path System                                  | [449](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=449/)     |
| gradepathsystemdescription                         | STRING |                                                    |                                                                                                               |
| gradepathvalue                                     | STRING | Grade Path Value                                   | [441](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=441/)     |
| gradepathvaluedescription                          | STRING |                                                    |                                                                                                               |
| gradepathological                                  | STRING | Grade Pathological                                 | [3844](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3844/)   |
| gradepathologicaldescription                       | STRING |                                                    |                                                                                                               |
| gradeposttherapy                                   | STRING | Grade Post Therapy Path (yp)                       | [3845](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3845/)   |
| gradeposttherapyclin                               | STRING | Grade Post Therapy Clin (yc)                       | [1068](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1068/)   |
| gradeposttherapyclindescription                    | STRING |                                                    |                                                                                                               |
| gradeposttherapydescription                        | STRING |                                                    |                                                                                                               |
| metsatdxbone                                       | STRING | Mets at DX-Bone                                    | [1112](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1112/)   |
| metsatdxbonedescription                            | STRING |                                                    |                                                                                                               |
| metsatdxbrain                                      | STRING | Mets at DX-Brain                                   | [1113](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1113/)   |
| metsatdxbraindescription                           | STRING |                                                    |                                                                                                               |
| metsatdxdistantln                                  | STRING | Mets at Dx-Distant LN                              | [1114](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1114/)   |
| metsatdxdistantlndescription                       | STRING |                                                    |                                                                                                               |
| metsatdxliver                                      | STRING | Mets at DX-Liver                                   | [1115](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1115/)   |
| metsatdxliverdescription                           | STRING |                                                    |                                                                                                               |
| metsatdxlung                                       | STRING | Mets at DX-Lung                                    | [1116](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1116/)   |
| metsatdxlungdescription                            | STRING |                                                    |                                                                                                               |
| metsatdxother                                      | STRING | Mets at DX-Other                                   | [1117](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1117/)   |
| metsatdxotherdescription                           | STRING |                                                    |                                                                                                               |
| npcrderivedajcc8tnmclinstggrp                      | STRING | NPCR Derived AJCC 8 TNM Clin Stg Grp               | [3645](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3645/)   |
| npcrderivedajcc8tnmclinstggrpdescription           | STRING |                                                    |                                                                                                               |
| npcrderivedajcc8tnmpathstggrp                      | STRING | NPCR Derived AJCC 8 TNM Path Stg Grp               | [3646](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3646/)   |
| npcrderivedajcc8tnmpathstggrpdescription           | STRING |                                                    |                                                                                                               |
| npcrderivedajcc8tnmpoststggrp                      | STRING | NPCR Derived AJCC 8 TNM Post Therapy Stg Grp       | [3647](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3647/)   |
| npcrderivedajcc8tnmpoststggrpdescription           | STRING |                                                    |                                                                                                               |
| overridesitetnmstggrp                              | STRING | Over-ride Site/TNM-StgGrp                          | [1989](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1989/)   |
| overridesitetnmstggrpdescription                   | STRING |                                                    |                                                                                                               |
| overridesstnmm                                     | STRING | Over-ride SS/TNM-M                                 | [1983](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1983/)   |
| overridesstnmmdescription                          | STRING |                                                    |                                                                                                               |
| overridesstnmn                                     | STRING | Over-ride SS/TNM-N                                 | [1982](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1982/)   |
| overridesstnmndescription                          | STRING |                                                    |                                                                                                               |
| overridetnm3                                       | STRING | Over-ride TNM 3                                    | [1994](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1994/)   |
| overridetnm3description                            | STRING |                                                    |                                                                                                               |
| overridetnmstage                                   | STRING | Over-ride TNM Stage                                | [1992](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1992/)   |
| overridetnmstagedescription                        | STRING |                                                    |                                                                                                               |
| overridetnmtis                                     | STRING | Over-ride TNM Tis                                  | [1993](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1993/)   |
| overridetnmtisdescription                          | STRING |                                                    |                                                                                                               |
| pediatricstage                                     | STRING | Pediatric Stage                                    | [1120](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1120/)   |
| pediatricstagedescription                          | STRING |                                                    |                                                                                                               |
| pediatricstagedby                                  | STRING | Pediatric Staged By                                | [1140](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1140/)   |
| pediatricstagedbydescription                       | STRING |                                                    |                                                                                                               |
| rxdatedxstgproc                                    | STRING | RX Date DX/Stg Proc                                | [1280](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1280/)   |
| rxdatedxstgprocflag                                | STRING | Rx Date Dx/Stg Proc Flag                           | [1281](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1281/)   |
| rxdatedxstgprocflagdescription                     | STRING |                                                    |                                                                                                               |
| rxhospdxstgproc                                    | STRING | RX Hosp--DX/Stg Proc                               | [740](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=740/)     |
| rxhospdxstgprocdescription                         | STRING |                                                    |                                                                                                               |
| rxsummdxstgproc                                    | STRING | RX Summ--DX/Stg Proc                               | [1350](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1350/)   |
| rxsummdxstgprocdescription                         | STRING |                                                    |                                                                                                               |
| seersummarystage1977                               | STRING | SEER Summary Stage 1977                            | [760](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=760/)     |
| seersummarystage1977description                    | STRING |                                                    |                                                                                                               |
| seersummarystage2000                               | STRING | SEER Summary Stage 2000                            | [759](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=759/)     |
| seersummarystage2000description                    | STRING |                                                    |                                                                                                               |
| stagealternate                                     | STRING | Stage Alternate                                    | [70049](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=70049/) |
| summarystage2018                                   | STRING | Summary Stage 2018                                 | [764](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=764/)     |
| summarystage2018description                        | STRING |                                                    |                                                                                                               |
| tnmclindescriptor                                  | STRING | TNM Clin Descriptor                                | [980](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=980/)     |
| tnmclindescriptordescription                       | STRING |                                                    |                                                                                                               |
| tnmclinm                                           | STRING | TNM Clin M                                         | [960](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=960/)     |
| tnmclinmdescription                                | STRING |                                                    |                                                                                                               |
| tnmclinn                                           | STRING | TNM Clin N                                         | [950](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=950/)     |
| tnmclinndescription                                | STRING |                                                    |                                                                                                               |
| tnmclinsource                                      | STRING | TNM Clin Source                                    | [23006](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=23006/) |
| tnmclinsourcedescription                           | STRING |                                                    |                                                                                                               |
| tnmclinstagegroup                                  | STRING | TNM Clin Stage Group                               | [970](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=970/)     |
| tnmclinstagegroupdescription                       | STRING |                                                    |                                                                                                               |
| tnmclinstagedby                                    | STRING | TNM Clin Staged By                                 | [990](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=990/)     |
| tnmclinstagedbydescription                         | STRING |                                                    |                                                                                                               |
| tnmclint                                           | STRING | TNM Clin T                                         | [940](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=940/)     |
| tnmclintdescription                                | STRING |                                                    |                                                                                                               |
| tnmeditionnumber                                   | STRING | TNM Edition Number                                 | [1060](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1060/)   |
| tnmeditionnumberdescription                        | STRING |                                                    |                                                                                                               |
| tnmpathdescriptor                                  | STRING | TNM Path Descriptor                                | [920](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=920/)     |
| tnmpathdescriptordescription                       | STRING |                                                    |                                                                                                               |
| tnmpathm                                           | STRING | TNM Path M                                         | [900](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=900/)     |
| tnmpathmdescription                                | STRING |                                                    |                                                                                                               |
| tnmpathn                                           | STRING | TNM Path N                                         | [890](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=890/)     |
| tnmpathndescription                                | STRING |                                                    |                                                                                                               |
| tnmpathsource                                      | STRING | TNM Path Source                                    | [23005](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=23005/) |
| tnmpathsourcedescription                           | STRING |                                                    |                                                                                                               |
| tnmpathstagegroup                                  | STRING | TNM Path Stage Group                               | [910](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=910/)     |
| tnmpathstagegroupdescription                       | STRING |                                                    |                                                                                                               |
| tnmpathstagedby                                    | STRING | TNM Path Staged By                                 | [930](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=930/)     |
| tnmpathstagedbydescription                         | STRING |                                                    |                                                                                                               |
| tnmpatht                                           | STRING | TNM Path T                                         | [880](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=880/)     |
| tnmpathtdescription                                | STRING |                                                    |                                                                                                               |
| discoveredbyscreening                              | STRING | Discovered by Screening                            | [70008](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=70008/) |
| discoveredbyscreeningdescription                   | STRING |                                                    |                                                                                                               |
| egfrmutationalanalysis                             | STRING | EGFR Mutational Analysis                           | [3939](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3939/)   |
| egfrmutationalanalysisdescription                  | STRING |                                                    |                                                                                                               |
| eodextension                                       | STRING | EOD--Extension                                     | [790](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=790/)     |
| eodextensiondescription                            | STRING |                                                    |                                                                                                               |
| eodextensionprostpath                              | STRING | EOD--Extension Prost Path                          | [800](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=800/)     |
| eodextensionprostpathdescription                   | STRING |                                                    |                                                                                                               |
| eodlymphnodeinvolv                                 | STRING | EOD--Lymph Node Involv                             | [810](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=810/)     |
| eodlymphnodeinvolvdescription                      | STRING |                                                    |                                                                                                               |
| esophagusandegjtumorepicenter                      | STRING | Esophagus and EGJ Tumor Epicenter                  | [3829](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3829/)   |
| esophagusandegjtumorepicenterdescription           | STRING |                                                    |                                                                                                               |
| estrogenreceptorpercntposorrange                   | STRING | Estrogen Receptor Percent Positive or Range        | [3826](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3826/)   |
| estrogenreceptorpercntposorrangedescription        | STRING |                                                    |                                                                                                               |
| estrogenreceptorsummary                            | STRING | Estrogen Receptor Summary                          | [3827](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3827/)   |
| estrogenreceptorsummarydescription                 | STRING |                                                    |                                                                                                               |
| estrogenreceptortotalallredscore                   | STRING | Estrogen Receptor Total Allred Score               | [3828](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3828/)   |
| estrogenreceptortotalallredscoredescription        | STRING |                                                    |                                                                                                               |
| extranodalextensionclin                            | STRING | Extranodal Extension Clin (non-Head and Neck)      | [3830](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3830/)   |
| extranodalextensionclindescription                 | STRING |                                                    |                                                                                                               |
| extranodalextensionheadneckclin                    | STRING | Extranodal Extension Head and Neck Clinical        | [3831](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3831/)   |
| extranodalextensionheadneckclindescription         | STRING |                                                    |                                                                                                               |
| extranodalextensionheadneckpath                    | STRING | Extranodal Extension Head and Neck Pathological    | [3832](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3832/)   |
| extranodalextensionheadneckpathdescription         | STRING |                                                    |                                                                                                               |
| extranodalextensionpath                            | STRING | Extranodal Extension Path (non-Head and Neck)      | [3833](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3833/)   |
| extranodalextensionpathdescription                 | STRING |                                                    |                                                                                                               |
| extravascularmatrixpatterns                        | STRING | Extravascular Matrix Patterns                      | [3834](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3834/)   |
| extravascularmatrixpatternsdescription             | STRING |                                                    |                                                                                                               |
| fibrosisscore                                      | STRING | Fibrosis Score                                     | [3835](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3835/)   |
| fibrosisscoredescription                           | STRING |                                                    |                                                                                                               |
| followupflag                                       | STRING | Follow-up Flag                                     | [70009](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=70009/) |
| followupflagdescription                            | STRING |                                                    |                                                                                                               |
| followuplasttypetumor                              | STRING | Follow-Up Last Type Tumor                          | [70011](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=70011/) |
| followuplasttypetumordescription                   | STRING |                                                    |                                                                                                               |
| gestationaltrophoblasticpxindex                    | STRING | Gestational Trophoblastic Prognostic Scoring Index | [3837](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3837/)   |
| gleasonpatternsclinical                            | STRING | Gleason Patterns Clinical                          | [3838](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3838/)   |
| gleasonpatternsclinicaldescription                 | STRING |                                                    |                                                                                                               |
| gleasonpatternspathological                        | STRING | Gleason Patterns Pathological                      | [3839](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3839/)   |
| gleasonpatternspathologicaldescription             | STRING |                                                    |                                                                                                               |
| gleasonscoreclinical                               | STRING | Gleason Score Clinical                             | [3840](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3840/)   |
| gleasonscoreclinicaldescription                    | STRING |                                                    |                                                                                                               |
| gleasonscorepathological                           | STRING | Gleason Score Pathological                         | [3841](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3841/)   |
| gleasonscorepathologicaldescription                | STRING |                                                    |                                                                                                               |
| gleasontertiarypattern                             | STRING | Gleason Tertiary Pattern                           | [3842](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3842/)   |
| gleasontertiarypatterndescription                  | STRING |                                                    |                                                                                                               |
| her2ihcsummary                                     | STRING | HER2 IHC Summary                                   | [3850](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3850/)   |
| her2ihcsummarydescription                          | STRING |                                                    |                                                                                                               |
| her2ishdualprobecopynumber                         | STRING | HER2 ISH Dual Probe Copy Number                    | [3851](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3851/)   |
| her2ishdualprobecopynumberdescription              | STRING |                                                    |                                                                                                               |
| her2ishdualproberatio                              | STRING | HER2 ISH Dual Probe Ratio                          | [3852](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3852/)   |
| her2ishdualproberatiodescription                   | STRING |                                                    |                                                                                                               |
| her2ishsingleprobecopynumber                       | STRING | HER2 ISH Single Probe Copy Number                  | [3853](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3853/)   |
| her2ishsingleprobecopynumberdescription            | STRING |                                                    |                                                                                                               |
| her2ishsummary                                     | STRING | HER2 ISH Summary                                   | [3854](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3854/)   |
| her2ishsummarydescription                          | STRING |                                                    |                                                                                                               |
| her2overallsummary                                 | STRING | HER2 Overall Summary                               | [3855](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3855/)   |
| her2overallsummarydescription                      | STRING |                                                    |                                                                                                               |
| heritabletrait                                     | STRING | Heritable Trait                                    | [3856](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3856/)   |
| heritabletraitdescription                          | STRING |                                                    |                                                                                                               |
| hivstatus                                          | STRING | HIV Status                                         | [3859](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3859/)   |
| hivstatusdescription                               | STRING |                                                    |                                                                                                               |
| hospitaltumornumberccr                             | STRING | Hospital Tumor Number CCR                          | [70014](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=70014/) |
| hospitaltumornumberccrdescription                  | STRING |                                                    |                                                                                                               |
| lnassessmethodfemoralinguinal                      | STRING | LN Assessment Method Femoral-Inguinal              | [3871](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3871/)   |
| lnassessmethodfemoralinguinaldescription           | STRING |                                                    |                                                                                                               |
| lnassessmethodparaaortic                           | STRING | LN Assessment Method Para-Aortic                   | [3872](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3872/)   |
| lnassessmethodparaaorticdescription                | STRING |                                                    |                                                                                                               |
| lnassessmethodpelvic                               | STRING | LN Assessment Method Pelvic                        | [3873](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3873/)   |
| lnassessmethodpelvicdescription                    | STRING |                                                    |                                                                                                               |
| lndistantassessmethod                              | STRING | LN Distant Assessment Method                       | [3874](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3874/)   |
| lndistantassessmethoddescription                   | STRING |                                                    |                                                                                                               |
| lndistantmediastinalscalene                        | STRING | LN Distant: Mediastinal, Scalene                   | [3875](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3875/)   |
| lndistantmediastinalscalenedescription             | STRING |                                                    |                                                                                                               |
| lnheadandnecklevels1to3                            | STRING | LN Head and Neck Levels I-III                      | [3876](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3876/)   |
| lnheadandnecklevels1to3description                 | STRING |                                                    |                                                                                                               |
| lnheadandnecklevels4to5                            | STRING | LN Head and Neck Levels IV-V                       | [3877](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3877/)   |
| lnheadandnecklevels4to5description                 | STRING |                                                    |                                                                                                               |
| lnheadandnecklevels6to7                            | STRING | LN Head and Neck Levels VI-VII                     | [3878](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3878/)   |
| lnheadandnecklevels6to7description                 | STRING |                                                    |                                                                                                               |
| lnheadandneckother                                 | STRING | LN Head and Neck Other                             | [3879](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3879/)   |
| lnheadandneckotherdescription                      | STRING |                                                    |                                                                                                               |
| lnisolatedtumorcells                               | STRING | LN Isolated Tumor Cells (ITC)                      | [3880](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3880/)   |
| lnisolatedtumorcellsdescription                    | STRING |                                                    |                                                                                                               |
| lnlaterality                                       | STRING | LN Laterality                                      | [3881](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3881/)   |
| lnlateralitydescription                            | STRING |                                                    |                                                                                                               |
| lnpositiveaxillarylevel1to2                        | STRING | LN Positive Axillary Level I-II                    | [3882](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3882/)   |
| lnpositiveaxillarylevel1to2description             | STRING |                                                    |                                                                                                               |
| lnsize                                             | STRING | LN Size                                            | [3883](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3883/)   |
| lnsizedescription                                  | STRING |                                                    |                                                                                                               |
| lnstatusfemoringuinparaaortpelv                    | STRING | LN Status Femoral-Inguinal, Para-Aortic, Pelvic    | [3884](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3884/)   |
| lnstatusfemoringuinparaaortpelvdescription         | STRING |                                                    |                                                                                                               |
| lnstatusfemoralinguinal                            | STRING | LN Status Femoral-Inguinal                         | [3959](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3959/)   |
| lnstatusfemoralinguinaldescription                 | STRING |                                                    |                                                                                                               |
| lnstatusparaaortic                                 | STRING | LN Status Para-Aortic                              | [3958](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3958/)   |
| lnstatusparaaorticdescription                      | STRING |                                                    |                                                                                                               |
| lnstatuspelvic                                     | STRING | LN Status Pelvic                                   | [3957](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3957/)   |
| lnstatuspelvicdescription                          | STRING |                                                    |                                                                                                               |
| lymphvascularinvasion                              | STRING | Lymphovascular Invasion                            | [1182](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1182/)   |
| lymphvascularinvasiondescription                   | STRING |                                                    |                                                                                                               |
| lymphocytosis                                      | STRING | Lymphocytosis                                      | [3885](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3885/)   |
| lymphocytosisdescription                           | STRING |                                                    |                                                                                                               |
| macroscopicevalofthemesorectum                     | STRING | Macroscopic Evaluation of Mesorectum               | [3950](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3950/)   |
| macroscopicevalofthemesorectumdescription          | STRING |                                                    |                                                                                                               |
| majorveininvolvement                               | STRING | Major Vein Involvement                             | [3886](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3886/)   |
| majorveininvolvementdescription                    | STRING |                                                    |                                                                                                               |
| measuredbasaldiameter                              | STRING | Measured Basal Diameter                            | [3887](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3887/)   |
| measuredbasaldiameterdescription                   | STRING |                                                    |                                                                                                               |
| measuredthickness                                  | STRING | Measured Thickness                                 | [3888](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3888/)   |
| measuredthicknessdescription                       | STRING |                                                    |                                                                                                               |
| methylationofo6mgmt                                | STRING | Methylation of O6-Methylguanine-Methyltransferase  | [3889](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3889/)   |
| methylationofo6mgmtdescription                     | STRING |                                                    |                                                                                                               |
| microsatelliteinstability                          | STRING | Microsatellite Instability (MSI)                   | [3890](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3890/)   |
| microsatelliteinstabilitydescription               | STRING |                                                    |                                                                                                               |
| microvasculardensity                               | STRING | Microvascular Density                              | [3891](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3891/)   |
| microvasculardensitydescription                    | STRING |                                                    |                                                                                                               |
| csextension                                        | STRING | CS Extension                                       | [2810](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=2810/)   |
| csextensiondescription                             | STRING |                                                    |                                                                                                               |
| cslymphnodes                                       | STRING | CS Lymph Nodes                                     | [2830](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=2830/)   |
| cslymphnodesdescription                            | STRING |                                                    |                                                                                                               |
| cslymphnodeseval                                   | STRING | CS Lymph Nodes Eval                                | [2840](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=2840/)   |
| cslymphnodesevaldescription                        | STRING |                                                    |                                                                                                               |
| inrprothrombintime                                 | STRING | International Normalized Ratio Prothrombin Time    | [3860](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3860/)   |
| inrprothrombintimedescription                      | STRING |                                                    |                                                                                                               |
| mitoticcountuvealmelanoma                          | STRING | Mitotic Count Uveal Melanoma                       | [3892](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3892/)   |
| mitoticcountuvealmelanomadescription               | STRING |                                                    |                                                                                                               |
| mitoticratemelanoma                                | STRING | Mitotic Rate Melanoma                              | [3893](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3893/)   |
| mitoticratemelanomadescription                     | STRING |                                                    |                                                                                                               |
| multigenesignaturemethod                           | STRING | Multigene Signature Method                         | [3894](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3894/)   |
| multigenesignaturemethoddescription                | STRING |                                                    |                                                                                                               |
| multigenesignatureresults                          | STRING | Multigene Signature Results                        | [3895](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3895/)   |
| multigenesignatureresultsdescription               | STRING |                                                    |                                                                                                               |
| nccninternationalprognosticindex                   | STRING | NCCN International Prognostic Index (IPI)          | [3896](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3896/)   |
| nccninternationalprognosticindexdescription        | STRING |                                                    |                                                                                                               |
| nrasmutationalanalysis                             | STRING | NRAS Mutational Analysis                           | [3941](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3941/)   |
| nrasmutationalanalysisdescription                  | STRING |                                                    |                                                                                                               |
| numberofcoresexamined                              | STRING | Number of Cores Examined                           | [3897](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3897/)   |
| numberofcoresexamineddescription                   | STRING |                                                    |                                                                                                               |
| numberofcorespositive                              | STRING | Number of Cores Positive                           | [3898](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3898/)   |
| numberofcorespositivedescription                   | STRING |                                                    |                                                                                                               |
| numberofexaminedparaaorticnodes                    | STRING | Number of Examined Para-Aortic Nodes               | [3899](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3899/)   |
| numberofexaminedparaaorticnodesdescription         | STRING |                                                    |                                                                                                               |
| numberofexaminedpelvicnodes                        | STRING | Number of Examined Pelvic Nodes                    | [3900](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3900/)   |
| numberofexaminedpelvicnodesdescription             | STRING |                                                    |                                                                                                               |
| numberofpositiveparaaorticnodes                    | STRING | Number of Positive Para-Aortic Nodes               | [3901](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3901/)   |
| numberofpositiveparaaorticnodesdescription         | STRING |                                                    |                                                                                                               |
| numberofpositivepelvicnodes                        | STRING | Number of Positive Pelvic Nodes                    | [3902](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3902/)   |
| numberofpositivepelvicnodesdescription             | STRING |                                                    |                                                                                                               |
| oncotypedxrecurrencescoredcis                      | STRING | Oncotype Dx Recurrence Score-DCIS                  | [3903](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3903/)   |
| oncotypedxrecurrencescoredcisdescription           | STRING |                                                    |                                                                                                               |
| oncotypedxrecurrencescoreinvasiv                   | STRING | Oncotype Dx Recurrence Score-Invasive              | [3904](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3904/)   |
| oncotypedxrecurrencescoreinvasivdescription        | STRING |                                                    |                                                                                                               |
| oncotypedxriskleveldcis                            | STRING | Oncotype Dx Risk Level-DCIS                        | [3905](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3905/)   |
| oncotypedxriskleveldcisdescription                 | STRING |                                                    |                                                                                                               |
| oncotypedxrisklevelinvasive                        | STRING | Oncotype Dx Risk Level-Invasive                    | [3906](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3906/)   |
| oncotypedxrisklevelinvasivedescription             | STRING |                                                    |                                                                                                               |
| organomegaly                                       | STRING | Organomegaly                                       | [3907](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3907/)   |
| organomegalydescription                            | STRING |                                                    |                                                                                                               |
| p16                                                | STRING | p16                                                | [3956](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3956/)   |
| p16description                                     | STRING |                                                    |                                                                                                               |
| pediatricstagingsystem                             | STRING | Pediatric Staging System                           | [1130](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1130/)   |
| pediatricstagingsystemdescription                  | STRING |                                                    |                                                                                                               |
| percentnecrosispostneoadjuvant                     | STRING | Percent Necrosis Post Neoadjuvant                  | [3908](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3908/)   |
| percentnecrosispostneoadjuvantdescription          | STRING |                                                    |                                                                                                               |
| perineuralinvasion                                 | STRING | Perineural Invasion                                | [3909](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3909/)   |
| perineuralinvasiondescription                      | STRING |                                                    |                                                                                                               |
| peripheralbloodinvolvement                         | STRING | Peripheral Blood Involvement                       | [3910](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3910/)   |
| peripheralbloodinvolvementdescription              | STRING |                                                    |                                                                                                               |
| peritonealcytology                                 | STRING | Peritoneal Cytology                                | [3911](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3911/)   |
| peritonealcytologydescription                      | STRING |                                                    |                                                                                                               |
| pleuraleffusion                                    | STRING | Pleural Effusion                                   | [3913](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3913/)   |
| pleuraleffusiondescription                         | STRING |                                                    |                                                                                                               |
| primarysclerosingcholangitis                       | STRING | Primary Sclerosing Cholangitis                     | [3917](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3917/)   |
| primarysclerosingcholangitisdescription            | STRING |                                                    |                                                                                                               |
| profoundimmunesuppression                          | STRING | Profound Immune Suppression                        | [3918](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3918/)   |
| profoundimmunesuppressiondescription               | STRING |                                                    |                                                                                                               |
| regionalnodesexamined                              | STRING | Regional Nodes Examined                            | [830](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=830/)     |
| regionalnodesexamineddescription                   | STRING |                                                    |                                                                                                               |
| regionalnodespositive                              | STRING | Regional Nodes Positive                            | [820](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=820/)     |
| regionalnodespositivedescription                   | STRING |                                                    |                                                                                                               |
| residualtumvolpostcytoreduction                    | STRING | Residual Tumor Volume Post Cytoreduction           | [3921](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3921/)   |
| residualtumvolpostcytoreductiondescription         | STRING |                                                    |                                                                                                               |
| responsetoneoadjuvanttherapy                       | STRING | Response to Neoadjuvant Therapy                    | [3922](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3922/)   |
| responsetoneoadjuvanttherapydescription            | STRING |                                                    |                                                                                                               |
| scategoryclinical                                  | STRING | S Category Clinical                                | [3923](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3923/)   |
| scategoryclinicaldescription                       | STRING |                                                    |                                                                                                               |
| scategorypathological                              | STRING | S Category Pathological                            | [3924](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3924/)   |
| scategorypathologicaldescription                   | STRING |                                                    |                                                                                                               |
| sarcomatoidfeatures                                | STRING | Sarcomatoid Features                               | [3925](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3925/)   |
| sarcomatoidfeaturesdescription                     | STRING |                                                    |                                                                                                               |
| tumordeposits                                      | STRING | Tumor Deposits                                     | [3934](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3934/)   |
| tumordepositsdescription                           | STRING |                                                    |                                                                                                               |
| tumorgrowthpattern                                 | STRING | Tumor Growth Pattern                               | [3935](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3935/)   |
| tumorgrowthpatterndescription                      | STRING |                                                    |                                                                                                               |
| tumormarker1                                       | STRING | Tumor Marker 1                                     | [1150](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1150/)   |
| tumormarker1description                            | STRING |                                                    |                                                                                                               |
| tumormarker2                                       | STRING | Tumor Marker 2                                     | [1160](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1160/)   |
| tumormarker2description                            | STRING |                                                    |                                                                                                               |
| tumormarker3                                       | STRING | Tumor Marker 3                                     | [1170](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1170/)   |
| tumormarker3description                            | STRING |                                                    |                                                                                                               |
| tumorsizeclinical                                  | STRING | Tumor Size Clinical                                | [752](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=752/)     |
| tumorsizeclinicaldescription                       | STRING |                                                    |                                                                                                               |
| tumorsizepathologic                                | STRING | Tumor Size Pathologic                              | [754](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=754/)     |
| tumorsizepathologicdescription                     | STRING |                                                    |                                                                                                               |
| tumorsizesummary                                   | STRING | Tumor Size Summary                                 | [756](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=756/)     |
| tumorsizesummarydescription                        | STRING |                                                    |                                                                                                               |
| ulceration                                         | STRING | Ulceration                                         | [3936](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3936/)   |
| ulcerationdescription                              | STRING |                                                    |                                                                                                               |
| visceralparietalpleuralinvasion                    | STRING | Visceral and Parietal Pleural Invasion             | [3937](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3937/)   |
| visceralparietalpleuralinvasiondescription         | STRING |                                                    |                                                                                                               |
| overrideadmisdx                                    | STRING | Over-ride Admis DX                                 | [70020](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=70020/) |
| overrideadmisdxdescription                         | STRING |                                                    |                                                                                                               |
| overridesitestage                                  | STRING | Over-ride Site Stage                               | [70022](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=70022/) |
| overridesitestagedescription                       | STRING |                                                    |                                                                                                               |
| textprimarysitetitle                               | STRING | Text--Primary Site Title                           | [2580](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=2580/)   |
| textstaging                                        | STRING | Text--Staging                                      | [2600](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=2600/)   |
| texthistologytitle                                 | STRING | Text--Histology Title                              | [2590](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=2590/)   |
| textplaceofdiagnosis                               | STRING | Text--Place of Diagnosis                           | [2690](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=2690/)   |
| cstumorsize                                        | STRING | CS Tumor Size                                      | [2800](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=2800/)   |
| secondarydiagnosis9                                | STRING | Secondary Diagnosis 9                              | [3796](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3796/)   |
| cstumorsizeexteval                                 | STRING | CS Tumor Size/Ext Eval                             | [2820](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=2820/)   |
| cstumorsizedescription                             | STRING |                                                    |                                                                                                               |
| secondarydiagnosis3description                     | STRING |                                                    |                                                                                                               |
| secondarydiagnosis4                                | STRING | Secondary Diagnosis 4                              | [3786](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3786/)   |
| secondarydiagnosis3                                | STRING | Secondary Diagnosis 3                              | [3784](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3784/)   |
| secondarydiagnosis1                                | STRING | Secondary Diagnosis 1                              | [3780](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3780/)   |
| cstumorsizeextevaldescription                      | STRING |                                                    |                                                                                                               |
| separatetumornodules                               | STRING | Separate Tumor Nodules                             | [3929](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3929/)   |
| breslowtumorthicknessdescription                   | STRING |                                                    |                                                                                                               |
| eodprimarytumor                                    | STRING | EOD Primary Tumor                                  | [772](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=772/)     |
| eodtumorsize                                       | STRING | EOD--Tumor Size                                    | [780](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=780/)     |
| breslowtumorthickness                              | STRING | Breslow Tumor Thickness                            | [3817](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3817/)   |
| eodtumorsizedescription                            | STRING |                                                    |                                                                                                               |
| separatetumornodulesdescription                    | STRING |                                                    |                                                                                                               |
| secondarydiagnosis10                               | STRING | Secondary Diagnosis 10                             | [3798](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3798/)   |
| secondarydiagnosis10description                    | STRING |                                                    |                                                                                                               |
| secondarydiagnosis1description                     | STRING |                                                    |                                                                                                               |
| secondarydiagnosis2                                | STRING | Secondary Diagnosis 2                              | [3782](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3782/)   |
| secondarydiagnosis2description                     | STRING |                                                    |                                                                                                               |
| secondarydiagnosis4description                     | STRING |                                                    |                                                                                                               |
| secondarydiagnosis5                                | STRING | Secondary Diagnosis 5                              | [3788](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3788/)   |
| secondarydiagnosis5description                     | STRING |                                                    |                                                                                                               |
| secondarydiagnosis6                                | STRING | Secondary Diagnosis 6                              | [3790](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3790/)   |
| secondarydiagnosis6description                     | STRING |                                                    |                                                                                                               |
| secondarydiagnosis7                                | STRING | Secondary Diagnosis 7                              | [3792](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3792/)   |
| secondarydiagnosis7description                     | STRING |                                                    |                                                                                                               |
| secondarydiagnosis8                                | STRING | Secondary Diagnosis 8                              | [3794](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3794/)   |
| secondarydiagnosis8description                     | STRING |                                                    |                                                                                                               |
| secondarydiagnosis9description                     | STRING |                                                    |                                                                                                               |
| anemia                                             | STRING | Anemia                                             | [3811](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3811/)   |
| anemiadescription                                  | STRING |                                                    |                                                                                                               |
| dateofmulttumorsflagdescription                    | STRING |                                                    |                                                                                                               |
| dateregionallndissection                           | STRING | Date Regional Lymph Node Dissection                | [682](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=682/)     |
| dateregionallndissectionflag                       | STRING | Date Regional Lymph Node Dissection Flag           | [683](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=683/)     |
| dateregionallndissectionflagdescription            | STRING |                                                    |                                                                                                               |
| datesentinellymphnodebiopsy                        | STRING | Date of Sentinel Lymph Node Biopsy                 | [832](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=832/)     |
| datesentinellymphnodebiopsyflag                    | STRING | Date Sentinel Lymph Node Biopsy Flag               | [833](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=833/)     |
| datesentinellymphnodebiopsyflagdescription         | STRING |                                                    |                                                                                                               |
| pathdatespeccollect1                               | STRING | Path Date Spec Collect 1                           | [7320](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=7320/)   |
| pathdatespeccollect2                               | STRING | Path Date Spec Collect 2                           | [7321](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=7321/)   |
| pathdatespeccollect3                               | STRING | Path Date Spec Collect 3                           | [7322](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=7322/)   |
| pathdatespeccollect4                               | STRING | Path Date Spec Collect 4                           | [7323](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=7323/)   |
| pathdatespeccollect5                               | STRING | Path Date Spec Collect 5                           | [7324](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=7324/)   |
| pathorderphyslicno1                                | STRING | Path Order Phys Lic No 1                           | [7100](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=7100/)   |
| pathorderphyslicno2                                | STRING | Path Order Phys Lic No 2                           | [7101](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=7101/)   |
| pathorderphyslicno3                                | STRING | Path Order Phys Lic No 3                           | [7102](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=7102/)   |
| pathorderphyslicno4                                | STRING | Path Order Phys Lic No 4                           | [7103](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=7103/)   |
| pathorderphyslicno5                                | STRING | Path Order Phys Lic No 5                           | [7104](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=7104/)   |
| pathorderingfacno1                                 | STRING | Path Ordering Fac No 1                             | [7190](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=7190/)   |
| pathorderingfacno1description                      | STRING |                                                    |                                                                                                               |
| pathorderingfacno2                                 | STRING | Path Ordering Fac No 2                             | [7191](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=7191/)   |
| pathorderingfacno2description                      | STRING |                                                    |                                                                                                               |
| pathorderingfacno3                                 | STRING | Path Ordering Fac No 3                             | [7192](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=7192/)   |
| pathorderingfacno3description                      | STRING |                                                    |                                                                                                               |
| pathorderingfacno4                                 | STRING | Path Ordering Fac No 4                             | [7193](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=7193/)   |
| pathorderingfacno4description                      | STRING |                                                    |                                                                                                               |
| pathorderingfacno5                                 | STRING | Path Ordering Fac No 5                             | [7194](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=7194/)   |
| pathorderingfacno5description                      | STRING |                                                    |                                                                                                               |
| pathreportnumber1                                  | STRING | Path Report Number 1                               | [7090](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=7090/)   |
| pathreportnumber2                                  | STRING | Path Report Number 2                               | [7091](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=7091/)   |
| pathreportnumber3                                  | STRING | Path Report Number 3                               | [7092](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=7092/)   |
| pathreportnumber4                                  | STRING | Path Report Number 4                               | [7093](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=7093/)   |
| pathreportnumber5                                  | STRING | Path Report Number 5                               | [7094](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=7094/)   |
| pathreporttype1                                    | STRING | Path Report Type 1                                 | [7480](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=7480/)   |
| pathreporttype1description                         | STRING |                                                    |                                                                                                               |
| pathreporttype2                                    | STRING | Path Report Type 2                                 | [7481](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=7481/)   |
| pathreporttype2description                         | STRING |                                                    |                                                                                                               |
| pathreporttype3                                    | STRING | Path Report Type 3                                 | [7482](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=7482/)   |
| pathreporttype3description                         | STRING |                                                    |                                                                                                               |
| pathreporttype4                                    | STRING | Path Report Type 4                                 | [7483](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=7483/)   |
| pathreporttype4description                         | STRING |                                                    |                                                                                                               |
| pathreporttype5                                    | STRING | Path Report Type 5                                 | [7484](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=7484/)   |
| pathreporttype5description                         | STRING |                                                    |                                                                                                               |
| pathreportingfacid1                                | STRING | Path Reporting Fac ID 1                            | [7010](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=7010/)   |
| pathreportingfacid1description                     | STRING |                                                    |                                                                                                               |
| pathreportingfacid2                                | STRING | Path Reporting Fac ID 2                            | [7011](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=7011/)   |
| pathreportingfacid2description                     | STRING |                                                    |                                                                                                               |
| pathreportingfacid3                                | STRING | Path Reporting Fac ID 3                            | [7012](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=7012/)   |
| pathreportingfacid3description                     | STRING |                                                    |                                                                                                               |
| pathreportingfacid4                                | STRING | Path Reporting Fac ID 4                            | [7013](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=7013/)   |
| pathreportingfacid4description                     | STRING |                                                    |                                                                                                               |
| pathreportingfacid5                                | STRING | Path Reporting Fac ID 5                            | [7014](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=7014/)   |
| pathreportingfacid5description                     | STRING |                                                    |                                                                                                               |
| adenoidcysticbasaloidpattern                       | STRING | Adenoid Cystic Basaloid Pattern                    | [3803](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3803/)   |
| adenopathy                                         | STRING | Adenopathy                                         | [3804](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3804/)   |
| adenopathydescription                              | STRING |                                                    |                                                                                                               |
| bsymptoms                                          | STRING | B symptoms                                         | [3812](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3812/)   |
| bsymptomsdescription                               | STRING |                                                    |                                                                                                               |
| boneinvasion                                       | STRING | Bone Invasion                                      | [3815](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3815/)   |
| boneinvasiondescription                            | STRING |                                                    |                                                                                                               |
| breastmethodofdetection                            | STRING | Breast Method of Detection                         | [22159](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=22159/) |
| breastmethodofdetectiondescription                 | STRING |                                                    |                                                                                                               |
| chromosome19qlossheterozygosity                    | STRING | Chromosome 19q: Loss of Heterozygosity (LOH)       | [3802](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3802/)   |
| chromosome19qlossheterozygositydescription         | STRING |                                                    |                                                                                                               |
| chromosome1plossheterozygosity                     | STRING | Chromosome 1p: Loss of Heterozygosity (LOH)        | [3801](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3801/)   |
| chromosome1plossheterozygositydescription          | STRING |                                                    |                                                                                                               |
| chromosome3status                                  | STRING | Chromosome 3 Status                                | [3821](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3821/)   |
| chromosome3statusdescription                       | STRING |                                                    |                                                                                                               |
| chromosome8qstatus                                 | STRING | Chromosome 8q Status                               | [3822](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3822/)   |
| chromosome8qstatusdescription                      | STRING |                                                    |                                                                                                               |
| circumferentialresectionmargin                     | STRING | Circumferential Resection Margin (CRM)             | [3823](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3823/)   |
| circumferentialresectionmargindescription          | STRING |                                                    |                                                                                                               |
| classofcase                                        | STRING | Class of Case                                      | [610](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=610/)     |
| classofcasedescription                             | STRING |                                                    |                                                                                                               |
| clinicalmarginwidth                                | STRING | Clinical Margin Width                              | [3961](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3961/)   |
| clinicalmarginwidthdescription                     | STRING |                                                    |                                                                                                               |
| cocaccreditedflag                                  | STRING | CoC Accredited Flag                                | [2152](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=2152/)   |
| cocaccreditedflagdescription                       | STRING |                                                    |                                                                                                               |
| coccodingsyscurrent                                | STRING | CoC Coding Sys--Current                            | [2140](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=2140/)   |
| coccodingsyscurrentdescription                     | STRING |                                                    |                                                                                                               |
| coccodingsysoriginal                               | STRING | CoC Coding Sys--Original                           | [2150](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=2150/)   |
| coccodingsysoriginaldescription                    | STRING |                                                    |                                                                                                               |
| cocexportflag                                      | STRING | CoC Export Flag                                    | [50071](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=50071/) |
| cocexportflagdescription                           | STRING |                                                    |                                                                                                               |
| cocmeasurebreastbcsrt                              | STRING |                                                    |                                                                                                               |
| cocmeasurebreastmac                                | STRING |                                                    |                                                                                                               |
| cocmeasurecolon12rln                               | STRING |                                                    |                                                                                                               |
| cocmeasurecolonact                                 | STRING |                                                    |                                                                                                               |
| cocmeasuregastricg15rln                            | STRING |                                                    |                                                                                                               |
| cocmeasurelunglct                                  | STRING |                                                    |                                                                                                               |
| cocmeasurerectalrecrtct                            | STRING |                                                    |                                                                                                               |
| codingproc                                         | STRING | Coding Proc                                        | [70000](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=70000/) |
| codingprocdescription                              | STRING |                                                    |                                                                                                               |
| csversioninputcurrent                              | STRING | CS Version Input Current                           | [2937](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=2937/)   |
| csversioninputcurrentdescription                   | STRING |                                                    |                                                                                                               |
| csversioninputoriginal                             | STRING | CS Version Input Original                          | [2935](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=2935/)   |
| csversioninputoriginaldescription                  | STRING |                                                    |                                                                                                               |
| ctrreview                                          | STRING | CTR Review                                         | [10028](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=10028/) |
| ctrreviewdescription                               | STRING |                                                    |                                                                                                               |
| datecaselastvalidatedcoc                           | STRING |                                                    |                                                                                                               |
| dateofmulttumorsflag                               | STRING | Date of Mult Tumors Flag                           | [439](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=439/)     |
| eodprimarytumordescription                         | STRING |                                                    |                                                                                                               |
| icdo3conversionflag                                | STRING | ICD-O-3 Conversion Flag                            | [2116](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=2116/)   |
| icdo3conversionflagdescription                     | STRING |                                                    |                                                                                                               |
| invasionbeyondcapsule                              | STRING | Invasion Beyond Capsule                            | [3864](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3864/)   |
| invasionbeyondcapsuledescription                   | STRING |                                                    |                                                                                                               |
| ipsilateraladrenalglandinvolve                     | STRING | Ipsilateral Adrenal Gland Involvement              | [3861](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3861/)   |
| ipsilateraladrenalglandinvolvedescription          | STRING |                                                    |                                                                                                               |
| morphtypebehavicdo2                                | STRING |                                                    |                                                                                                               |
| morphtypebehavicdo2description                     | STRING |                                                    |                                                                                                               |
| morphtypebehavicdo3                                | STRING |                                                    |                                                                                                               |
| morphtypebehavicdo3description                     | STRING |                                                    |                                                                                                               |
| primarydiagnosis                                   | STRING |                                                    |                                                                                                               |
| dateofdiagnosisflag                                | STRING | Date Of Diagnosis Flag                             | [391](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=391/)     |
| schema                                             | STRING | Site Specific Schema                               | [10498](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=10498/) |
| schemadiscriminator1                               | STRING | Schema Discriminator 1                             | [3926](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3926/)   |
| schemadiscriminator1description                    | STRING |                                                    |                                                                                                               |
| schemadiscriminator2                               | STRING | Schema Discriminator 2                             | [3927](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3927/)   |
| schemadiscriminator2description                    | STRING |                                                    |                                                                                                               |
| schemaid                                           | STRING | Schema ID                                          | [3800](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3800/)   |
| schemaiddescription                                | STRING |                                                    |                                                                                                               |
| schemaidversioncurrent                             | STRING | Schema ID Version Current                          | [2117](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=2117/)   |
| schemaidversioncurrentdescription                  | STRING |                                                    |                                                                                                               |
| schemaidversionoriginal                            | STRING | Schema ID Version Original                         | [2118](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=2118/)   |
| schemaidversionoriginaldescription                 | STRING |                                                    |                                                                                                               |
| scopelnproc1                                       | STRING | Scope LN Proc 1                                    | [70045](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=70045/) |
| scopelnproc1description                            | STRING |                                                    |                                                                                                               |
| scopelnproc2                                       | STRING | Scope LN Proc 2                                    | [70046](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=70046/) |
| scopelnproc2description                            | STRING |                                                    |                                                                                                               |
| scopelnproc3                                       | STRING | Scope LN Proc 3                                    | [70047](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=70047/) |
| scopelnproc3description                            | STRING |                                                    |                                                                                                               |
| seercodingsyscurrent                               | STRING |                                                    |                                                                                                               |
| seercodingsysoriginal                              | STRING |                                                    |                                                                                                               |
| seersitespecificfact1                              | STRING | SEER Site-Specific Fact 1                          | [3700](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3700/)   |
| seersitespecificfact1description                   | STRING |                                                    |                                                                                                               |
| sentinellymphnodesexamined                         | STRING | Sentinel Lymph Nodes Examined                      | [834](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=834/)     |
| sentinellymphnodesexamineddescription              | STRING |                                                    |                                                                                                               |
| sentinellymphnodespositive                         | STRING | Sentinel Lymph Nodes Positive                      | [835](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=835/)     |
| sentinellymphnodespositivedescription              | STRING |                                                    |                                                                                                               |
| sequencenumberhospital                             | STRING | Sequence Number--Hospital                          | [560](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=560/)     |
| sequencenumberhospitaldescription                  | STRING |                                                    |                                                                                                               |
| siteicdo1                                          | STRING |                                                    |                                                                                                               |
| stanforddiagnosisfacility                          | STRING | Stanford Diagnosis Facility                        | [23001](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=23001/) |
| stanforddiagnosisfacilitydescription               | STRING |                                                    |                                                                                                               |
| stanfordnonreportable                              | STRING |                                                    |                                                                                                               |
| stanfordsubsequent1diagnosisfacility               | STRING | Stanford Subsequent 1 Diagnosis Facility           | [23015](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=23015/) |
| stanfordsubsequent1diagnosisfacilitydescription    | STRING |                                                    |                                                                                                               |
| stanfordsubsequent2diagnosisfacility               | STRING | Stanford Subsequent 2 Diagnosis Facility           | [23023](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=23023/) |
| stanfordsubsequent2diagnosisfacilitydescription    | STRING |                                                    |                                                                                                               |
| stanfordsubsequent3diagnosisfacility               | STRING | Stanford Subsequent 3 Diagnosis Facility           | [23031](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=23031/) |
| stanfordsubsequent3diagnosisfacilitydescription    | STRING |                                                    |                                                                                                               |
| textdxprocop                                       | STRING | Text--DX Proc--Op                                  | [2560](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=2560/)   |
| textdxprocpe                                       | STRING | Text--DX Proc--PE                                  | [2520](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=2520/)   |
| textdxprocscopes                                   | STRING | Text--DX Proc--Scopes                              | [2540](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=2540/)   |
| thrombocytopenia                                   | STRING | Thrombocytopenia                                   | [3933](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3933/)   |
| thrombocytopeniadescription                        | STRING |                                                    |                                                                                                               |
| afppostorchiectomylabvalue                         | STRING | AFP Post-Orchiectomy Lab Value                     | [3805](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3805/)   |
| afppostorchiectomylabvaluedescription              | STRING |                                                    |                                                                                                               |
| afppostorchiectomyrange                            | STRING | AFP Post-Orchiectomy Range                         | [3806](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3806/)   |
| afppostorchiectomyrangedescription                 | STRING |                                                    |                                                                                                               |
| afppreorchiectomylabvalue                          | STRING | AFP Pre-Orchiectomy Lab Value                      | [3807](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3807/)   |
| afppreorchiectomylabvaluedescription               | STRING |                                                    |                                                                                                               |
| afppreorchiectomyrange                             | STRING | AFP Pre-Orchiectomy Range                          | [3808](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3808/)   |
| afppreorchiectomyrangedescription                  | STRING |                                                    |                                                                                                               |
| afppretreatmentinterpretation                      | STRING | AFP Pretreatment Interpretation                    | [3809](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3809/)   |
| afppretreatmentinterpretationdescription           | STRING |                                                    |                                                                                                               |
| afppretreatmentlabvalue                            | STRING | AFP Pretreatment Lab Value                         | [3810](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3810/)   |
| afppretreatmentlabvaluedescription                 | STRING |                                                    |                                                                                                               |
| alkrearrangement                                   | STRING | ALK Rearrangement                                  | [3938](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3938/)   |
| alkrearrangementdescription                        | STRING |                                                    |                                                                                                               |
| bilirubinpretxtotallabvalue                        | STRING | Bilirubin Pretreatment Total Lab Value             | [3813](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3813/)   |
| bilirubinpretxtotallabvaluedescription             | STRING |                                                    |                                                                                                               |
| bilirubinpretxunitofmeasure                        | STRING | Bilirubin Pretreatment Unit of Measure             | [3814](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3814/)   |
| bilirubinpretxunitofmeasuredescription             | STRING |                                                    |                                                                                                               |
| brafmutationalanalysis                             | STRING | BRAF Mutational Analysis                           | [3940](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3940/)   |
| brafmutationalanalysisdescription                  | STRING |                                                    |                                                                                                               |
| brainmolecularmarkers                              | STRING | Brain Molecular Markers                            | [3816](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3816/)   |
| brainmolecularmarkersdescription                   | STRING |                                                    |                                                                                                               |
| ca125pretreatmentinterpretation                    | STRING | CA-125 Pretreatment Interpretation                 | [3818](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3818/)   |
| ca125pretreatmentinterpretationdescription         | STRING |                                                    |                                                                                                               |
| ca199pretxlabvalue                                 | STRING | CA 19-9 PreTX Lab Value                            | [3942](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3942/)   |
| ca199pretxlabvaluedescription                      | STRING |                                                    |                                                                                                               |
| ceapretreatmentinterpretation                      | STRING | CEA Pretreatment Interpretation                    | [3819](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3819/)   |
| ceapretreatmentinterpretationdescription           | STRING |                                                    |                                                                                                               |
| ceapretreatmentlabvalue                            | STRING | CEA Pretreatment Lab Value                         | [3820](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3820/)   |
| ceapretreatmentlabvaluedescription                 | STRING |                                                    |                                                                                                               |
| creatininepretreatmentlabvalue                     | STRING | Creatinine Pretreatment Lab Value                  | [3824](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3824/)   |
| creatininepretreatmentlabvaluedescription          | STRING |                                                    |                                                                                                               |
| creatininepretxunitofmeasure                       | STRING | Creatinine Pretreatment Unit of Measure            | [3825](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3825/)   |
| creatininepretxunitofmeasuredescription            | STRING |                                                    |                                                                                                               |
| hcgpostorchiectomylabvalue                         | STRING | hCG Post-Orchiectomy Lab Value                     | [3846](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3846/)   |
| hcgpostorchiectomylabvaluedescription              | STRING |                                                    |                                                                                                               |
| hcgpostorchiectomyrange                            | STRING | hCG Post-Orchiectomy Range                         | [3847](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3847/)   |
| hcgpostorchiectomyrangedescription                 | STRING |                                                    |                                                                                                               |
| hcgpreorchiectomylabvalue                          | STRING | hCG Pre-Orchiectomy Lab Value                      | [3848](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3848/)   |
| hcgpreorchiectomylabvaluedescription               | STRING |                                                    |                                                                                                               |
| hcgpreorchiectomyrange                             | STRING | hCG Pre-Orchiectomy Range                          | [3849](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3849/)   |
| hcgpreorchiectomyrangedescription                  | STRING |                                                    |                                                                                                               |
| jak2                                               | STRING | JAK2                                               | [3862](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3862/)   |
| jak2description                                    | STRING |                                                    |                                                                                                               |
| ki67                                               | STRING | Ki-67                                              | [3863](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3863/)   |
| ki67description                                    | STRING |                                                    |                                                                                                               |
| kitgeneimmunohistochemistry                        | STRING | KIT Gene Immunohistochemistry                      | [3865](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3865/)   |
| kitgeneimmunohistochemistrydescription             | STRING |                                                    |                                                                                                               |
| kras                                               | STRING | KRAS                                               | [3866](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3866/)   |
| krasdescription                                    | STRING |                                                    |                                                                                                               |
| ldhpostorchiectomyrange                            | STRING | LDH Post-Orchiectomy Range                         | [3867](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3867/)   |
| ldhpostorchiectomyrangedescription                 | STRING |                                                    |                                                                                                               |
| ldhpreorchiectomyrange                             | STRING | LDH Pre-Orchiectomy Range                          | [3868](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3868/)   |
| ldhpreorchiectomyrangedescription                  | STRING |                                                    |                                                                                                               |
| ldhpretreatmentlabvalue                            | STRING | LDH Lab Value                                      | [3932](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3932/)   |
| ldhpretreatmentlabvaluedescription                 | STRING |                                                    |                                                                                                               |
| ldhpretreatmentlevel                               | STRING | LDH Level                                          | [3869](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3869/)   |
| ldhpretreatmentleveldescription                    | STRING |                                                    |                                                                                                               |
| ldhupperlimitsofnormal                             | STRING | LDH Upper Limits of Normal                         | [3870](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3870/)   |
| ldhupperlimitsofnormaldescription                  | STRING |                                                    |                                                                                                               |
| progesteronerecepprcntposorrange                   | STRING | Progesterone Receptor Percent Positive or Range    | [3914](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3914/)   |
| progesteronerecepprcntposorrangedescription        | STRING |                                                    |                                                                                                               |
| progesteronerecepsummary                           | STRING | Progesterone Receptor Summary                      | [3915](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3915/)   |
| progesteronerecepsummarydescription                | STRING |                                                    |                                                                                                               |
| progesteronereceptotalallredscor                   | STRING | Progesterone Receptor Total Allred Score           | [3916](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3916/)   |
| progesteronereceptotalallredscordescription        | STRING |                                                    |                                                                                                               |
| prostatepathologicalextension                      | STRING | EOD Prostate Pathologic Extension                  | [3919](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3919/)   |
| prostatepathologicalextensiondescription           | STRING |                                                    |                                                                                                               |
| protocolparticipation                              | STRING | Protocol Participation                             | [1480](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1480/)   |
| protocolparticipationdescription                   | STRING |                                                    |                                                                                                               |
| psalabvalue                                        | STRING | PSA (Prostatic Specific Antigen) Lab Value         | [3920](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3920/)   |
| psalabvaluedescription                             | STRING |                                                    |                                                                                                               |
| serumalbuminpretreatmentlevel                      | STRING | Serum Albumin Pretreatment Level                   | [3930](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3930/)   |
| serumalbuminpretreatmentleveldescription           | STRING |                                                    |                                                                                                               |
| serumbeta2microglobulinpretxlvl                    | STRING | Serum Beta-2 Microglobulin Pretreatment Level      | [3931](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3931/)   |
| serumbeta2microglobulinpretxlvldescription         | STRING |                                                    |                                                                                                               |
| stanfordbileductgenetictestingperformed            | STRING | Stanford Bile Duct Genetic Testing Performed       | [10023](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=10023/) |
| stanfordbileductgenetictestingperformeddescription | STRING |                                                    |                                                                                                               |
| stanfordbileductgenetictestingresults              | STRING | Stanford Bile Duct Genetic Testing Results         | [10024](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=10024/) |
| stanfordbileductgenetictestingresultsdescription   | STRING |                                                    |                                                                                                               |
| stanfordbileductgenetictestingresultstext          | STRING | Stanford Bile Duct Genetic Testing Results Text    | [10025](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=10025/) |
| stanfordbileductmsi                                | STRING | Stanford Bile Duct MSI                             | [10026](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=10026/) |
| stanfordbileductmsidescription                     | STRING |                                                    |                                                                                                               |
| stanfordbileducttumormutationalburdentmb           | STRING | Stanford Bile Duct Tumor Mutational Burden (TMB)   | [10027](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=10027/) |
| stanfordmelanomabraf                               | STRING | Stanford Melanoma BRAF                             | [10022](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=10022/) |
| stanfordmelanomabrafdescription                    | STRING |                                                    |                                                                                                               |
| stanfordpdl1                                       | STRING | Stanford PdL1 (Lung)                               | [23004](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=23004/) |
| stanfordpdl1description                            | STRING |                                                    |                                                                                                               |
| textdxproclabtests                                 | STRING | Text--DX Proc--Lab Tests                           | [2550](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=2550/)   |

:  {.hover .responsive .sm}