---
title: "NeuralFrame Case Treatments"
---

This category outlines the various treatments administered to patients, including surgical interventions, chemotherapy, radiation therapy, and other therapeutic approaches.

### Table Columns

| column name                                               | type    | phi   | phi-scrubbing operation       | naaccr number                                                                                                   |
|:----------------------------------------------------------|:--------|:------|:------------------------------|:----------------------------------------------------------------------------------------------------------------|
| date1stcrsrxcoc                                           | STRING  | Yes   | Jitter                        | [1270](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1270/)     |
| dateinitialrxseer                                         | STRING  | Yes   | Jitter                        | [1260](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1260/)     |
| datesurgproc1                                             | STRING  | Yes   | Jitter                        | [70002](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=70002/)   |
| datesurgproc1flag                                         | STRING  |       |                            | [70003](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=70003/)   |
| datesurgproc1flagdescription                              | STRING  |       |                            |                                                                                                                 |
| datesurgproc2                                             | STRING  | Yes   | Jitter                        | [70004](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=70004/)   |
| datesurgproc2flag                                         | STRING  |       |                            | [70005](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=70005/)   |
| datesurgproc2flagdescription                              | STRING  |       |                            |                                                                                                                 |
| datesurgproc3                                             | STRING  | Yes   | Jitter                        | [70006](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=70006/)   |
| datesurgproc3flag                                         | STRING  |       |                            | [70007](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=70007/)   |
| datesurgproc3flagdescription                              | STRING  |       |                            |                                                                                                                 |
| intentoftreatment                                         | STRING  |       |                            | [1560](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1560/)     |
| intentoftreatmentdescription                              | STRING  |       |                            |                                                                                                                 |
| nameofradiationdrug                                       | STRING  |       |                            | [10008](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=10008/)   |
| nameofradiationdrugdescription                            | STRING  |       |                            |                                                                                                                 |
| neoadjuvanttherapy                                        | STRING  |       |                            | [1632](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1632/)     |
| neoadjuvanttherapydescription                             | STRING  |       |                            |                                                                                                                 |
| neoadjuvtherapyclinicalresponse                           | STRING  |       |                            | [1633](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1633/)     |
| neoadjuvtherapyclinicalresponsedescription                | STRING  |       |                            |                                                                                                                 |
| neoadjuvtherapytreatmenteffect                            | STRING  |       |                            | [1634](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1634/)     |
| neoadjuvtherapytreatmenteffectdescription                 | STRING  |       |                            |                                                                                                                 |
| nfcaseentityid                                            | STRING  | Yes   | Stable Between Data Refreshes |                                                                                                                 |
| nfcasestatus                                              | STRING  |       |                            |                                                                                                                 |
| nmtexthemtransplantendocrine                              | STRING  | Yes   | TiDE                          | [10030](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=10030/)   |
| numberphasesofradtxtovolume                               | STRING  |       |                            | [1532](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1532/)     |
| numberphasesofradtxtovolumedescription                    | STRING  |       |                            |                                                                                                                 |
| person_id                                                 | INTEGER | Yes   | Stable Between Data Refreshes |                                                                                                                 |
| phase1doseperfraction                                     | STRING  |       |                            | [1501](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1501/)     |
| phase1doseperfractiondescription                          | STRING  |       |                            |                                                                                                                 |
| phase1numberoffractions                                   | STRING  |       |                            | [1503](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1503/)     |
| phase1numberoffractionsdescription                        | STRING  |       |                            |                                                                                                                 |
| phase1radiationexternalbeamtech                           | STRING  |       |                            | [1502](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1502/)     |
| phase1radiationexternalbeamtechdescription                | STRING  |       |                            |                                                                                                                 |
| phase1radiationprimarytxvolume                            | STRING  |       |                            | [1504](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1504/)     |
| phase1radiationprimarytxvolumedescription                 | STRING  |       |                            |                                                                                                                 |
| phase1radiationtodrainingln                               | STRING  |       |                            | [1505](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1505/)     |
| phase1radiationtodraininglndescription                    | STRING  |       |                            |                                                                                                                 |
| phase1radiationtreatmentmodality                          | STRING  |       |                            | [1506](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1506/)     |
| phase1radiationtreatmentmodalitydescription               | STRING  |       |                            |                                                                                                                 |
| phase1totaldose                                           | STRING  |       |                            | [1507](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1507/)     |
| phase1totaldosedescription                                | STRING  |       |                            |                                                                                                                 |
| phase2doseperfraction                                     | STRING  |       |                            | [1511](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1511/)     |
| phase2doseperfractiondescription                          | STRING  |       |                            |                                                                                                                 |
| phase2numberoffractions                                   | STRING  |       |                            | [1513](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1513/)     |
| phase2numberoffractionsdescription                        | STRING  |       |                            |                                                                                                                 |
| phase2radiationexternalbeamtech                           | STRING  |       |                            | [1512](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1512/)     |
| phase2radiationexternalbeamtechdescription                | STRING  |       |                            |                                                                                                                 |
| phase2radiationprimarytxvolume                            | STRING  |       |                            | [1514](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1514/)     |
| phase2radiationprimarytxvolumedescription                 | STRING  |       |                            |                                                                                                                 |
| phase2radiationtodrainingln                               | STRING  |       |                            | [1515](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1515/)     |
| phase2radiationtodraininglndescription                    | STRING  |       |                            |                                                                                                                 |
| phase2radiationtreatmentmodality                          | STRING  |       |                            | [1516](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1516/)     |
| phase2radiationtreatmentmodalitydescription               | STRING  |       |                            |                                                                                                                 |
| phase2totaldose                                           | STRING  |       |                            | [1517](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1517/)     |
| phase2totaldosedescription                                | STRING  |       |                            |                                                                                                                 |
| phase3doseperfraction                                     | STRING  |       |                            | [1521](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1521/)     |
| phase3doseperfractiondescription                          | STRING  |       |                            |                                                                                                                 |
| phase3numberoffractions                                   | STRING  |       |                            | [1523](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1523/)     |
| phase3numberoffractionsdescription                        | STRING  |       |                            |                                                                                                                 |
| phase3radiationexternalbeamtech                           | STRING  |       |                            | [1522](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1522/)     |
| phase3radiationexternalbeamtechdescription                | STRING  |       |                            |                                                                                                                 |
| phase3radiationprimarytxvolume                            | STRING  |       |                            | [1524](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1524/)     |
| phase3radiationprimarytxvolumedescription                 | STRING  |       |                            |                                                                                                                 |
| phase3radiationtodrainingln                               | STRING  |       |                            | [1525](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1525/)     |
| phase3radiationtodraininglndescription                    | STRING  |       |                            |                                                                                                                 |
| phase3radiationtreatmentmodality                          | STRING  |       |                            | [1526](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1526/)     |
| phase3radiationtreatmentmodalitydescription               | STRING  |       |                            |                                                                                                                 |
| phase3totaldose                                           | STRING  |       |                            | [1527](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1527/)     |
| phase3totaldosedescription                                | STRING  |       |                            |                                                                                                                 |
| radboostdosecgy                                           | STRING  |       |                            | [3210](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3210/)     |
| radboostdosecgydescription                                | STRING  |       |                            |                                                                                                                 |
| radboostrxmodality                                        | STRING  |       |                            | [3200](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3200/)     |
| radboostrxmodalitydescription                             | STRING  |       |                            |                                                                                                                 |
| radiationcompletionstatus                                 | STRING  |       |                            | [10071](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=10071/)   |
| radiationlocalcontrolstatus                               | STRING  |       |                            | [1590](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1590/)     |
| radiationlocalcontrolstatusdescription                    | STRING  |       |                            |                                                                                                                 |
| radiationtxdiscontinuedearly                              | STRING  |       |                            | [1531](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1531/)     |
| radiationtxdiscontinuedearlydescription                   | STRING  |       |                            |                                                                                                                 |
| radlocationofrx                                           | STRING  |       |                            | [1550](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1550/)     |
| radlocationofrxdescription                                | STRING  |       |                            |                                                                                                                 |
| radnooftreatmentvol                                       | STRING  |       |                            | [1520](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1520/)     |
| radnooftreatmentvoldescription                            | STRING  |       |                            |                                                                                                                 |
| radregionaldosecgy                                        | STRING  |       |                            | [1510](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1510/)     |
| radregionaldosecgydescription                             | STRING  |       |                            |                                                                                                                 |
| radregionalrxmodality                                     | STRING  |       |                            | [1570](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1570/)     |
| radregionalrxmodalitydescription                          | STRING  |       |                            |                                                                                                                 |
| radtreatmentvolume                                        | STRING  |       |                            | [1540](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1540/)     |
| radtreatmentvolumedescription                             | STRING  |       |                            |                                                                                                                 |
| readmsamehosp30days                                       | STRING  |       |                            | [3190](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3190/)     |
| readmsamehosp30daysdescription                            | STRING  |       |                            |                                                                                                                 |
| reasonfornoradiation                                      | STRING  |       |                            | [1430](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1430/)     |
| reasonfornoradiationdescription                           | STRING  |       |                            |                                                                                                                 |
| reasonfornosurgery                                        | STRING  |       |                            | [1340](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1340/)     |
| reasonfornosurgerydescription                             | STRING  |       |                            |                                                                                                                 |
| rxcodingsystemcurrent                                     | STRING  |       |                            | [1460](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1460/)     |
| rxcodingsystemcurrentdescription                          | STRING  |       |                            |                                                                                                                 |
| rxdatebrm                                                 | STRING  | Yes   | Jitter                        | [1240](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1240/)     |
| rxdatebrmflag                                             | STRING  |       |                            | [1241](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1241/)     |
| rxdatebrmflagdescription                                  | STRING  |       |                            |                                                                                                                 |
| rxdatechemo                                               | STRING  | Yes   | Jitter                        | [1220](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1220/)     |
| rxdatechemoflag                                           | STRING  |       |                            | [1221](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1221/)     |
| rxdatechemoflagdescription                                | STRING  |       |                            |                                                                                                                 |
| rxdatedxstgproc                                           | STRING  |       |                            | [1280](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1280/)     |
| rxdatedxstgprocflag                                       | STRING  | Yes   | Jitter                        | [1281](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1281/)     |
| rxdatedxstgprocflagdescription                            | STRING  |       |                            |                                                                                                                 |
| rxdatehormone                                             | STRING  | Yes   | Jitter                        | [1230](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1230/)     |
| rxdatehormoneflag                                         | STRING  |       |                            | [1231](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1231/)     |
| rxdatehormoneflagdescription                              | STRING  |       |                            |                                                                                                                 |
| rxdatemostdefinsurg                                       | STRING  | Yes   | Jitter                        | [3170](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3170/)     |
| rxdatemostdefinsurgflag                                   | STRING  |       |                            | [3171](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3171/)     |
| rxdatemostdefinsurgflagdescription                        | STRING  |       |                            |                                                                                                                 |
| rxdateother                                               | STRING  | Yes   | Jitter                        | [1250](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1250/)     |
| rxdateotherflag                                           | STRING  |       |                            | [1251](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1251/)     |
| rxdateotherflagdescription                                | STRING  |       |                            |                                                                                                                 |
| rxdateradiation                                           | STRING  | Yes   | Jitter                        | [1210](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1210/)     |
| rxdateradiationended                                      | STRING  | Yes   | Jitter                        | [3220](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3220/)     |
| rxdateradiationendedflag                                  | STRING  |       |                            | [3221](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3221/)     |
| rxdateradiationendedflagdescription                       | STRING  |       |                            |                                                                                                                 |
| rxdateradiationflag                                       | STRING  |       |                            | [1211](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1211/)     |
| rxdateradiationflagdescription                            | STRING  |       |                            |                                                                                                                 |
| rxdatesurgery                                             | STRING  | Yes   | Jitter                        | [1200](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1200/)     |
| rxdatesurgeryflag                                         | STRING  |       |                            | [1201](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1201/)     |
| rxdatesurgeryflagdescription                              | STRING  |       |                            |                                                                                                                 |
| rxdatesurgicaldisch                                       | STRING  | Yes   | Jitter                        | [3180](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3180/)     |
| rxdatesurgicaldischflag                                   | STRING  |       |                            | [3181](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3181/)     |
| rxdatesurgicaldischflagdescription                        | STRING  |       |                            |                                                                                                                 |
| rxdatesystemic                                            | STRING  | Yes   | Jitter                        | [3230](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3230/)     |
| rxdatesystemicflag                                        | STRING  |       |                            | [3231](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3231/)     |
| rxdatesystemicflagdescription                             | STRING  |       |                            |                                                                                                                 |
| rxdatetranspendo                                          | STRING  | Yes   | Jitter                        | [70043](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=70043/)   |
| rxdatetranspendoflag                                      | STRING  |       |                            | [70044](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=70044/)   |
| rxdatetranspendoflagdescription                           | STRING  |       |                            |                                                                                                                 |
| rxhospbrm                                                 | STRING  |       |                            | [720](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=720/)       |
| rxhospbrmdescription                                      | STRING  |       |                            |                                                                                                                 |
| rxhospchemo                                               | STRING  |       |                            | [700](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=700/)       |
| rxhospchemodescription                                    | STRING  |       |                            |                                                                                                                 |
| rxhosphormone                                             | STRING  |       |                            | [710](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=710/)       |
| rxhosphormonedescription                                  | STRING  |       |                            |                                                                                                                 |
| rxhospother                                               | STRING  |       |                            | [730](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=730/)       |
| rxhospotherdescription                                    | STRING  |       |                            |                                                                                                                 |
| rxhosppalliativeproc                                      | STRING  |       |                            | [3280](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3280/)     |
| rxhosppalliativeprocdescription                           | STRING  |       |                            |                                                                                                                 |
| rxhospradiation                                           | STRING  |       |                            |                                                                                                                 |
| rxhospreconbreast                                         | STRING  |       |                            | [10106](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=10106/)   |
| rxhospreconbreastdescription                              | STRING  |       |                            |                                                                                                                 |
| rxhospreglnremoved                                        | STRING  |       |                            |                                                                                                                 |
| rxhospscopereg9802                                        | STRING  |       |                            | [747](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=747/)       |
| rxhospscopereg9802description                             | STRING  |       |                            |                                                                                                                 |
| rxhospscopereglnsur                                       | STRING  |       |                            | [672](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=672/)       |
| rxhospscopereglnsurdescription                            | STRING  |       |                            |                                                                                                                 |
| rxhospsurgapp2010                                         | STRING  |       |                            | [668](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=668/)       |
| rxhospsurgapp2010description                              | STRING  |       |                            |                                                                                                                 |
| rxhospsurgbreast                                          | STRING  |       |                            | [10104](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=10104/)   |
| rxhospsurgbreastdescription                               | STRING  |       |                            |                                                                                                                 |
| rxhospsurgoth9802                                         | STRING  |       |                            | [748](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=748/)       |
| rxhospsurgoth9802description                              | STRING  |       |                            |                                                                                                                 |
| rxhospsurgothregdis                                       | STRING  |       |                            | [674](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=674/)       |
| rxhospsurgothregdisdescription                            | STRING  |       |                            |                                                                                                                 |
| rxhospsurgprimsite                                        | STRING  |       |                            | [670](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=670/)       |
| rxhospsurgprimsite2023                                    | STRING  |       |                            | [671](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=671/)       |
| rxhospsurgprimsite2023description                         | STRING  |       |                            |                                                                                                                 |
| rxhospsurgprimsitedescription                             | STRING  |       |                            |                                                                                                                 |
| rxhospsurgsite9802                                        | STRING  |       |                            | [746](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=746/)       |
| rxhospsurgsite9802description                             | STRING  |       |                            |                                                                                                                 |
| rxsummbrm                                                 | STRING  |       |                            | [1410](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1410/)     |
| rxsummbrmdescription                                      | STRING  |       |                            |                                                                                                                 |
| rxsummchemo                                               | STRING  |       |                            | [1390](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1390/)     |
| rxsummchemodescription                                    | STRING  |       |                            |                                                                                                                 |
| rxsummdxstgproc                                           | STRING  |       |                            | [1350](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1350/)     |
| rxsummdxstgprocdescription                                | STRING  |       |                            |                                                                                                                 |
| rxsummhormone                                             | STRING  |       |                            | [1400](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1400/)     |
| rxsummhormonedescription                                  | STRING  |       |                            |                                                                                                                 |
| rxsummother                                               | STRING  |       |                            | [1420](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1420/)     |
| rxsummotherdescription                                    | STRING  |       |                            |                                                                                                                 |
| rxsummpalliativeproc                                      | STRING  |       |                            | [3270](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3270/)     |
| rxsummpalliativeprocdescription                           | STRING  |       |                            |                                                                                                                 |
| rxsummradiation                                           | STRING  |       |                            | [1360](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1360/)     |
| rxsummradiationdescription                                | STRING  |       |                            |                                                                                                                 |
| rxsummradtocns                                            | STRING  |       |                            |                                                                                                                 |
| rxsummreconbreast                                         | STRING  |       |                            | [10107](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=10107/)   |
| rxsummreconbreastdescription                              | STRING  |       |                            |                                                                                                                 |
| rxsummreconstruct1st                                      | STRING  |       |                            | [1330](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1330/)     |
| rxsummreconstruct1stdescription                           | STRING  |       |                            |                                                                                                                 |
| rxsummreglnexamined                                       | STRING  |       |                            | [1296](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1296/)     |
| rxsummreglnexamineddescription                            | STRING  |       |                            |                                                                                                                 |
| rxsummscopereg9802                                        | STRING  |       |                            | [1647](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1647/)     |
| rxsummscopereg9802description                             | STRING  |       |                            |                                                                                                                 |
| rxsummscopereglnsur                                       | STRING  |       |                            | [1292](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1292/)     |
| rxsummscopereglnsurdescription                            | STRING  |       |                            |                                                                                                                 |
| rxsummsurgbreast                                          | STRING  |       |                            | [10105](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=10105/)   |
| rxsummsurgbreastdescription                               | STRING  |       |                            |                                                                                                                 |
| rxsummsurgerytype                                         | STRING  |       |                            |                                                                                                                 |
| rxsummsurgicalapproch                                     | STRING  |       |                            | [1310](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1310/)     |
| rxsummsurgicalapprochdescription                          | STRING  |       |                            |                                                                                                                 |
| rxsummsurgicalmargins                                     | STRING  |       |                            | [1320](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1320/)     |
| rxsummsurgicalmarginsdescription                          | STRING  |       |                            |                                                                                                                 |
| rxsummsurgoth9802                                         | STRING  |       |                            | [1648](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1648/)     |
| rxsummsurgoth9802description                              | STRING  |       |                            |                                                                                                                 |
| rxsummsurgothregdis                                       | STRING  |       |                            | [1294](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1294/)     |
| rxsummsurgothregdisdescription                            | STRING  |       |                            |                                                                                                                 |
| rxsummsurgprimsite                                        | STRING  |       |                            | [1290](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1290/)     |
| rxsummsurgprimsite2023                                    | STRING  |       |                            | [1291](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1291/)     |
| rxsummsurgprimsite2023description                         | STRING  |       |                            |                                                                                                                 |
| rxsummsurgprimsitedescription                             | STRING  |       |                            |                                                                                                                 |
| rxsummsurgradseq                                          | STRING  |       |                            | [1380](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1380/)     |
| rxsummsurgradseqdescription                               | STRING  |       |                            |                                                                                                                 |
| rxsummsurgsite9802                                        | STRING  |       |                            | [1646](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1646/)     |
| rxsummsurgsite9802description                             | STRING  |       |                            |                                                                                                                 |
| rxsummsystemicsurseq                                      | STRING  |       |                            | [1639](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1639/)     |
| rxsummsystemicsurseqdescription                           | STRING  |       |                            |                                                                                                                 |
| rxsummtransplntendocr                                     | STRING  |       |                            | [3250](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3250/)     |
| rxsummtransplntendocrdescription                          | STRING  |       |                            |                                                                                                                 |
| rxsummtreatmentstatus                                     | STRING  |       |                            | [1285](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1285/)     |
| rxsummtreatmentstatusdescription                          | STRING  |       |                            |                                                                                                                 |
| rxtextbrm                                                 | STRING  | Yes   | TiDE                          | [2660](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=2660/)     |
| rxtextchemo                                               | STRING  | Yes   | TiDE                          | [2640](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=2640/)     |
| rxtexthormone                                             | STRING  | Yes   | TiDE                          | [2650](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=2650/)     |
| rxtextother                                               | STRING  | Yes   | TiDE                          | [2670](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=2670/)     |
| rxtextpalliative                                          | STRING  | Yes   | TiDE                          | [100039](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=100039/) |
| rxtextradiation                                           | STRING  | Yes   | TiDE                          | [2620](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=2620/)     |
| rxtextradiationother                                      | STRING  | Yes   | TiDE                          | [2630](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=2630/)     |
| rxtextsurgery                                             | STRING  | Yes   | TiDE                          | [2610](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=2610/)     |
| rxtextsurgery1                                            | STRING  | Yes   | TiDE                          | [70066](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=70066/)   |
| rxtextsurgery2                                            | STRING  | Yes   | TiDE                          | [70067](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=70067/)   |
| rxtextsurgery3                                            | STRING  | Yes   | TiDE                          | [70068](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=70068/)   |
| stanford1stcoursechemofacility                            | STRING  |       |                            | [23008](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=23008/)   |
| stanford1stcoursechemofacilitydescription                 | STRING  |       |                            |                                                                                                                 |
| stanford1stcoursehormonefacility                          | STRING  |       |                            | [23011](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=23011/)   |
| stanford1stcoursehormonefacilitydescription               | STRING  |       |                            |                                                                                                                 |
| stanford1stcourseimmunofacility                           | STRING  |       |                            | [23010](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=23010/)   |
| stanford1stcourseimmunofacilitydescription                | STRING  |       |                            |                                                                                                                 |
| stanford1stcourseotherrxfacility                          | STRING  |       |                            | [23013](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=23013/)   |
| stanford1stcourseotherrxfacilitydescription               | STRING  |       |                            |                                                                                                                 |
| stanford1stcoursepalliativefacility                       | STRING  |       |                            | [23012](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=23012/)   |
| stanford1stcoursepalliativefacilitydescription            | STRING  |       |                            |                                                                                                                 |
| stanford1stcourseradiationfacility                        | STRING  |       |                            | [23009](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=23009/)   |
| stanford1stcourseradiationfacilitydescription             | STRING  |       |                            |                                                                                                                 |
| stanford1stcoursesurgeryfacility                          | STRING  |       |                            | [23007](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=23007/)   |
| stanford1stcoursesurgeryfacilitydescription               | STRING  |       |                            |                                                                                                                 |
| stanford1stcoursetransplantendocrinefacility              | STRING  |       |                            | [33043](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=33043/)   |
| stanford1stcoursetransplantendocrinefacilitydescription   | STRING  |       |                            |                                                                                                                 |
| stanford_patient_uid                                      | STRING  | Yes   | Del                           |                                                                                                                 |
| stanfordadditionaltext                                    | STRING  | Yes   | TiDE                          | [10032](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=10032/)   |
| stanfordradiationgivenateden                              | STRING  |       |                            | [23038](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=23038/)   |
| stanfordradiationgivenatedendescription                   | STRING  |       |                            |                                                                                                                 |
| stanfordradiationgivenatseroc                             | STRING  |       |                            | [10011](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=10011/)   |
| stanfordradiationgivenatserocdescription                  | STRING  |       |                            |                                                                                                                 |
| stanfordrouteofadministrationhormone                      | STRING  |       |                            | [33046](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=33046/)   |
| stanfordrouteofadministrationhormonedescription           | STRING  |       |                            |                                                                                                                 |
| stanfordrouteofadministrationimmuno                       | STRING  |       |                            | [33047](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=33047/)   |
| stanfordrouteofadministrationimmunodescription            | STRING  |       |                            |                                                                                                                 |
| stanfordsubsequent1chemofacility                          | STRING  |       |                            | [23016](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=23016/)   |
| stanfordsubsequent1chemofacilitydescription               | STRING  |       |                            |                                                                                                                 |
| stanfordsubsequent1hormonefacility                        | STRING  |       |                            | [23019](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=23019/)   |
| stanfordsubsequent1hormonefacilitydescription             | STRING  |       |                            |                                                                                                                 |
| stanfordsubsequent1immunofacility                         | STRING  |       |                            | [23018](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=23018/)   |
| stanfordsubsequent1immunofacilitydescription              | STRING  |       |                            |                                                                                                                 |
| stanfordsubsequent1otherrxfacility                        | STRING  |       |                            | [23021](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=23021/)   |
| stanfordsubsequent1otherrxfacilitydescription             | STRING  |       |                            |                                                                                                                 |
| stanfordsubsequent1palliativefacility                     | STRING  |       |                            | [23020](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=23020/)   |
| stanfordsubsequent1palliativefacilitydescription          | STRING  |       |                            |                                                                                                                 |
| stanfordsubsequent1radiationfacility                      | STRING  |       |                            | [23017](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=23017/)   |
| stanfordsubsequent1radiationfacilitydescription           | STRING  |       |                            |                                                                                                                 |
| stanfordsubsequent1surgeryfacility                        | STRING  |       |                            | [23014](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=23014/)   |
| stanfordsubsequent1surgeryfacilitydescription             | STRING  |       |                            |                                                                                                                 |
| stanfordsubsequent1transplantendocrinefacility            | STRING  |       |                            | [10012](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=10012/)   |
| stanfordsubsequent1transplantendocrinefacilitydescription | STRING  |       |                            |                                                                                                                 |
| stanfordsubsequent2chemofacility                          | STRING  |       |                            | [23024](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=23024/)   |
| stanfordsubsequent2chemofacilitydescription               | STRING  |       |                            |                                                                                                                 |
| stanfordsubsequent2hormonefacility                        | STRING  |       |                            | [23027](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=23027/)   |
| stanfordsubsequent2hormonefacilitydescription             | STRING  |       |                            |                                                                                                                 |
| stanfordsubsequent2immunofacility                         | STRING  |       |                            | [23026](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=23026/)   |
| stanfordsubsequent2immunofacilitydescription              | STRING  |       |                            |                                                                                                                 |
| stanfordsubsequent2otherrxfacility                        | STRING  |       |                            | [23029](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=23029/)   |
| stanfordsubsequent2otherrxfacilitydescription             | STRING  |       |                            |                                                                                                                 |
| stanfordsubsequent2palliativefacility                     | STRING  |       |                            | [23028](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=23028/)   |
| stanfordsubsequent2palliativefacilitydescription          | STRING  |       |                            |                                                                                                                 |
| stanfordsubsequent2radiationfacility                      | STRING  |       |                            | [23025](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=23025/)   |
| stanfordsubsequent2radiationfacilitydescription           | STRING  |       |                            |                                                                                                                 |
| stanfordsubsequent2surgeryfacility                        | STRING  |       |                            | [23022](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=23022/)   |
| stanfordsubsequent2surgeryfacilitydescription             | STRING  |       |                            |                                                                                                                 |
| stanfordsubsequent2transplantendocrinefacility            | STRING  |       |                            | [33041](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=33041/)   |
| stanfordsubsequent2transplantendocrinefacilitydescription | STRING  |       |                            |                                                                                                                 |
| stanfordsubsequent3chemofacility                          | STRING  |       |                            | [23032](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=23032/)   |
| stanfordsubsequent3chemofacilitydescription               | STRING  |       |                            |                                                                                                                 |
| stanfordsubsequent3hormonefacility                        | STRING  |       |                            | [23035](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=23035/)   |
| stanfordsubsequent3hormonefacilitydescription             | STRING  |       |                            |                                                                                                                 |
| stanfordsubsequent3immunofacility                         | STRING  |       |                            | [23034](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=23034/)   |
| stanfordsubsequent3immunofacilitydescription              | STRING  |       |                            |                                                                                                                 |
| stanfordsubsequent3otherrxfacility                        | STRING  |       |                            | [23037](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=23037/)   |
| stanfordsubsequent3otherrxfacilitydescription             | STRING  |       |                            |                                                                                                                 |
| stanfordsubsequent3palliativefacility                     | STRING  |       |                            | [23036](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=23036/)   |
| stanfordsubsequent3palliativefacilitydescription          | STRING  |       |                            |                                                                                                                 |
| stanfordsubsequent3radiationfacility                      | STRING  |       |                            | [23033](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=23033/)   |
| stanfordsubsequent3radiationfacilitydescription           | STRING  |       |                            |                                                                                                                 |
| stanfordsubsequent3surgeryfacility                        | STRING  |       |                            | [23030](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=23030/)   |
| stanfordsubsequent3surgeryfacilitydescription             | STRING  |       |                            |                                                                                                                 |
| stanfordsubsequent3transplantendocrinefacility            | STRING  |       |                            | [33042](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=33042/)   |
| stanfordsubsequent3transplantendocrinefacilitydescription | STRING  |       |                            |                                                                                                                 |
| stanfordtextprotocol                                      | STRING  | Yes   | TiDE                          | [33044](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=33044/)   |
| subsequenttreatmentneeded                                 | STRING  |       |                            |                                                                                                                 |
| subsequenttreatmentneededdescription                      | STRING  |       |                            |                                                                                                                 |
| subsequenttreatmenttext                                   | STRING  | Yes   | TiDE                          |                                                                                                                 |
| subsqrx2ndcoursechemo                                     | STRING  |       |                            |                                                                                                                 |
| subsqrx2ndcoursedate                                      | STRING  | Yes   | Jitter                        |                                                                                                                 |
| subsqrx2ndcourseoth                                       | STRING  |       |                            |                                                                                                                 |
| subsqrx2ndcourserad                                       | STRING  |       |                            |                                                                                                                 |
| subsqrx2ndcoursesurg                                      | STRING  |       |                            |                                                                                                                 |
| subsqrx2ndreglnrem                                        | STRING  |       |                            |                                                                                                                 |
| subsqrx2ndscopelnsu                                       | STRING  |       |                            |                                                                                                                 |
| subsqrx2ndsurgoth                                         | STRING  |       |                            |                                                                                                                 |
| subsqrx3rdcoursedate                                      | STRING  | Yes   | Jitter                        |                                                                                                                 |
| subsqrx3rdcourserad                                       | STRING  |       |                            |                                                                                                                 |
| subsqrx3rdcoursesurg                                      | STRING  |       |                            |                                                                                                                 |
| subsqrx3rdreglnrem                                        | STRING  |       |                            |                                                                                                                 |
| subsqrx3rdscopelnsu                                       | STRING  |       |                            |                                                                                                                 |
| subsqrx3rdsurgoth                                         | STRING  |       |                            |                                                                                                                 |
| subsqrx4thcoursedate                                      | STRING  | Yes   | Jitter                        |                                                                                                                 |
| subsqrx4thcourserad                                       | STRING  |       |                            |                                                                                                                 |
| subsqrx4thcoursesurg                                      | STRING  |       |                            |                                                                                                                 |
| subsqrx4thscopelnsu                                       | STRING  |       |                            |                                                                                                                 |
| subsqrx4thsurgoth                                         | STRING  |       |                            |                                                                                                                 |
| subsqrxreconstructdel                                     | STRING  |       |                            |                                                                                                                 |
| surgotherproc1                                            | STRING  |       |                            | [70050](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=70050/)   |
| surgotherproc1description                                 | STRING  |       |                            |                                                                                                                 |
| surgotherproc2                                            | STRING  |       |                            | [70051](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=70051/)   |
| surgotherproc2description                                 | STRING  |       |                            |                                                                                                                 |
| surgotherproc3                                            | STRING  |       |                            | [70052](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=70052/)   |
| surgotherproc3description                                 | STRING  |       |                            |                                                                                                                 |
| surgprimproc1                                             | STRING  |       |                            | [70053](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=70053/)   |
| surgprimproc1description                                  | STRING  |       |                            |                                                                                                                 |
| surgprimproc2                                             | STRING  |       |                            | [70054](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=70054/)   |
| surgprimproc20231                                         | STRING  |       |                            | [70069](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=70069/)   |
| surgprimproc20231description                              | STRING  |       |                            |                                                                                                                 |
| surgprimproc20232                                         | STRING  |       |                            | [70070](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=70070/)   |
| surgprimproc20232description                              | STRING  |       |                            |                                                                                                                 |
| surgprimproc20233                                         | STRING  |       |                            | [70071](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=70071/)   |
| surgprimproc20233description                              | STRING  |       |                            |                                                                                                                 |
| surgprimproc2description                                  | STRING  |       |                            |                                                                                                                 |
| surgprimproc3                                             | STRING  |       |                            | [70055](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=70055/)   |
| surgprimproc3description                                  | STRING  |       |                            |                                                                                                                 |
| totaldose                                                 | STRING  |       |                            | [1533](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1533/)     |
| totaldosedescription                                      | STRING  |       |                            |                                                                                                                 |
| transpendohosp                                            | STRING  |       |                            | [70058](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=70058/)   |
| transpendohospdescription                                 | STRING  |       |                            |                                                                                                                 |
| treatmenthospitalnumberproc1                              | STRING  |       |                            | [70059](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=70059/)   |
| treatmenthospitalnumberproc1description                   | STRING  |       |                            |                                                                                                                 |
| treatmenthospitalnumberproc2                              | STRING  |       |                            | [70060](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=70060/)   |
| treatmenthospitalnumberproc2description                   | STRING  |       |                            |                                                                                                                 |
| treatmenthospitalnumberproc3                              | STRING  |       |                            | [70061](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=70061/)   |
| treatmenthospitalnumberproc3description                   | STRING  |       |                            |                                                                                                                 |

:  {.hover .responsive .sm}

### Columns Description


##### date1stcrsrxcoc

Date 1st Crs RX CoC

##### dateinitialrxseer

Date Initial RX SEER

##### datesurgproc1

Date Surg Proc 1

##### datesurgproc1flag

Date Surg Proc 1 Flag

##### datesurgproc1flagdescription

nan

##### datesurgproc2

Date Surg Proc 2

##### datesurgproc2flag

Date Surg Proc 2 Flag

##### datesurgproc2flagdescription

nan

##### datesurgproc3

Date Surg Proc 3

##### datesurgproc3flag

Date Surg Proc 3 Flag

##### datesurgproc3flagdescription

nan

##### intentoftreatment

Intent of Treatment - Radiation

##### intentoftreatmentdescription

nan

##### nameofradiationdrug

Name of Radiation Drug

##### nameofradiationdrugdescription

nan

##### neoadjuvanttherapy

Neoadjuvant Therapy

##### neoadjuvanttherapydescription

nan

##### neoadjuvtherapyclinicalresponse

Neoadjuvant Therapy-Clinical Response

##### neoadjuvtherapyclinicalresponsedescription

nan

##### neoadjuvtherapytreatmenteffect

Neoadjuvant Therapy-Treatment Effect

##### neoadjuvtherapytreatmenteffectdescription

nan

##### nfcaseentityid

Unique number corresponding to every new neural frame "case" or event

##### nfcasestatus

nan

##### nmtexthemtransplantendocrine

Text-Hem Transplant Endocrine

##### numberphasesofradtxtovolume

Number of Phases of Rad Treatment to this Volume

##### numberphasesofradtxtovolumedescription

nan

##### person_id

Person_id as corresponds to the OMOP dataset

##### phase1doseperfraction

Phase I Dose per Fraction

##### phase1doseperfractiondescription

nan

##### phase1numberoffractions

Phase I Number of Fractions

##### phase1numberoffractionsdescription

nan

##### phase1radiationexternalbeamtech

Phase I Radiation External Beam Planning Tech

##### phase1radiationexternalbeamtechdescription

nan

##### phase1radiationprimarytxvolume

Phase I Radiation Primary Treatment Volume

##### phase1radiationprimarytxvolumedescription

nan

##### phase1radiationtodrainingln

Phase I Radiation to Draining Lymph Nodes

##### phase1radiationtodraininglndescription

nan

##### phase1radiationtreatmentmodality

Phase I Radiation Treatment Modality

##### phase1radiationtreatmentmodalitydescription

nan

##### phase1totaldose

Phase I Total Dose

##### phase1totaldosedescription

nan

##### phase2doseperfraction

Phase II Dose per Fraction

##### phase2doseperfractiondescription

nan

##### phase2numberoffractions

Phase II Number of Fractions

##### phase2numberoffractionsdescription

nan

##### phase2radiationexternalbeamtech

Phase II Radiation External Beam Planning Tech

##### phase2radiationexternalbeamtechdescription

nan

##### phase2radiationprimarytxvolume

Phase II Radiation Primary Treatment Volume

##### phase2radiationprimarytxvolumedescription

nan

##### phase2radiationtodrainingln

Phase II Radiation to Draining Lymph Nodes

##### phase2radiationtodraininglndescription

nan

##### phase2radiationtreatmentmodality

Phase II Radiation Treatment Modality

##### phase2radiationtreatmentmodalitydescription

nan

##### phase2totaldose

Phase II Total Dose

##### phase2totaldosedescription

nan

##### phase3doseperfraction

Phase III Dose per Fraction

##### phase3doseperfractiondescription

nan

##### phase3numberoffractions

Phase III Number of Fractions

##### phase3numberoffractionsdescription

nan

##### phase3radiationexternalbeamtech

Phase III Radiation External Beam Planning Tech

##### phase3radiationexternalbeamtechdescription

nan

##### phase3radiationprimarytxvolume

Phase III Radiation Primary Treatment Volume

##### phase3radiationprimarytxvolumedescription

nan

##### phase3radiationtodrainingln

Phase III Radiation to Draining Lymph Nodes

##### phase3radiationtodraininglndescription

nan

##### phase3radiationtreatmentmodality

Phase III Radiation Treatment Modality

##### phase3radiationtreatmentmodalitydescription

nan

##### phase3totaldose

Phase III Total Dose

##### phase3totaldosedescription

nan

##### radboostdosecgy

RadBoost Dose cGy

##### radboostdosecgydescription

nan

##### radboostrxmodality

RadBoost RX Modality

##### radboostrxmodalitydescription

nan

##### radiationcompletionstatus

Radiation Completion Status

##### radiationlocalcontrolstatus

Radiation Local Control Status

##### radiationlocalcontrolstatusdescription

nan

##### radiationtxdiscontinuedearly

Radiation Treatment Discontinued Early

##### radiationtxdiscontinuedearlydescription

nan

##### radlocationofrx

RadLocation of RX

##### radlocationofrxdescription

nan

##### radnooftreatmentvol

RadNo of Treatment Vol

##### radnooftreatmentvoldescription

nan

##### radregionaldosecgy

RadRegional Dose: cGy

##### radregionaldosecgydescription

nan

##### radregionalrxmodality

RadRegional RX Modality

##### radregionalrxmodalitydescription

nan

##### radtreatmentvolume

RadTreatment Volume

##### radtreatmentvolumedescription

nan

##### readmsamehosp30days

Readm Same Hosp 30 Days

##### readmsamehosp30daysdescription

nan

##### reasonfornoradiation

Reason for No Radiation

##### reasonfornoradiationdescription

nan

##### reasonfornosurgery

Reason for No Surgery

##### reasonfornosurgerydescription

nan

##### rxcodingsystemcurrent

RX Coding SystemCurrent

##### rxcodingsystemcurrentdescription

nan

##### rxdatebrm

RX Date BRM

##### rxdatebrmflag

Rx Date Brm Flag

##### rxdatebrmflagdescription

nan

##### rxdatechemo

RX Date Chemo

##### rxdatechemoflag

Rx Date Chemo Flag

##### rxdatechemoflagdescription

nan

##### rxdatedxstgproc

RX Date DX/Stg Proc

##### rxdatedxstgprocflag

Rx Date Dx/Stg Proc Flag

##### rxdatedxstgprocflagdescription

nan

##### rxdatehormone

RX Date Hormone

##### rxdatehormoneflag

Rx Date Hormone Flag

##### rxdatehormoneflagdescription

nan

##### rxdatemostdefinsurg

RX Date Mst Defn Srg

##### rxdatemostdefinsurgflag

Rx Date Mst Defn Srg Flag

##### rxdatemostdefinsurgflagdescription

nan

##### rxdateother

RX Date Other

##### rxdateotherflag

Rx Date Other Flag

##### rxdateotherflagdescription

nan

##### rxdateradiation

RX Date Radiation

##### rxdateradiationended

RX Date Rad Ended

##### rxdateradiationendedflag

Rx Date Rad Ended Flag

##### rxdateradiationendedflagdescription

nan

##### rxdateradiationflag

Rx Date Radiation Flag

##### rxdateradiationflagdescription

nan

##### rxdatesurgery

RX Date Surgery

##### rxdatesurgeryflag

Rx Date Surgery Flag

##### rxdatesurgeryflagdescription

nan

##### rxdatesurgicaldisch

RX Date Surg Disch

##### rxdatesurgicaldischflag

Rx Date Surg Disch Flag

##### rxdatesurgicaldischflagdescription

nan

##### rxdatesystemic

RX Date Systemic

##### rxdatesystemicflag

Rx Date Systemic Flag

##### rxdatesystemicflagdescription

nan

##### rxdatetranspendo

RX Date Transp Endo

##### rxdatetranspendoflag

RX Date Transp Endo Flag

##### rxdatetranspendoflagdescription

nan

##### rxhospbrm

RX HospBRM

##### rxhospbrmdescription

nan

##### rxhospchemo

RX HospChemo

##### rxhospchemodescription

nan

##### rxhosphormone

RX HospHormone

##### rxhosphormonedescription

nan

##### rxhospother

RX HospOther

##### rxhospotherdescription

nan

##### rxhosppalliativeproc

RX HospPalliative Proc

##### rxhosppalliativeprocdescription

nan

##### rxhospradiation

nan

##### rxhospreconbreast

RX HospRecon Breast

##### rxhospreconbreastdescription

nan

##### rxhospreglnremoved

nan

##### rxhospscopereg9802

RX HospScope Reg 98-02

##### rxhospscopereg9802description

nan

##### rxhospscopereglnsur

RX HospScope Reg LN Sur

##### rxhospscopereglnsurdescription

nan

##### rxhospsurgapp2010

RX HospSurg App 2010

##### rxhospsurgapp2010description

nan

##### rxhospsurgbreast

RX HospSurg Breast

##### rxhospsurgbreastdescription

nan

##### rxhospsurgoth9802

RX HospSurg Oth 98-02

##### rxhospsurgoth9802description

nan

##### rxhospsurgothregdis

RX HospSurg Oth Reg/Dis

##### rxhospsurgothregdisdescription

nan

##### rxhospsurgprimsite

RX HospSurg Prim Site 03-2022

##### rxhospsurgprimsite2023

RX HospSurg Prim Site 2023

##### rxhospsurgprimsite2023description

nan

##### rxhospsurgprimsitedescription

nan

##### rxhospsurgsite9802

RX HospSurg Site 98-02

##### rxhospsurgsite9802description

nan

##### rxsummbrm

RX SummBRM

##### rxsummbrmdescription

nan

##### rxsummchemo

RX SummChemo

##### rxsummchemodescription

nan

##### rxsummdxstgproc

RX SummDX/Stg Proc

##### rxsummdxstgprocdescription

nan

##### rxsummhormone

RX SummHormone

##### rxsummhormonedescription

nan

##### rxsummother

RX SummOther

##### rxsummotherdescription

nan

##### rxsummpalliativeproc

RX SummPalliative Proc

##### rxsummpalliativeprocdescription

nan

##### rxsummradiation

RX SummRadiation

##### rxsummradiationdescription

nan

##### rxsummradtocns

nan

##### rxsummreconbreast

RX SummRecon Breast

##### rxsummreconbreastdescription

nan

##### rxsummreconstruct1st

RX SummReconstruct 1st

##### rxsummreconstruct1stdescription

nan

##### rxsummreglnexamined

RX SummReg LN Examined

##### rxsummreglnexamineddescription

nan

##### rxsummscopereg9802

RX SummScope Reg 98-02

##### rxsummscopereg9802description

nan

##### rxsummscopereglnsur

RX SummScope Reg LN Sur

##### rxsummscopereglnsurdescription

nan

##### rxsummsurgbreast

RX SummSurg Breast

##### rxsummsurgbreastdescription

nan

##### rxsummsurgerytype

nan

##### rxsummsurgicalapproch

RX SummSurgical Approch

##### rxsummsurgicalapprochdescription

nan

##### rxsummsurgicalmargins

RX SummSurgical Margins

##### rxsummsurgicalmarginsdescription

nan

##### rxsummsurgoth9802

RX SummSurg Oth 98-02

##### rxsummsurgoth9802description

nan

##### rxsummsurgothregdis

RX SummSurg Oth Reg/Dis

##### rxsummsurgothregdisdescription

nan

##### rxsummsurgprimsite

RX SummSurg Prim Site 03-2022

##### rxsummsurgprimsite2023

RX SummSurg Prim Site 2023

##### rxsummsurgprimsite2023description

nan

##### rxsummsurgprimsitedescription

nan

##### rxsummsurgradseq

RX SummSurg/Rad Seq

##### rxsummsurgradseqdescription

nan

##### rxsummsurgsite9802

RX SummSurg Site 98-02

##### rxsummsurgsite9802description

nan

##### rxsummsystemicsurseq

RX SummSystemic/Sur Seq

##### rxsummsystemicsurseqdescription

nan

##### rxsummtransplntendocr

RX SummTransplnt/Endocr

##### rxsummtransplntendocrdescription

nan

##### rxsummtreatmentstatus

RX SummTreatment Status

##### rxsummtreatmentstatusdescription

nan

##### rxtextbrm

RX TextBRM

##### rxtextchemo

RX TextChemo

##### rxtexthormone

RX TextHormone

##### rxtextother

RX TextOther

##### rxtextpalliative

Text-Palliative Services

##### rxtextradiation

RX TextRadiation (Beam)

##### rxtextradiationother

RX TextRadiation Other

##### rxtextsurgery

RX TextSurgery

##### rxtextsurgery1

RX Text Surgery 1

##### rxtextsurgery2

RX Text Surgery 2

##### rxtextsurgery3

RX Text Surgery 3

##### stanford_patient_uid

Internal Stanford tracking ID for Neural frame (this is the patient's MRN | DOB)

##### stanford1stcoursechemofacility

Stanford 1st Course Chemo Facility

##### stanford1stcoursechemofacilitydescription

nan

##### stanford1stcoursehormonefacility

Stanford 1st Course Hormone Facility

##### stanford1stcoursehormonefacilitydescription

nan

##### stanford1stcourseimmunofacility

Stanford 1st Course Immuno Facility

##### stanford1stcourseimmunofacilitydescription

nan

##### stanford1stcourseotherrxfacility

Stanford 1st Course Other Rx Facility

##### stanford1stcourseotherrxfacilitydescription

nan

##### stanford1stcoursepalliativefacility

Stanford 1st Course Palliative Facility

##### stanford1stcoursepalliativefacilitydescription

nan

##### stanford1stcourseradiationfacility

Stanford 1st Course Radiation Facility

##### stanford1stcourseradiationfacilitydescription

nan

##### stanford1stcoursesurgeryfacility

Stanford 1st Course Surgery Facility

##### stanford1stcoursesurgeryfacilitydescription

nan

##### stanford1stcoursetransplantendocrinefacility

Stanford 1st Course Transplant Endocrine Facility

##### stanford1stcoursetransplantendocrinefacilitydescription

nan

##### stanfordadditionaltext

Text - Followup/Outcomes

##### stanfordradiationgivenateden

Stanford Radiation Given At EDEN

##### stanfordradiationgivenatedendescription

nan

##### stanfordradiationgivenatseroc

Stanford Radiation Given At SEROC

##### stanfordradiationgivenatserocdescription

nan

##### stanfordrouteofadministrationhormone

Stanford Route Of Administration Hormone

##### stanfordrouteofadministrationhormonedescription

nan

##### stanfordrouteofadministrationimmuno

Stanford Route Of Administration Immuno

##### stanfordrouteofadministrationimmunodescription

nan

##### stanfordsubsequent1chemofacility

Stanford Subsequent 1 Chemo Facility

##### stanfordsubsequent1chemofacilitydescription

nan

##### stanfordsubsequent1hormonefacility

Stanford Subsequent 1 Hormone Facility

##### stanfordsubsequent1hormonefacilitydescription

nan

##### stanfordsubsequent1immunofacility

Stanford Subsequent 1 Immuno Facility

##### stanfordsubsequent1immunofacilitydescription

nan

##### stanfordsubsequent1otherrxfacility

Stanford Subsequent 1 Other Rx Facility

##### stanfordsubsequent1otherrxfacilitydescription

nan

##### stanfordsubsequent1palliativefacility

Stanford Subsequent 1 Palliative Facility

##### stanfordsubsequent1palliativefacilitydescription

nan

##### stanfordsubsequent1radiationfacility

Stanford Subsequent 1 Radiation Facility

##### stanfordsubsequent1radiationfacilitydescription

nan

##### stanfordsubsequent1surgeryfacility

Stanford Subsequent 1 Surgery Facility

##### stanfordsubsequent1surgeryfacilitydescription

nan

##### stanfordsubsequent1transplantendocrinefacility

Stanford Subsequent 1 Transplant Endocrine Facility

##### stanfordsubsequent1transplantendocrinefacilitydescription

nan

##### stanfordsubsequent2chemofacility

Stanford Subsequent 2 Chemo Facility

##### stanfordsubsequent2chemofacilitydescription

nan

##### stanfordsubsequent2hormonefacility

Stanford Subsequent 2 Hormone Facility

##### stanfordsubsequent2hormonefacilitydescription

nan

##### stanfordsubsequent2immunofacility

Stanford Subsequent 2 Immuno Facility

##### stanfordsubsequent2immunofacilitydescription

nan

##### stanfordsubsequent2otherrxfacility

Stanford Subsequent 2 Other Rx Facility

##### stanfordsubsequent2otherrxfacilitydescription

nan

##### stanfordsubsequent2palliativefacility

Stanford Subsequent 2 Palliative Facility

##### stanfordsubsequent2palliativefacilitydescription

nan

##### stanfordsubsequent2radiationfacility

Stanford Subsequent 2 Radiation Facility

##### stanfordsubsequent2radiationfacilitydescription

nan

##### stanfordsubsequent2surgeryfacility

Stanford Subsequent 2 Surgery Facility

##### stanfordsubsequent2surgeryfacilitydescription

nan

##### stanfordsubsequent2transplantendocrinefacility

Stanford Subsequent 2 Transplant Endocrine Facility

##### stanfordsubsequent2transplantendocrinefacilitydescription

nan

##### stanfordsubsequent3chemofacility

Stanford Subsequent 3 Chemo Facility

##### stanfordsubsequent3chemofacilitydescription

nan

##### stanfordsubsequent3hormonefacility

Stanford Subsequent 3 Hormone Facility

##### stanfordsubsequent3hormonefacilitydescription

nan

##### stanfordsubsequent3immunofacility

Stanford Subsequent 3 Immuno Facility

##### stanfordsubsequent3immunofacilitydescription

nan

##### stanfordsubsequent3otherrxfacility

Stanford Subsequent 3 Other Rx Facility

##### stanfordsubsequent3otherrxfacilitydescription

nan

##### stanfordsubsequent3palliativefacility

Stanford Subsequent 3 Palliative Facility

##### stanfordsubsequent3palliativefacilitydescription

nan

##### stanfordsubsequent3radiationfacility

Stanford Subsequent 3 Radiation Facility

##### stanfordsubsequent3radiationfacilitydescription

nan

##### stanfordsubsequent3surgeryfacility

Stanford Subsequent 3 Surgery Facility

##### stanfordsubsequent3surgeryfacilitydescription

nan

##### stanfordsubsequent3transplantendocrinefacility

Stanford Subsequent 3 Transplant Endocrine Facility

##### stanfordsubsequent3transplantendocrinefacilitydescription

nan

##### stanfordtextprotocol

Text-Protocol

##### subsequenttreatmentneeded

nan

##### subsequenttreatmentneededdescription

nan

##### subsequenttreatmenttext

Treatment Protocol

##### subsqrx2ndcoursechemo

nan

##### subsqrx2ndcoursedate

nan

##### subsqrx2ndcourseoth

nan

##### subsqrx2ndcourserad

nan

##### subsqrx2ndcoursesurg

nan

##### subsqrx2ndreglnrem

nan

##### subsqrx2ndscopelnsu

nan

##### subsqrx2ndsurgoth

nan

##### subsqrx3rdcoursedate

nan

##### subsqrx3rdcourserad

nan

##### subsqrx3rdcoursesurg

nan

##### subsqrx3rdreglnrem

nan

##### subsqrx3rdscopelnsu

nan

##### subsqrx3rdsurgoth

nan

##### subsqrx4thcoursedate

nan

##### subsqrx4thcourserad

nan

##### subsqrx4thcoursesurg

nan

##### subsqrx4thscopelnsu

nan

##### subsqrx4thsurgoth

nan

##### subsqrxreconstructdel

nan

##### surgotherproc1

Surg Other Proc 1

##### surgotherproc1description

nan

##### surgotherproc2

Surg Other Proc 2

##### surgotherproc2description

nan

##### surgotherproc3

Surg Other Proc 3

##### surgotherproc3description

nan

##### surgprimproc1

Surg Prim Proc 1

##### surgprimproc1description

nan

##### surgprimproc2

Surg Prim Proc 2

##### surgprimproc20231

Surg Prim Proc 2023 1

##### surgprimproc20231description

nan

##### surgprimproc20232

Surg Prim Proc 2023 2

##### surgprimproc20232description

nan

##### surgprimproc20233

Surg Prim Proc 2023 3

##### surgprimproc20233description

nan

##### surgprimproc2description

nan

##### surgprimproc3

Surg Prim Proc 3

##### surgprimproc3description

nan

##### totaldose

Total Dose

##### totaldosedescription

nan

##### transpendohosp

Transp Endo Hosp

##### transpendohospdescription

nan

##### treatmenthospitalnumberproc1

Treatment Hospital Number Procedure 1

##### treatmenthospitalnumberproc1description

nan

##### treatmenthospitalnumberproc2

Treatment Hospital Number Procedure 2

##### treatmenthospitalnumberproc2description

nan

##### treatmenthospitalnumberproc3

Treatment Hospital Number Procedure 3

##### treatmenthospitalnumberproc3description

nan
