---
title: "NeuralFrame Case Miscellaneous Details"
---

This section includes additional data that may not fit into the other categories, such as demographic information, patient-reported outcomes, and other relevant clinical data.

### Table Columns

| column name                            | type    | phi   | phi-scrubbing operation       | naaccr number                                                                                                   |
|:---------------------------------------|:--------|:------|:------------------------------|:----------------------------------------------------------------------------------------------------------------|
| abstractedby                           | STRING  | Yes   | Del                           | [570](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=570/)       |
| abstractedbydescription                | STRING  | Yes   | Del                           |                                                                                                                 |
| addratdxcity                           | STRING  | Yes   | Del                           |                                                                                                                 |
| addratdxcitydescription                | STRING  | Yes   | Del                           |                                                                                                                 |
| addratdxcountry                        | STRING  |       |                            | [102](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=102/)       |
| addratdxcountrydescription             | STRING  |       |                            |                                                                                                                 |
| addratdxnostreet                       | STRING  | Yes   | Del                           | [2330](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=2330/)     |
| addratdxnostreetdescription            | STRING  | Yes   | Del                           |                                                                                                                 |
| addratdxpostalcode                     | STRING  | Yes   | RedZip                        | [100](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=100/)       |
| addratdxpostalcodedescription          | STRING  |       |                            |                                                                                                                 |
| addratdxstate                          | STRING  |       |                            | [80](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=80/)         |
| addratdxstatedescription               | STRING  |       |                            |                                                                                                                 |
| addratdxsupplementl                    | STRING  |       |                            | [2335](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=2335/)     |
| addrcurrentcity                        | STRING  | Yes   | Del                           | [1810](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1810/)     |
| addrcurrentcountry                     | STRING  |       |                            | [1832](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1832/)     |
| addrcurrentcountrydescription          | STRING  |       |                            |                                                                                                                 |
| addrcurrentcounty                      | STRING  |       |                            |                                                                                                                 |
| addrcurrentnostreet                    | STRING  | Yes   | Del                           | [2350](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=2350/)     |
| addrcurrentpostalcode                  | STRING  | Yes   | RedZip                        | [1830](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1830/)     |
| addrcurrentpostalcodedescription       | STRING  |       |                            |                                                                                                                 |
| addrcurrentstate                       | STRING  |       |                            | [1820](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1820/)     |
| addrcurrentstatedescription            | STRING  |       |                            |                                                                                                                 |
| addrcurrentsupplementl                 | STRING  | Yes   | Del                           | [2355](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=2355/)     |
| ageatdiagnosis                         | STRING  | Yes   | Jitter                        | [230](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=230/)       |
| ageatdiagnosisdescription              | STRING  |       |                            |                                                                                                                 |
| agedecadediagnosis                     | STRING  | Yes   | Jitter                        |                                                                                                                 |
| archivefin                             | STRING  |       |                            | [3100](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=3100/)     |
| archivefindescription                  | STRING  |       |                            |                                                                                                                 |
| birthplacecountry                      | STRING  |       |                            | [254](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=254/)       |
| birthplacecountrydescription           | STRING  |       |                            |                                                                                                                 |
| birthplacestate                        | STRING  |       |                            | [252](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=252/)       |
| birthplacestatedescription             | STRING  |       |                            |                                                                                                                 |
| californiacountyatdx                   | STRING  |       |                            | [23002](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=23002/)   |
| californiacountyatdxdescription        | STRING  |       |                            |                                                                                                                 |
| californiareportingfacility            | STRING  |       |                            | [23001](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=23001/)   |
| californiareportingfacilitydescription | STRING  |       |                            |                                                                                                                 |
| caseassignedto                         | STRING  | Yes   | Del                           | [50070](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=50070/)   |
| caseassignedtodescription              | STRING  | Yes   | Del                           |                                                                                                                 |
| casefindingreviewstatus                | STRING  |       |                            | [50010](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=50010/)   |
| casefindingreviewstatusdescription     | STRING  |       |                            |                                                                                                                 |
| causeofdeath                           | STRING  |       |                            | [1910](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1910/)     |
| causeofdeathdescription                | STRING  |       |                            |                                                                                                                 |
| censusindcode19702000                  | STRING  |       |                            |                                                                                                                 |
| censusocccode19702000                  | STRING  |       |                            |                                                                                                                 |
| contactname                            | STRING  | Yes   | Del                           | [70001](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=70001/)   |
| countyatdx                             | STRING  |       |                            | [90](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=90/)         |
| countyatdxdescription                  | STRING  |       |                            |                                                                                                                 |
| dateofbirth                            | STRING  | Yes   | Jitter                        |                                                                                                                 |
| dcstatefilenumber                      | STRING  | Yes   | Del                           | [2380](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=2380/)     |
| followupcontactcity                    | STRING  |       |                            |                                                                                                                 |
| followupcontactcountry                 | STRING  |       |                            |                                                                                                                 |
| followupcontactnost                    | STRING  | Yes   | Del                           |                                                                                                                 |
| followupcontactpostal                  | STRING  | Yes   | RedZip                        |                                                                                                                 |
| followupcontactstate                   | STRING  |       |                            |                                                                                                                 |
| followupcontactsuppl                   | STRING  |       |                            |                                                                                                                 |
| followuplasttypepatient                | STRING  |       |                            | [70010](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=70010/)   |
| followuplasttypepatientdescription     | STRING  |       |                            |                                                                                                                 |
| followupnexttype                       | STRING  |       |                            | [70012](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=70012/)   |
| followupnexttypedescription            | STRING  |       |                            |                                                                                                                 |
| height                                 | STRING  |       |                            | [9960](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=9960/)     |
| heightdescription                      | STRING  |       |                            |                                                                                                                 |
| hosppatno                              | STRING  | Yes   | Del                           | [70013](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=70013/)   |
| maritalstatusatdx                      | STRING  |       |                            | [150](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=150/)       |
| maritalstatusatdxdescription           | STRING  |       |                            |                                                                                                                 |
| medicarebeneficiaryidentifier          | STRING  | Yes   | Del                           | [2315](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=2315/)     |
| naaccralcohol                          | STRING  |       |                            | [350](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=350/)       |
| naaccralcoholdescription               | STRING  |       |                            |                                                                                                                 |
| naaccrrecordversion                    | STRING  |       |                            | [50](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=50/)         |
| naaccrrecordversiondescription         | STRING  |       |                            |                                                                                                                 |
| naaccrtobacco                          | STRING  |       |                            | [340](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=340/)       |
| naaccrtobaccodescription               | STRING  |       |                            |                                                                                                                 |
| namealias                              | STRING  | Yes   | Del                           | [2280](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=2280/)     |
| namealiasfirst                         | STRING  | Yes   | Del                           | [70016](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=70016/)   |
| namebirthsurname                       | STRING  | Yes   | Del                           | [2232](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=2232/)     |
| namefirst                              | STRING  | Yes   | Del                           | [2240](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=2240/)     |
| namelast                               | STRING  | Yes   | Del                           | [2230](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=2230/)     |
| namemaiden                             | STRING  | Yes   | Del                           |                                                                                                                 |
| namemiddle                             | STRING  | Yes   | Del                           | [2250](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=2250/)     |
| nameprefix                             | STRING  | Yes   | Del                           |                                                                                                                 |
| namespouseparent                       | STRING  | Yes   | Del                           |                                                                                                                 |
| namesuffix                             | STRING  | Yes   | Del                           |                                                                                                                 |
| nfcaseentityid                         | STRING  | Yes   | Stable between Data Refreshes |                                                                                                                 |
| nfcasestatus                           | STRING  |       |                            |                                                                                                                 |
| nfcreatedat                            | STRING  | Yes   | Jitter                        |                                                                                                                 |
| nfupdatedat                            | STRING  | Yes   | Jitter                        |                                                                                                                 |
| overridespanishbpl                     | STRING  |       |                            | [70023](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=70023/)   |
| overridespanishbpldescription          | STRING  |       |                            |                                                                                                                 |
| patientsystemidhosp                    | STRING  |       |                            | [21](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=21/)         |
| patnocontact                           | STRING  |       |                            | [70024](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=70024/)   |
| patnocontactdescription                | STRING  |       |                            |                                                                                                                 |
| paymentsourcetext                      | STRING  |       |                            | [70026](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=70026/)   |
| paysource2                             | STRING  |       |                            | [70025](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=70025/)   |
| paysource2description                  | STRING  |       |                            |                                                                                                                 |
| person_id                              | INTEGER | Yes   | Stable between Data Refreshes |                                                                                                                 |
| placeofdeath                           | STRING  | Yes   | Del                           |                                                                                                                 |
| placeofdeathcountry                    | STRING  |       |                            | [1944](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1944/)     |
| placeofdeathcountrydescription         | STRING  |       |                            |                                                                                                                 |
| placeofdeathstate                      | STRING  |       |                            | [1942](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=1942/)     |
| placeofdeathstatedescription           | STRING  |       |                            |                                                                                                                 |
| primarypayeratdx                       | STRING  |       |                            | [630](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=630/)       |
| primarypayeratdxdescription            | STRING  |       |                            |                                                                                                                 |
| race1                                  | STRING  |       |                            | [160](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=160/)       |
| race1description                       | STRING  |       |                            |                                                                                                                 |
| race2                                  | STRING  |       |                            | [161](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=161/)       |
| race2description                       | STRING  |       |                            |                                                                                                                 |
| race3                                  | STRING  |       |                            | [162](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=162/)       |
| race3description                       | STRING  |       |                            |                                                                                                                 |
| race4                                  | STRING  |       |                            | [163](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=163/)       |
| race4description                       | STRING  |       |                            |                                                                                                                 |
| race5                                  | STRING  |       |                            | [164](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=164/)       |
| race5description                       | STRING  |       |                            |                                                                                                                 |
| racecodingsyscurrent                   | STRING  |       |                            | [170](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=170/)       |
| racecodingsyscurrentdescription        | STRING  |       |                            |                                                                                                                 |
| racecodingsysoriginal                  | STRING  |       |                            | [180](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=180/)       |
| racecodingsysoriginaldescription       | STRING  |       |                            |                                                                                                                 |
| reasoncasenotsubmittedstate            | STRING  |       |                            | [50014](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=50014/)   |
| reasoncasenr                           | STRING  |       |                            |                                                                                                                 |
| reasoncasenrdescription                | STRING  |       |                            |                                                                                                                 |
| recordtype                             | STRING  |       |                            | [10](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=10/)         |
| recordtypedescription                  | STRING  |       |                            |                                                                                                                 |
| registryid                             | STRING  |       |                            | [40](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=40/)         |
| registryiddescription                  | STRING  |       |                            |                                                                                                                 |
| registrytype                           | STRING  |       |                            | [30](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=30/)         |
| registrytypedescription                | STRING  |       |                            |                                                                                                                 |
| religion                               | STRING  |       |                            | [260](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=260/)       |
| religiondescription                    | STRING  |       |                            |                                                                                                                 |
| reportingfacility                      | STRING  |       |                            | [540](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=540/)       |
| reportingfacilitydescription           | STRING  |       |                            |                                                                                                                 |
| researchthisfacility                   | STRING  |       |                            | [100048](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=100048/) |
| researchthisfacilitydescription        | STRING  |       |                            |                                                                                                                 |
| sex                                    | STRING  |       |                            | [220](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=220/)       |
| sexdescription                         | STRING  |       |                            |                                                                                                                 |
| socialsecuritynumber                   | STRING  | Yes   | Del                           | [2320](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=2320/)     |
| socialsecuritynumberdescription        | STRING  | Yes   | Del                           |                                                                                                                 |
| spanishhispanicorigin                  | STRING  |       |                            | [190](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=190/)       |
| spanishhispanicorigindescription       | STRING  |       |                            |                                                                                                                 |
| ssnsuffix                              | STRING  | Yes   | Del                           | [70048](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=70048/)   |
| stanford_patient_uid                   | STRING  | Yes   | Del                           |                                                                                                                 |
| stateexportflag                        | STRING  |       |                            | [50080](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=50080/)   |
| stateexportflagdescription             | STRING  |       |                            |                                                                                                                 |
| telephone                              | STRING  | Yes   | Del                           | [2360](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=2360/)     |
| telephonedescription                   | STRING  | Yes   | Del                           |                                                                                                                 |
| textusualindustry                      | STRING  | Yes   | TiDE                          | [320](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=320/)       |
| textusualoccupation                    | STRING  | Yes   | TiDE                          |                                                                                                                 |
| textusualoccupation                    | STRING  | Yes   | Del                           | [310](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=310/)       |
| tobaccousecigarettes                   | STRING  |       |                            | [9965](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=9965/)     |
| tobaccousecigarettesdescription        | STRING  |       |                            |                                                                                                                 |
| tobaccousenos                          | STRING  |       |                            | [9968](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=9968/)     |
| tobaccousenosdescription               | STRING  |       |                            |                                                                                                                 |
| tobaccouseothersmoke                   | STRING  |       |                            | [9966](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=9966/)     |
| tobaccouseothersmokedescription        | STRING  |       |                            |                                                                                                                 |
| tobaccousesmokeless                    | STRING  |       |                            | [9967](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=9967/)     |
| tobaccousesmokelessdescription         | STRING  |       |                            |                                                                                                                 |
| tobaccousesmokingstatus                | STRING  |       |                            | [344](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=344/)       |
| tobaccousesmokingstatusdescription     | STRING  |       |                            |                                                                                                                 |
| weight                                 | STRING  |       |                            | [9961](https://apps.naaccr.org/data-dictionary/data-dictionary/version=25/data-item-view/item-number=9961/)     |
| weightdescription                      | STRING  |       |                            |                                                                                                                 |

:  {.hover .responsive .sm}

### Columns Description


##### abstractedby

Abstracted By

##### abstractedbydescription

nan

##### addratdxcity

nan

##### addratdxcitydescription

nan

##### addratdxcountry

Addr at DX–Country

##### addratdxcountrydescription

nan

##### addratdxnostreet

Addr at DX–No & Street

##### addratdxnostreetdescription

nan

##### addratdxpostalcode

Addr at DX–Postal Code

##### addratdxpostalcodedescription

nan

##### addratdxstate

Addr at DX–State

##### addratdxstatedescription

nan

##### addratdxsupplementl

Addr at DX–Supplementl

##### addrcurrentcity

Addr Current–City

##### addrcurrentcountry

Addr Current–Country

##### addrcurrentcountrydescription

nan

##### addrcurrentcounty

nan

##### addrcurrentnostreet

Addr Current–No & Street

##### addrcurrentpostalcode

Addr Current–Postal Code

##### addrcurrentpostalcodedescription

nan

##### addrcurrentstate

Addr Current–State

##### addrcurrentstatedescription

nan

##### addrcurrentsupplementl

Addr Current–Supplementl

##### ageatdiagnosis

Age at Diagnosis

##### ageatdiagnosisdescription

nan

##### agedecadediagnosis

Decade of Diagnosis

##### archivefin

Archive FIN

##### archivefindescription

nan

##### birthplacecountry

Birthplace–Country

##### birthplacecountrydescription

nan

##### birthplacestate

Birthplace–State

##### birthplacestatedescription

nan

##### californiacountyatdx

California County At Dx

##### californiacountyatdxdescription

nan

##### californiareportingfacility

California Reporting Facility

##### californiareportingfacilitydescription

nan

##### caseassignedto

Case Assigned To

##### caseassignedtodescription

nan

##### casefindingreviewstatus

Case Finding Review Status

##### casefindingreviewstatusdescription

nan

##### causeofdeath

Cause of Death

##### causeofdeathdescription

nan

##### censusindcode19702000

nan

##### censusocccode19702000

nan

##### contactname

Contact Name

##### countyatdx

County at DX Reported

##### countyatdxdescription

nan

##### dcstatefilenumber

DC State File Number

##### dateofbirth

Date of Birth 

##### followupcontactcity

nan

##### followupcontactcountry

nan

##### followupcontactnost

nan

##### followupcontactpostal

nan

##### followupcontactstate

nan

##### followupcontactsuppl

nan

##### followuplasttypepatient

Follow-Up Last Type Patient

##### followuplasttypepatientdescription

nan

##### followupnexttype

Follow-Up Next Type

##### followupnexttypedescription

nan

##### height

Height

##### heightdescription

nan

##### hosppatno

Hosp Pat No

##### maritalstatusatdx

Marital Status at DX

##### maritalstatusatdxdescription

nan

##### medicarebeneficiaryidentifier

Medicare Beneficiary Identifier

##### naaccralcohol

Alcohol History

##### naaccralcoholdescription

nan

##### naaccrrecordversion

NAACCR Record Version

##### naaccrrecordversiondescription

nan

##### naaccrtobacco

Tobacco History

##### naaccrtobaccodescription

nan

##### namealias

Name–Alias

##### namealiasfirst

Name–Alias First

##### namebirthsurname

Name–Birth Surname

##### namefirst

Name–First

##### namelast

Name–Last

##### namemaiden

nan

##### namemiddle

Name–Middle

##### nameprefix

nan

##### namespouseparent

nan

##### namesuffix

nan

##### nfcaseentityid

Unique number corresponding to every new neural frame "case" or event

##### nfcasestatus

nan

##### nfcreatedat

date created

##### nfupdatedat

date created

##### overridespanishbpl

Over-ride Spanish BPL

##### overridespanishbpldescription

nan

##### patientsystemidhosp

Patient System ID-Hosp

##### patnocontact

Pat No Contact

##### patnocontactdescription

nan

##### paymentsourcetext

Payment Source Text

##### paysource2

Pay Source 2

##### paysource2description

nan

##### person_id

Person_id as corresponds to the OMOP dataset

##### placeofdeath

Place of Death

##### placeofdeathcountry

Place of Death–Country

##### placeofdeathcountrydescription

nan

##### placeofdeathstate

Place of Death–State

##### placeofdeathstatedescription

nan

##### primarypayeratdx

Primary Payer at DX

##### primarypayeratdxdescription

nan

##### race1

Race 1

##### race1description

nan

##### race2

Race 2

##### race2description

nan

##### race3

Race 3

##### race3description

nan

##### race4

Race 4

##### race4description

nan

##### race5

Race 5

##### race5description

nan

##### racecodingsyscurrent

Race Coding Sys–Current

##### racecodingsyscurrentdescription

nan

##### racecodingsysoriginal

Race Coding Sys–Original

##### racecodingsysoriginaldescription

nan

##### reasoncasenotsubmittedstate

Reason Case Not Submitted to State

##### reasoncasenr

nan

##### reasoncasenrdescription

nan

##### recordtype

Record Type

##### recordtypedescription

nan

##### registryid

Registry ID

##### registryiddescription

nan

##### registrytype

Registry Type

##### registrytypedescription

nan

##### religion

Religion

##### religiondescription

nan

##### reportingfacility

Reporting Facility

##### reportingfacilitydescription

nan

##### researchthisfacility

Research This Facility

##### researchthisfacilitydescription

nan

##### sex

Sex

##### sexdescription

nan

##### socialsecuritynumber

Social Security Number

##### socialsecuritynumberdescription

nan

##### spanishhispanicorigin

Spanish/Hispanic Origin

##### spanishhispanicorigindescription

nan

##### ssnsuffix

SSN Suffix

##### stanford_patient_uid

Internal Stanford tracking ID for Neural frame 

##### stateexportflag

State Export Flag

##### stateexportflagdescription

nan

##### telephone

Telephone

##### telephonedescription

nan

##### textusualindustry

Text–Usual Industry

##### textusualoccupation

nan

##### textusualoccupation

Text–Usual Occupation

##### tobaccousecigarettes

Tobacco Use Cigarettes

##### tobaccousecigarettesdescription

nan

##### tobaccousenos

Tobacco Use NOS

##### tobaccousenosdescription

nan

##### tobaccouseothersmoke

Tobacco Use Other Smoke

##### tobaccouseothersmokedescription

nan

##### tobaccousesmokeless

Tobacco Use Smokeless

##### tobaccousesmokelessdescription

nan

##### tobaccousesmokingstatus

Tobacco Use Smoking Status

##### tobaccousesmokingstatusdescription

nan

##### weight

Weight

##### weightdescription

nan
