---
title: "CARE_SITE"
---

Standarized Health System Data Tables

### Table Columns

| field                                               | type    | phi   | required   |
|:----------------------------------------------------|:--------|:------|:-----------|
| care_site_id                                        | INTEGER |       | Yes        |
| care_site_name                                      | STRING  |       | No         |
| place_of_service_concept_id                         | INTEGER |       | Yes        |
| location_id                                         | INTEGER |       | No         |
| care_site_source_value                              | STRING  |       | No         |
| place_of_service_source_value                       | STRING  |       | No         |
| trace_id (Stanford construct for traceability)      | STRING  |       | No         |
| unit_id (Stanford construct for traceability)       | STRING  |       | No         |
| load_table_id (Stanford construct for traceability) | STRING  |       | No         |

:  {.hover .responsive}

### Columns Description


##### care_site_id

A unique identifier for each Care Site.

##### care_site_name

The verbatim description or name of the Care Site as in data source

##### place_of_service_concept_id

A foreign key that refers to a Place of Service Concept ID in the Standardized Vocabularies.

##### location_id

A foreign key to the geographic Location in the LOCATION table, where the detailed address information is stored.

##### care_site_source_value

The identifier for the Care Site in the source data, stored here for reference.

##### place_of_service_source_value

The source code for the Place of Service as it appears in the source data, stored here for reference.

##### trace_id (stanford construct for traceability) 

A json string with the primary keys of the table in Clarity where most of the information for a given row is sourced. 

##### unit_id (stanford construct for traceability) 

Is a reference for the position in the ETL code responsible for bringing in this row level data

##### load_table_id (stanford construct for traceability) 

Is the name of the primary Clarity table in Clarity where most of the information for a given row is sourced.Is a Stanford specific column.
