---
title: "concept_class"
---

Vocabulary Tables

### Table Columns

| field                                               | type    | required   | phi   |   phi scrubbing operation |
|:----------------------------------------------------|:--------|:-----------|:------|--------------------------:|
| concept_class_id                                    | STRING  | Yes        |       |                        |
| concept_class_name                                  | STRING  | Yes        |       |                        |
| concept_class_concept_id                            | INTEGER | Yes        |       |                        |
| load_table_id (Stanford construct for traceability) | STRING  | No         |       |                        |
| load_row_id (Stanford construct for traceability)   | STRING  | No         |       |                        |

:  {.hover .responsive .sm}

### Columns Description


##### concept_class_id

A unique key for each class.

##### concept_class_name

The name describing the Concept Class, e.g. "Clinical Finding", "Ingredient", etc.

##### concept_class_concept_id

A foreign key that refers to an identifier in the CONCEPT table for the unique Concept Class the record belongs to.

##### load_table_id (stanford construct for traceability) 

A json string with the primary keys of the table in Clarity where most of the information for a given row is sourced

##### load_row_id (stanford construct for traceability)

A reference to the position in the ETL code responsible for bringing in this row level data
