---
title: "concept_ancestor"
---

Vocabulary Tables

### Table Columns

| field                                               | type    | phi   | required   |
|:----------------------------------------------------|:--------|:------|:-----------|
| ancestor_concept_id                                 | INTEGER |       | Yes        |
| descendant_concept_id                               | INTEGER |       | Yes        |
| min_levels_of_separation                            | INTEGER |       | Yes        |
| max_levels_of_separation                            | INTEGER |       | Yes        |
| load_table_id (Stanford construct for traceability) | STRING  |       | No         |
| load_row_id (Stanford construct for traceability)   | STRING  |       | No         |

:  {.hover .responsive .sm}

### Columns Description


##### ancestor_concept_id

A foreign key to the concept in the concept table for the higher-level concept that forms the ancestor in the relationship.

##### descendant_concept_id

A foreign key to the concept in the concept table for the lower-level concept that forms the descendant in the relationship.

##### min_levels_of_separation

The minimum separation in number of levels of hierarchy between ancestor and descendant concepts. This is an attribute that is used to simplify hierarchic analysis.

##### max_levels_of_separation

The maximum separation in number of levels of hierarchy between ancestor and descendant concepts. This is an attribute that is used to simplify hierarchic analysis.

##### load_table_id (stanford construct for traceability)

A json string with the primary keys of the table in Clarity where most of the information for a given row is sourced

##### load_row_id (stanford construct for traceability)

A reference to the position in the ETL code responsible for bringing in this row level data
