---
title: "death"
---

Standard Clinical Data Table

### Table Columns

| field                                                      | type   | phi   | required   |
|:-----------------------------------------------------------|:-------|:------|:-----------|
| person_id                                                  |        |       | Yes        |
| death_date                                                 |        | Yes   | Yes        |
| death_datetime                                             |        | Yes   | No         |
| death_type_concept_id                                      |        |       | No         |
| cause_concept_id                                           |        |       | No         |
| cause_source_value                                         |        |       | No         |
| cause_source_concept_id                                    |        |       | No         |
| trace_id (Stanford construct for traceability)             |        | Yes   | No         |
| unit_id (Stanford construct for traceability)              |        |       | No         |
| load_table_id (Stanford construct for traceability)        |        |       | No         |
| _death_date_external (Stanford construct for traceability) |        | Yes   | No         |

:  {.hover .responsive .sm}

### Columns Description


##### person_id



##### death_date



##### death_datetime



##### death_type_concept_id



##### cause_concept_id



##### cause_source_value



##### cause_source_concept_id



##### trace_id (stanford construct for traceability) 



##### unit_id (stanford construct for traceability) 



##### load_table_id (stanford construct for traceability) 



##### _death_date_external (stanford construct for traceability) 


