---
title: "DEVICE_EXPOSURE"
---

## Description

Standard Clinical Data Table

The following columns are available in this table:


### DEVICE_EXPOSURE_ID


- **Required:** Yes
- **Contains PHI:** Yes
- **Data Type:** INTEGER
- **Description:** A system-generated unique identifier for each Device Exposure.



### PERSON_ID


- **Required:** Yes
- **Contains PHI:** Yes
- **Data Type:** INTEGER
- **Description:** A foreign key identifier to the Person who is subjected to the Device. The demographic details of that Person are stored in the PERSON table.



### DEVICE_CONCEPT_ID


- **Required:** Yes
- **Contains PHI:** 
- **Data Type:** INTEGER
- **Description:** A foreign key that refers to a Standard Concept identifier in the Standardized Vocabularies belonging to the 'Device' domain.



### DEVICE_EXPOSURE_START_DATE


- **Required:** No
- **Contains PHI:** Yes
- **Data Type:** DATE
- **Description:** The date the Device or supply was applied or used.



### DEVICE_EXPOSURE_START_DATETIME


- **Required:** Yes
- **Contains PHI:** Yes
- **Data Type:** DATETIME
- **Description:** The date and time the Device or supply was applied or used.



### DEVICE_EXPOSURE_END_DATE


- **Required:** No
- **Contains PHI:** Yes
- **Data Type:** DATE
- **Description:** The date use of the Device or supply was ceased.



### DEVICE_EXPOSURE_END_DATETIME


- **Required:** No
- **Contains PHI:** Yes
- **Data Type:** DATETIME
- **Description:** The date and time use of the Device or supply was ceased.



### DEVICE_TYPE_CONCEPT_ID


- **Required:** Yes
- **Contains PHI:** 
- **Data Type:** INTEGER
- **Description:** This field can be used to determine the provenance of the record, as in whether the condition was from an EHR system, insurance claim, registry, or other sources.



### UNIQUE_DEVICE_ID


- **Required:** No
- **Contains PHI:** 
- **Data Type:** STRING
- **Description:** A UDI or equivalent identifying the instance of the Device used in the Person.



### QUANTITY


- **Required:** No
- **Contains PHI:** 
- **Data Type:** INTEGER
- **Description:** The number of individual Devices used in the exposure.



### PROVIDER_ID


- **Required:** No
- **Contains PHI:** Yes
- **Data Type:** INTEGER
- **Description:** A foreign key to the provider in the PROVIDER table who initiated or administered the Device.



### VISIT_OCCURRENCE_ID


- **Required:** No
- **Contains PHI:** Yes
- **Data Type:** INTEGER
- **Description:** A foreign key to the visit in the VISIT_OCCURRENCE table during which the Device was used.



### VISIT_DETAIL_ID


- **Required:** No
- **Contains PHI:** Yes
- **Data Type:** INTEGER
- **Description:** A foreign key to the visit detail record in the VISIT_DETAIL table during which the Device was used.



### DEVICE_SOURCE_VALUE


- **Required:** No
- **Contains PHI:** 
- **Data Type:** STRING
- **Description:** The source code for the Device as it appears in the source data. This code is mapped to a Standard Device Concept in the Standardized Vocabularies and the original code is stored here for reference.



### DEVICE_SOURCE_CONCEPT_ID


- **Required:** Yes
- **Contains PHI:** 
- **Data Type:** INTEGER
- **Description:** A foreign key to a Device Concept that refers to the code used in the source.



### TRACE_ID (STANFORD CONSTRUCT FOR TRACEABILITY) 


- **Required:** No
- **Contains PHI:** Yes
- **Data Type:** STRING
- **Description:** A json string with the primary keys of the table in Clarity where most of the information for a given row is sourced



### UNIT_ID (STANFORD CONSTRUCT FOR TRACEABILITY) 


- **Required:** No
- **Contains PHI:** 
- **Data Type:** STRING
- **Description:** Is a reference to the position in the ETL code resposible for bringing in this row data



### LOAD_TABLE_ID (STANFORD CONSTRUCT FOR TRACEABILITY) 


- **Required:** No
- **Contains PHI:** 
- **Data Type:** STRING
- **Description:** Is the name of the primary Clarity table in Clarity where most of the information for a given row is sourced


