---
title: "DOMAIN"
---

## Description

Vocabulary Tables

The following columns are available in this table:


### DOMAIN_ID


- **Required:** Yes
- **Contains PHI:** 
- **Data Type:** STRING
- **Description:** A unique key for each domain.



### DOMAIN_NAME


- **Required:** Yes
- **Contains PHI:** 
- **Data Type:** STRING
- **Description:** The name describing the Domain, e.g. "Condition", "Procedure", "Measurement" etc.



### DOMAIN_CONCEPT_ID


- **Required:** Yes
- **Contains PHI:** 
- **Data Type:** INTEGER
- **Description:** A Concept representing the Domain Concept the DOMAIN record belongs to.            



### LOAD_TABLE_ID


- **Required:** No
- **Contains PHI:** 
- **Data Type:** STRING
- **Description:** Is the name of the primary Clarity table in Clarity where most of the information for a given row is sourced



### LOAD_ROW_ID


- **Required:** No
- **Contains PHI:** 
- **Data Type:** STRING
- **Description:** A reference to the position in the ETL code responsible for bringing in this row level data


