---
title: "DRUG_ERA"
---

## Description

Standardized Derived Elements

The following columns are available in this table:


### DRUG_ERA_ID


- **Required:** Yes
- **Contains PHI:** 
- **Data Type:** INTEGER
- **Description:** A unique identifier for each Drug Era.



### PERSON_ID


- **Required:** Yes
- **Contains PHI:** 
- **Data Type:** INTEGER
- **Description:** A foreign key identifier to the Person who is subjected to the drug during the Drug Era. The demographic details of that Person are stored in the PERSON table.



### DRUG_CONCEPT_ID


- **Required:** Yes
- **Contains PHI:** 
- **Data Type:** INTEGER
- **Description:** A foreign key that refers to a Standard Concept identifier in the Standardized Vocabularies for the Ingredient Concept.



### DRUG_ERA_START_DATE


- **Required:** Yes
- **Contains PHI:** Yes
- **Data Type:** DATETIME
- **Description:** The start date for the Drug Era constructed from the individual instances of Drug Exposures. It is the start date of the very first chronologically recorded instance of conutilization of a Drug.



### DRUG_ERA_END_DATE


- **Required:** Yes
- **Contains PHI:** Yes
- **Data Type:** DATETIME
- **Description:** The end date for the drug era constructed from the individual instance of drug exposures. It is the end date of the final continuously recorded instance of utilization of a drug.



### DRUG_EXPOSURE_COUNT


- **Required:** No
- **Contains PHI:** 
- **Data Type:** INTEGER
- **Description:** The number of individual Drug Exposure occurrences used to construct the Drug Era.



### GAP_DAYS


- **Required:** No
- **Contains PHI:** 
- **Data Type:** INTEGER
- **Description:** The number of days that are not covered by drug_exposure records that were used to make up the era record.



### TRACE_ID (STANFORD CONSTRUCT FOR TRACEABILITY) 


- **Required:** No
- **Contains PHI:** Yes
- **Data Type:** STRING
- **Description:** A json string with the primary keys of the table in Clarity where most of the information for a given row is sourced



### UNIT_ID (STANFORD CONSTRUCT FOR TRACEABILITY) 


- **Required:** No
- **Contains PHI:** 
- **Data Type:** STRING
- **Description:** Is a reference for the position in the ETL code responsible for bringing in this row data



### LOAD_TABLE_ID (STANFORD CONSTRUCT FOR TRACEABILITY) 


- **Required:** No
- **Contains PHI:** 
- **Data Type:** STRING
- **Description:** Is the name of the primary Clarity table in Clarity where most of the information for a given row is sourced


