---
title: "LOCATION"
---

Standarized Health System Data Tables

### Table Columns

| field                                               | type    | phi   | required   |
|:----------------------------------------------------|:--------|:------|:-----------|
| location_id                                         | INTEGER | No    | Yes        |
| address_1                                           | STRING  | Yes   | No         |
| address_2                                           | STRING  | Yes   | No         |
| city                                                | STRING  | Yes   | No         |
| state                                               | STRING  | Yes   | No         |
| zip                                                 | STRING  | Yes   | No         |
| county                                              | STRING  | No    | No         |
| location_source_value                               | STRING  | Yes   | No         |
| unit_id (Stanford construct for traceability)       | STRING  | No    | No         |
| load_table_id (Stanford construct for traceability) | STRING  | No    | No         |
| _census_block_group (available only at Stanford)    | STRING  | Yes   | No         |
| latitude (available only at Stanford)               | FLOAT   | Yes   | No         |
| longitude (available only at Stanford)              | FLOAT   | Yes   | No         |

:  {.hover .responsive}

### Columns Description


##### location_id

A unique identifier for each geographic location.

##### address_1

The address field 1, typically used for the street address, as it appears in the source data.

##### address_2

The address field 2, typically used for additional detail such as buildings, suites, floors, as it appears in the source data.

##### city

The city field as it appears in the source data.

##### state

The state field as it appears in the source data.

##### zip

The 5 digit zip or postal code of the locatin address

##### county

The name of the county.

##### location_source_value

The MRN|DOB of the person this location corresponds to

##### unit_id (stanford construct for traceability) 

Is a reference for the position in the ETL code responsible for bringing in this row level data

##### load_table_id (stanford construct for traceability) 

A json string with the primary keys of the table in Clarity where most of the information for a given row is sourced

##### _census_block_group (available only at stanford)

The census block group as indicated by United States Census Bureau API for this address location

##### latitude (available only at stanford)

latitude of the address if available

##### longitude (available only at stanford)

longitude of the address if available
