---
title: "OBSERVATION_PERIOD"
---

Standard Clinical Data Table

### Table Columns

| field                                               | type    | phi   | required   |
|:----------------------------------------------------|:--------|:------|:-----------|
| observation_period_id                               | INTEGER |       | Yes        |
| person_id                                           | INTEGER |       | Yes        |
| observation_period_start_date                       | DATE    | Yes   | Yes        |
| observation_period_end_date                         | DATE    | Yes   | Yes        |
| period_type_concept_id                              | INTEGER |       | Yes        |
| trace_id (Stanford construct for traceability)      | STRING  |       | No         |
| unit_id (Stanford construct for traceability)       | STRING  |       | No         |
| load_table_id (Stanford construct for traceability) | STRING  |       | No         |

:  {.hover .responsive}

### Columns Description


##### observation_period_id

A unique identifier for each observation period. A Person can have multiple discrete Observation Periods which are identified by the Observation_Period_Id.

##### person_id

A foreign key identifier to the person for whom the observation period is defined. The demographic details of that person are stored in the person table.

##### observation_period_start_date

The start date of the observation period for which data are available from the data source.

##### observation_period_end_date

The end date of the observation period for which data are available from the data source.

##### period_type_concept_id

This field. stores the provenance of the Observation Period as in whether the period was determined from an insurance enrollment file, EHR healthcare encounters, or other sources.      

##### trace_id (stanford construct for traceability) 

A json string with the primary keys of the table in Clarity where most of the information for a given row is sourced

##### unit_id (stanford construct for traceability) 

Is a reference for the position in the ETL code resposible for bringing in this row data

##### load_table_id (stanford construct for traceability) 

Is the name of the primary Clarity table in Clarity where most of the information for a given row is sourced
