---
title: "RELATIONSHIP"
---

Vocabulary Tables

### Table Columns

| field                                               | type    | phi   | required   |
|:----------------------------------------------------|:--------|:------|:-----------|
| relationship_id                                     | STRING  |       | Yes        |
| relationship_name                                   | STRING  |       | Yes        |
| is_hierarchical                                     | STRING  |       | Yes        |
| defines_ancestry                                    | STRING  |       | Yes        |
| reverse_relationship_id                             | STRING  |       | Yes        |
| relationship_concept_id                             | INTEGER |       | Yes        |
| load_table_id (Stanford construct for traceability) | STRING  |       | No         |
| load_row_id (Stanford construct for traceability)   | STRING  |       | No         |

:  {.hover .responsive}

### Columns Description


##### relationship_id

The type of relationship captured by the relationship record.

##### relationship_name

The text that describes the relationship type.

##### is_hierarchical

Defines whether a relationship defines concepts into classes or hierarchies. Values are 1 for hierarchical relationship or 0 if not.

##### defines_ancestry

Defines whether a hierarchical relationship contributes to the concept_ancestor table. These are subsets of the hierarchical relationships. Valid values are 1 or 0.

##### reverse_relationship_id

The identifier for the relationship used to define the reverse relationship between two concepts.

##### relationship_concept_id

A foreign key that refers to an identifier in the CONCEPT table for the unique relationship concept.

##### load_table_id (stanford construct for traceability)

A json string with the primary keys of the table in Clarity where most of the information for a given row is sourced

##### load_row_id (stanford construct for traceability)

A reference to the position in the ETL code responsible for bringing in this row level data
