---
title: "visit_detail"
---

Standard Clinical Data Table 

### Table Columns

| field                                               | type     | phi   | required   |
|:----------------------------------------------------|:---------|:------|:-----------|
| visit_detail_id                                     | INTEGER  |       | Yes        |
| person_id                                           | INTEGER  |       | Yes        |
| visit_detail_concept_id                             | INTEGER  |       | Yes        |
| visit_detail_start_date                             | DATE     | Yes   | No         |
| visit_detail_start_datetime                         | DATETIME | Yes   | Yes        |
| visit_detail_end_date                               | DATE     | Yes   | No         |
| visit_detail_end_datetime                           | DATETIME | Yes   | Yes        |
| visit_detail_type_concept_id                        | INTEGER  |       | Yes        |
| provider_id                                         | INTEGER  |       | No         |
| care_site_id                                        | INTEGER  |       | No         |
| visit_detail_source_value                           | STRING   | Yes   | No         |
| visit_detail_source_concept_id                      | INTEGER  |       | Yes        |
| admitted_from_source_value                          | STRING   | Yes   | No         |
| admitted_from_concept_id                            | INTEGER  |       | Yes        |
| discharge_to_source_value                           | STRING   | Yes   | No         |
| discharge_to_concept_id                             | INTEGER  |       | Yes        |
| preceding_visit_detail_id                           | INTEGER  |       | No         |
| visit_detail_parent_id                              | INTEGER  |       | No         |
| visit_occurrence_id                                 | INTEGER  |       | Yes        |
| trace_id (Stanford construct for traceability)      | STRING   | Yes   | No         |
| unit_id (Stanford construct for traceability)       | STRING   |       | No         |
| load_table_id (Stanford construct for traceability) | STRING   |       | No         |

:  {.hover .responsive .sm}

### Columns Description


##### visit_detail_id

A unique identifier for each Person's visit or encounter at a healthcare provider.

##### person_id

A foreign key identifier to the Person for whom the visit is recorded. The demographic details of that Person are stored in the PERSON table.

##### visit_detail_concept_id

This field contains a concept id representing the kind of visit detail, like inpatient or outpatient. All concepts in this field should be standard and belong to the Visit domain.

##### visit_detail_start_date

The start date of the visit.

##### visit_detail_start_datetime

The date and time when the visit started. This defaults to 00:00:00 (midnight) if no time information is available. 

##### visit_detail_end_date

The end date of the visit. If this is a one-day visit the end date should match the start date.

##### visit_detail_end_datetime

The date and time when the visit ended.This defaults to 00:00:00 (midnight) if no time information is available.

##### visit_detail_type_concept_id

Use this field to understand the provenance of the visit detail record, or where the record comes from.

##### provider_id

A foreign key to the provider in the provider table who was associated with the visit.

##### care_site_id

A foreign key to the care site in the care site table that was visited.

##### visit_detail_source_value

The source ID for the visit as it appears in the source data; this corresponds to the Epic Clarity pat_enc_csn_id for STARR-OMOP.

##### visit_detail_source_concept_id

A foreign key to a Concept that repersents a distinct combination of the following three variables:  ADT patient class, hospital admission type, and encounter type. One or more of these variables may be null for any given visit.

##### admitted_from_source_value

The source code for the admitting source as it appears in the source data.

##### admitted_from_concept_id

A foreign key to the predefined concept in the 'Place of Service' Vocabulary reflecting the admitting source for a visit.

##### discharge_to_source_value

The source code for the discharge disposition as it appears in the source data.

##### discharge_to_concept_id

A foreign key to the predefined concept in the 'Place of Service' Vocabulary reflecting the discharge disposition for a visit.

##### preceding_visit_detail_id

A foreign key to the VISIT_DETAIL table of the visit immediately preceding this visit

##### visit_detail_parent_id

A foreign key to the VISIT_DETAIL table record to represent the parent Visit Detail this Visit Detail belongs to, to allow for multiple levels of nested visits.

##### visit_occurrence_id

A foreign key that refers to the record in the VISIT_OCCURRENCE table. This is a required field, because every visit_detail is associated with a visit_occurrence and cannot exist without a corresponding record in visit_occurrence

##### trace_id (stanford construct for traceability) 

A json string with the primary keys of the table in Clarity where most of the information for a given row is sourced

##### unit_id (stanford construct for traceability) 

Is a reference for the position in the ETL code resposible for bringing in this row data

##### load_table_id (stanford construct for traceability) 

Is the name of the primary Clarity table in Clarity where most of the information for a given row is sourced
