---
title: "HEME-STAMP Versions"
execute:
  echo: false
---


```{r, message=FALSE, warning=FALSE, echo=FALSE}
dat=readr::read_tsv(file="/workspaces/starr-oncology-data-lake-arpah/src/stamp_data_dict/oncology_stamp_metadata.tsv")

```
## HEME-STAMP-V1 {#HEME-STAMP-V1}

The following genes are listed under HEME-STAMP V1:

```{r, message=FALSE, warning=FALSE}
library(dplyr)

# Read the data
dat = readr::read_tsv(file="/workspaces/starr-oncology-data-lake-arpah/src/stamp_data_dict/oncology_stamp_metadata.tsv")

# Create the subsets
heme_v1= dat %>% 
  filter(pipeline_version == "v1" & assay_performed == "HEME-STAMP")

heme_v1$pipeline_version<-NULL
DT::datatable(heme_v1, options = list(pageLength = 25))
```

## HEME-STAMP-V2 {#HEME-STAMP-V2}

The following genes are listed under HEME-STAMP V2:

```{r, message=FALSE, warning=FALSE}
library(dplyr)

# Read the data
dat = readr::read_tsv(file="/workspaces/starr-oncology-data-lake-arpah/src/stamp_data_dict/oncology_stamp_metadata.tsv")

# Create the subsets
heme_v2= dat %>% 
  filter(pipeline_version == "v2" & assay_performed == "HEME-STAMP")

heme_v2$pipeline_version<-NULL

DT::datatable(heme_v2, options = list(pageLength = 25))
```

## HEME-STAMP-V4 {#HEME-STAMP-V4}

The following genes are listed under HEME-STAMP V4:

```{r, message=FALSE, warning=FALSE}
library(dplyr)

# Read the data
dat = readr::read_tsv(file="/workspaces/starr-oncology-data-lake-arpah/src/stamp_data_dict/oncology_stamp_metadata.tsv")

# Create the subsets
heme_v4= dat %>% 
  filter(pipeline_version == "v4" & assay_performed == "HEME-STAMP")

heme_v4$pipeline_version<-NULL

DT::datatable(heme_v4, options = list(pageLength = 25))
```