---
title: "STAMP Versions"
execute:
  echo: false
---



```{r, message=FALSE, warning=FALSE, echo=FALSE}
dat=readr::read_tsv(file="/workspaces/starr-oncology-data-lake-arpah/src/stamp_metadata/oncology_stamp_metadata.tsv")

```
## STAMP-V1 {#STAMP-V1}

The following genes are listed under STAMP V1:

```{r, message=FALSE, warning=FALSE}
library(dplyr)

# Read the data
dat = readr::read_tsv(file="/workspaces/starr-oncology-data-lake-arpah/src/stamp_metadata/oncology_stamp_metadata.tsv")

# Create the subsets
stamp_v1 = dat %>% 
  filter(pipeline_version == "v1" & assay_performed == "STAMP")

stamp_v1$pipeline_version<-NULL
DT::datatable(stamp_v1, options = list(pageLength = 25))
```

## STAMP-V2 {#STAMP-V2}

The following genes are listed under STAMP V2:

```{r, message=FALSE, warning=FALSE}
library(dplyr)

# Read the data
dat = readr::read_tsv(file="/workspaces/starr-oncology-data-lake-arpah/src/stamp_metadata/oncology_stamp_metadata.tsv")

# Create the subsets
stamp_v2 = dat %>% 
  filter(pipeline_version == "v2" & assay_performed == "STAMP")
stamp_v2$pipeline_version<-NULL

DT::datatable(stamp_v2, options = list(pageLength = 25))
```
## STAMP-V3 {#STAMP-V3}

The following genes are listed under STAMP V3:

```{r, message=FALSE, warning=FALSE}
library(dplyr)

# Read the data
dat = readr::read_tsv(file="/workspaces/starr-oncology-data-lake-arpah/src/stamp_metadata/oncology_stamp_metadata.tsv")

# Create the subsets
stamp_v3 = dat %>% 
  filter(pipeline_version == "v3" & assay_performed == "STAMP")
stamp_v3$pipeline_version<-NULL

DT::datatable(stamp_v3, options = list(pageLength = 25))
```

## STAMP-V4 {#STAMP-V4}

The following genes are listed under STAMP V4:

```{r, message=FALSE, warning=FALSE}
library(dplyr)

# Read the data
dat = readr::read_tsv(file="/workspaces/starr-oncology-data-lake-arpah/src/stamp_metadata/oncology_stamp_metadata.tsv")

# Create the subsets
stamp_v4 = dat %>% 
  filter(pipeline_version == "v4" & assay_performed == "STAMP")
stamp_v4$pipeline_version<-NULL

DT::datatable(stamp_v4, options = list(pageLength = 25))
```