---
title: "About"
back-to-top-navigation: false
---

The Virtual Intelligence for Specialized Tumor Board Assessment (VISTA) Oncology Data Lake is a multi-modal data repository designed to integrate diverse clinical modalities, including clinical notes, genomic, and imaging data to facilitate oncology research and artificial intelligence modeling. To further bridge the fragmentation of care across different clinics, VISTA Data Lake has also integrated the Stanford Cancer Registry. 
The data lake is built by Stanford Medicine's honest broker and research infrastructure team, Research Technology. The technologies and methods used by Research Technology in the development of the VISTA data lake rely on over two decades of experience in developing and managing research clinical data warehouses (see [publications](https://starr.stanford.edu/publications-0)) for the Stanford Medicine community.  

The source EHR data is from the three hospital ecosystems, Stanford Health Care and Stanford Children’s Hospital (fka Lucile Packard Children’s Hospital), and Stanford Healthcare Tri-Valley, along with a network of more than a hundred pediatric and adult care clinics affiliated with University HealthCare Alliance and Packard Children’s Health Alliance. The ecosystems use two independent Epic instances for patient care and share their Epic Clarity data with Research Technology.  One Clarity instance contains data from Stanford Health Care, Stanford Health Care Tri-Valley (includes pediatric population), and the University Healthcare Alliance. The other Clarity instance contains data from Stanford Children’s Health and the Packard Children’s Health Alliance (the adult population includes mothers).
The clinical applications for non-Epic sources, such as the Radiology DICOMs, the Whole Slide Imaging data, and the genetic testing results, are shared across the two hospital ecosystems i.e., Research Technology needs to process data from one Radiology PACS system to get the DICOMs for the entire cohort. 

The Stanford Cancer Registry is a shared system across the two hospital ecosystems. The data is managed on a vendor platform, Neuralframe KACI. NeuralFrame sends monthly snapshots of the database to Research Technology. 
The VISTA dataset has ~222K patients. Approximately 12% of the SCR patients have a Tumor Board encounter.  
 

### VISTA Cohort: Patient Inclusion Criteria
All patients included in VISTA must be present in **STARR-OMOP**, Stanford’s research-standard representation of the electronic health record (EHR), **and** have documented evidence of cancer-related care or review within the Stanford health system, defined by at least one of the following: 


1. A documented **tumor board** encounter in the source EHR OR
2. A **case record in Stanford’s Cancer Registry dataset, in Neuralframe KACI**


STARR-OMOP contains data from adult and pediatric patients seen across the Stanford hospital ecosystem whose information may be used for research* and who have at least one recorded clinical event—such as a visit, diagnosis, procedure, medication, laboratory result, imaging event, or clinical note—since January 1, 2000. We include unsigned notes- which is often the case when tumor board documentation exists. The source data for STARR -OMOP are the Adult and Pediatric EPIC Clarity databases and include Stanford HealthCare, Stanford HealthCare Tri-Valley, University Healthcare Alliance or  Stanford Medicine Partners, Lucile Packard Children’s Hospital, and Packard Children's Health Alliance.     

A patient is classified as having a tumor board encounter in STARR OMOP if the visit type contains the text “tumor board”, (irrespective of capitalization). 
Stanford’s Cancer Registry (SCR), currently managed by Neuralframe KACI, includes cancer cases from both adult and pediatric hospitals. The registry contains analytic and non-analytic cases dating back to 1988, has been maintained on multiple platforms over time, and contributes data to the California Cancer Registry (CCR). While CCR requirements have evolved over time, the SCR includes the following types of patients: 

- Analytic cases - which include patients whose first course of cancer treatment occurred at Stanford regardless of diagnosis location, as well as patients diagnosed at Stanford, even if then treated elsewhere. Note that in the latter case, our data may be incomplete.

- Non-Analytic cases -  included since 2024, which capture additional cancer-related encounters such as patients treated at Stanford only for recurrence, patients followed at Stanford and found to be cancer-free, and patients neither diagnosed nor treated at Stanford (e.g., consultation-only or end-of-life care). 

*Not all EHR data is allowed for research- for more details, see the [STARR Electronic Health Record documentation](https://starr.stanford.edu/data-types/electronic-health-record).

### Data Architecture, Privacy and Security

The VISTA data lake uses Google Cloud Platform to develop and deliver the assets. The datasets are made available as BigQuery datasets. Google BigQuery is a fully managed, serverless, HIPAA-compliant enterprise data platform optimized for high-performance analytics on massive, multimodal biomedical datasets. Using a decoupled storage-and-compute architecture, enables investigators to execute complex SQL queries in seconds.
The two independent BigQuery datasets, EHR and Registry, are linked together by the unique patient identifier (Medical Record Number AND Date of Birth). The clinical dataset is transformed from the two Epic Clarity models to the unified Observational Medical Outcomes Partnership (OMOP) Common Data Model (CDM). The data includes Epic modules such as Epic Genetics, Epic Beaker, and Epic Beacon. Metadata from DICOMs and WSI are included in custom tables in the OMOP. Best practices of OMOP transformation are followed. The registry data has minimal ETL to preserve the original California Cancer Registry data model.

The data is refreshed quarterly. Each release is accompanied by updated metrics and other release specific information on this VISTA Data Lake github. The github is also used to host data dictionaries, and metadata such as gene lists specific to each version of the genetic test.  
The datasets are PHI scrubbed using Safe Harbor approaches. Specifically, we replace PHI with surrogates. In order to maintain the patient’s timeline, the dates, including date of birth, date of death, and service dates, are shifted. The shift is unique to the patient (across all datasets and data types) and is plus or minus 30 days, but never zero. Due to the presence of large amounts of unstructured data in the VISTA data lake, including clinical notes and DICOMs, Stanford University Privacy Office has determined that additional Expert Determination is needed if the datasets need to be declared as de-identified. Currently, the security requirements are similar to NIH dbGaP datasets. 

### Dataset Overview

#### Oncology-OMOP 

The OMOP-CDM is a standardized data model designed to facilitate the analysis and sharing of healthcare data across different institutions and studies. By using a common structure and terminology, the OMOP-CDM enables researchers to perform large-scale observational research and generate real-world evidence. 

Our EHR data was initially standardized using OMOP CDM version 5.3.1 and subsequently upgraded to OMOP CDM version 5.4.2 to leverage the latest data model enhancements. For more details about the November 2025 upgrade and data evolution across releases, see the [Data Evolution Overview](data_evolution_overview.qmd) page.

The identified dataset is created using EPIC Clarity tables, which include patient and encounter data permissible for research. The tables in the OMOP-CDM common data model that are part of this dataset are listed in the [Data Dictionary](data_dictionary.qmd) page, along with information on whether they contain PHI and a brief description of each table.


#### NeuralFrame

NeuralFrame data encompasses research-eligible patients who have case records in the Neural Frame, also known as the Stanford Cancer Registry. This dataset is categorized into four main areas:

- **Outcome**: This category includes information related to patient outcomes, such as survival rates, disease progression, and overall health status.

- **Diagnoses**: This section contains details about the diagnoses made for each patient, including cancer types, staging, and any relevant comorbidity.

- **Treatment**: This category outlines the various treatments administered to patients, including surgical interventions, chemotherapy, radiation therapy, and other therapeutic approaches.

- **Miscellaneous**: This section includes additional data that may not fit into the other categories, such as demographic information, patient-reported outcomes, and other relevant clinical data.

#### Philips ISPM

- **Philips ISPM Orders**: This table contains order-level information from the Philips IntelliSpace Precision Medicine (ISPM) genomics database at Stanford. The fields in this table are related to diagnostic orders, patient demographics, and specimen accession numbers which can be used to link to the other Philips ISPM tables. 

- **Philips ISPM Aberration**: This table contains genomic testing information from the Philips IntelliSpace Precision Medicine (ISPM) genomics database at Stanford. The fields in this table are related to genomic testing details about each sample, as well as the specimen accession number which can be used to link to the Philips ISPM Orders table.

- **Philips ISPM Specimen**: This table includes specimen-related information from the Philips IntelliSpace Precision Medicine (ISPM) genomics database at Stanford. The fields in this table are related to specimen details, including accession numbers and collection information.

- Following assays are included in the Philips ISPM data:

  - **STAMP**: The Stanford Actionable Mutation Panel for Solid Tumors (STAMP) is a targeted next-generation sequencing (NGS) assay designed to detect clinically actionable mutations as well as other genes frequently altered in cancer. STAMP employs a target enrichment-based sequencing method to capture specific genomic regions of interest. The sequencing approach and integrated bio informatics pipeline are optimized for ultra-deep sequencing of formalin-fixed, paraffin-embedded (FFPE) tumor biopsy specimens. This panel focuses on clinically actionable genes, selected based on:

    - **Gene Selection Criteria**:
        - Their utility as targets of current or emerging anti-cancer therapies
        - Their prognostic value
        - Their mutation frequency across known cancer types

    - **Technical Specifications**:
        - Sequencing is performed using an **Illumina** platform
        - Minimum limit of detection (LOD) of **5% variant allele frequency (VAF)**
        - Genomic coordinates reported relative to **GRCh37 (hg19)**

   - **Heme-STAMP**: The Stanford Actionable Mutation Panel for Hematopoietic and Lymphoid Malignancies (Heme-STAMP) is a targeted next-generation sequencing (NGS) assay designed to detect single nucleotide variants (SNVs), short insertion–deletions (indels), and selected gene fusions across 203 genes recurrently altered in myeloid and lymphoid neoplasms. Heme-STAMP employs a target enrichment–based sequencing method, beginning with acoustic shearing of genomic DNA, followed by sequencing library preparation and capture of genomic regions of interest using custom-designed oligonucleotide probes.

      - **Gene Selection Criteria**:
        - Clinical relevance as targets of existing or emerging anti-cancer therapies
        - Prognostic significance in hematopoietic malignancies
        - Recurrence frequency across patients with myeloid and lymphoid neoplasms
      - **Technical Specifications**:
        - Sequencing performed on an Illumina platform
        - Minimum limit of detection (LOD) of 5% variant allele frequency (VAF) for SNVs and indels
        - Targets 203 genes (either fully or partially covered)
        - Pooled libraries prepared through acoustic shearing and targeted enrichment

   - **FoundationOne Heme** is designed to include genes known to be somatically altered in human hematologic malignancies and sarcomas that are validated targets for therapy, either approved or in clinical trials, and/or that are unambiguous drivers of oncogenesis based on current knowledge. The current assay utilizes DNA sequencing to interrogate 406 genes as well as selected introns of 31 genes involved in rearrangements, in addition to RNA sequencing of 265 genes. The assay will be updated periodically to reflect new knowledge about cancer biology.

   - **FoundationOne CDx™ (F1CDx)** is a next generation sequencing based in vitro diagnostic device for detection of substitutions, insertion and deletion alterations (indels), and copy number alterations (CNAs) in 324 genes and select gene rearrangements, as well as genomic signatures including microsatellite instability (MSI) and tumor mutational burden (TMB) using DNA isolated from formalin-fixed paraffin embedded (FFPE) tumor tissue specimens.

   - **FoundationOne Liquid CDx** is a qualitative next generation sequencing based in vitro diagnostic test that uses targeted high throughput hybridization-based capture technology to detect and report substitutions, insertions and deletions (indels) in 311 genes, including rearrangements in eight (8) genes, and copy number alterations in three (3) genes. FoundationOne Liquid CDx utilizes circulating cell-free DNA (cfDNA) isolated from plasma derived from anti-coagulated peripheral whole blood of cancer patients. 

#### STAMP Add-On

- The STAMP Add-On includes the ‘assay performed’ value, which specifies the type of STAMP test result; For example, the Stanford Actionable Mutation Panel for Solid Tumors (STAMP, Order Code: [STAMPT](https://stanfordlab.com/test-details/s/STAMPT.html) or Heme-STAMP, which includes both Heme-STAMP, Blood (Order Code: [HSTAMPB](https://stanfordlab.com/content/stanfordlab/en/test-details/h/HSTAMPB.html)) and Heme-STAMP, Non-Blood (Order Code: [HSTAMPT](https://stanfordlab.com/content/stanfordlab/en/test-details/h/HSTAMPT.html). In addition, the Add-On contains pipeline version information, along with patient identifiers and accession numbers.

#### HIPPO Benchmark

HIPPO stands for Human-in-the-loop Identification of PHI with Preserved Output. This is a corpus of 1,394 clinical notes sampled from STARR-OMOP. The PHI within the corpus was annotated by expert annotators. The full methodology describing dataset generation can be found [here](feb_2025/phi_labeling_process.qmd).

#### Lung Resection CAP Forms

This is a fully identified dataset that contains a combination of structured and unstructured information. A description of the CAP forms itself and their purpose can be found [here](aug_2025/cap_forms_methods.qmd) and [here](https://www.cap.org/protocols-and-guidelines/cancer-reporting-tools/cancer-protocol-templates). This dataset only contains Lung Resection CAP forms.

#### Epic Media Server Documents

This is a fully identified dataset that contains all PDFs for cancer patients that currently exist in the EPIC Media (BLOB) Server and are included in the VISTA data lake. These documents:

- Are displayed in the Media and Lab tab in Epic Hyperspace
- Typically originate from third party service providers 
- Are pulled into VISTA via the Mulesoft API

### Metadata

The metadata includes DICOM dictionary, listed genes for STAMP and HEME-STAMP versions, and relative BED files. 


### Dataset Releases

We periodically release updated versions of our datasets to ensure that researchers have access to the most current and comprehensive data available. Below are the details of our latest dataset releases:

* [February 2025](feb_2025/released_datasets.qmd)
* [May 2025](may_2025/released_datasets.qmd)
* [August 2025](aug_2025/released_datasets.qmd)
* [November 2025](nov_2025/released_datasets.qmd)
* [February 2026](feb_2026/released_datasets.qmd)
* [May 2026](may_2026/released_datasets.qmd)

## Data Privacy and Security

We prioritize patient privacy and data security. Our datasets undergo rigorous phi scrubbing processes. Most vocabulary tables contain standard terminology, do not vary between institutions, and do not contain any PHI. We have included all populated tables in the CDM, along with descriptions of the fields, on this website.

## Project Resources

For more information regarding our source data and methods, please refer to the following resources:

- **Source Data**
    - [Imaging](https://starr.stanford.edu/data-types/imaging)
    - [Death Data](https://starr.stanford.edu/data-types/death-data)
- **Methods**
    - [Text De-identification](https://starr.stanford.edu/methods/tide-clinical-text-safe-harbor)
    - [Imaging De-identification](https://starr.stanford.edu/methods/dicom-safe-harbor-phi-scrubbing)
- [**Publications**](https://starr.stanford.edu/publications-0 )


## Acknowledgments

This research was funded, in part, by the Advanced Research Projects Agency for Health (ARPA-H). The views and conclusions contained in this document are those of the authors and should not be interpreted as representing the official policies, either expressed or implied, of the U.S. Government.

