---
title: "ARPAH Demographic Metrics"
execute:
  echo: false
---
The Advanced Research Projects Agency for Health (ARPA-H) is a research funding agency that supports transformative biomedical and health breakthroughs – ranging from the molecular to the societal – to provide health solutions for all.
For more information, you can [Visit Stanford News](https://med.stanford.edu/news/all-news/2024/10/arpa-h-contracts).


# **Clinical Metrics*

```{r}
# set wrking directory
setwd("/workspaces/starr-oncology-data-lake-arpah/src")
source("/workspaces/starr-oncology-data-lake-arpah/src/R/all_function.R", encoding = "UTF-8")

```
```{r}
## pull arpah clinical metrics ##
credentials_path <- "/home/rstudio/.config/gcloud/application_default_credentials.json"
folder_path <- "/workspaces/starr-oncology-data-lake-arpah/src/sql/arpah_clinical"
 project_name = "som-rit-phi-oncology-prod"
res_arpah <- fetch_data_from_sql(credentials_path, project_name, folder_path)
```

```{r}
credentials_path <- "/home/rstudio/.config/gcloud/application_default_credentials.json"
folder_path_tb <- "/workspaces/starr-oncology-data-lake-arpah/src/sql/tumor_board"
project_name = "som-rit-phi-oncology-prod"
res_tb <- fetch_data_from_sql(credentials_path, project_name, folder_path_tb)
```
```{r}
colnames(res_arpah)[1]<-"pt_count_arph"
res_tb$sql_file_name=gsub("tumor_board_","", res_tb$sql_file_name)
colnames(res_tb)[1]<-"pt_count_tb"
```
```{r}
res_all=res_arpah %>% inner_join(res_tb, by="sql_file_name")
print(res_all)
```
```{r}
res_all <- res_all %>%
  mutate(
    metric = case_when(
      sql_file_name == "note_path_cyto_person_metrics.sql" ~ "with pathology/cytology clinical report", 
      sql_file_name == "note_imaging_person_metrics.sql" ~ "with imaging reports, also a proxy for radiology imaging data",
      sql_file_name == "philips_person_metrics.sql" ~ "have molecular mutation structured data (Philips ISPM)",
      sql_file_name == "vital_status_person_metrics.sql" ~ "present Hospital or Stanford Cancer Registry death date", 
      sql_file_name == "omop_chemo_person_metrics.sql" ~ "given chemo medication",
      sql_file_name == "aria_person_metrics.sql" ~ "given radiation therapy (ARIA)",
      sql_file_name == "wsi_beaker_path_person_metrics.sql" ~ "with WSI (based on EPIC Beaker AP/Pathology, starting from 2022)",
      sql_file_name == "powerpath_beaker_path_person_metrics.sql" ~ "pathology beaker",
      sql_file_name == "powerpath_path_person_metrics.sql" ~ "pathology path",
      TRUE ~ NA_character_  
    )
  )
print(res_all)
res_all=res_all %>% filter(!is.na(metric))
print(res_all)

```
```{r}
res_all<-res_all%>% select(metric, everything())
```

```{r, message=FALSE, warning=FALSE}

res_all%>%select (-sql_file_name)%>%
  gt() %>%
  cols_label(
    metric = "Clinical Metrics",
    pt_count_arph = "ARPAH Count (N)",
    pt_count_tb="Tumor Board Count (N)",
  ) %>%
  tab_header(
    title = "Clinical Metrics",
    subtitle = "ARPAH Cohort"
  ) %>%
  fmt_number(
    columns = where(is.numeric),
    decimals = 0
  ) %>%
  cols_align(
    align = "center",
    columns = vars(pt_count_arph, pt_count_tb)  # Specify the columns to center
  ) %>%
  tab_options(
    table.font.size = px(14),
    heading.align = "left",
    table.border.top.color = "darkred",
    table.align = "left"
  ) %>%
  opt_row_striping()
```


## end 
