---
title: "Data Metrics"
execute:
  echo: false
---

This page provides an overview of the various data metrics available in the dataset. The metrics are designed to give insights into the contents of the dataset.

## Release Overview

This project will have multiple data releases over time. Each release will include updated and new metrics. Below is the list of available releases:

### February 2025

The February 2025 release is the first release of the dataset. It includes comprehensive demographic metrics and other key data points. You can find detailed information about this release by following the link below:

- [February 2025 Metrics](feb_2025/demographic_clinical.qmd)

### May 2025

The May 2025 release is the second release of the dataset which includes additional data sources such as OMOP image occurrence, Philips ISPM, and Stanford cancer registry. You can find detailed information about this release by following the link below:

- [May 2025 Metrics](may_2025/metrics_clinical.qmd)

### August 2025

The August 2025 release is the third release of the dataset which includes additional data sources such as OMOP image occurrence, Philips ISPM, Stanford cancer registry, and STAMP Add-On data. You can find detailed information about this release by following the link below:

- [August 2025 Metrics](aug_2025/metrics_clinical.qmd)

## Future Releases

Future releases will include additional metrics and updates to the existing ones.
